return {
["tutorial"]={
},
["descriptions"]={
["Back"]={
["b_challenge"]={
["name"]="挑战牌组",
["text"]={
[1]="",
},
},
["b_plasma"]={
["name"]="等离子牌组",
["text"]={
[1]="计算出牌分数时",
[2]="平衡{C:blue}筹码{}和",
[3]="{C:red}倍率{}",
[4]="盲注要求分数{C:red}X#1#{}",
},
},
["b_nebula"]={
["name"]="星云牌组",
["text"]={
[1]="开局时拥有",
[2]="{C:planet,T:v_telescope}#1#{}张优惠券",
[3]="",
[4]="{C:red}#2#{}消耗牌槽位",
},
},
["b_anaglyph"]={
["name"]="浮雕牌组",
["text"]={
[1]="击败每个",
[2]="{C:attention}Boss盲注{}后，获得一个",
[3]="{C:attention,T:tag_double}#1#",
},
},
["b_black"]={
["name"]="黑色牌组",
["text"]={
[1]="每回合",
[2]="",
[3]="{C:attention}+#1#{}小丑牌槽位",
[4]="{C:blue}-#2#{}次出牌",
},
},
["b_ghost"]={
["name"]="幽灵牌组",
["text"]={
[1]="{C:spectral}幻灵牌{}可能",
[2]="出现在商店中，",
[3]="初始带有{C:spectral,T:c_hex}妖法{}牌",
},
},
["b_abandoned"]={
["name"]="废弃牌组",
["text"]={
[1]="开局时",
[2]="玩家牌组中",
[3]="没有{C:attention}人头牌",
},
},
["b_erratic"]={
["name"]="古怪牌组",
["text"]={
[1]="所有{C:attention}牌级{}和",
[2]="牌组的{C:attention}花色{}",
[3]="都是随机的",
},
},
["b_magic"]={
["name"]="魔法牌组",
["text"]={
[1]="开局时拥有",
[2]="{C:tarot,T:v_crystal_ball}#1#{}张优惠券",
[3]="和{C:attention}2{}份",
[4]="{C:tarot,T:c_fool}#2#",
},
},
["b_red"]={
["name"]="红色牌组",
["text"]={
[1]="每回合",
[2]="{C:red}+#1#{}次弃牌",
},
},
["b_painted"]={
["name"]="彩绘牌组",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
[2]="{C:red}#2#{}小丑牌槽位",
},
},
["b_blue"]={
["name"]="蓝色牌组",
["text"]={
[1]="每回合",
[2]="{C:blue}+#1#{}次出牌",
},
},
["b_checkered"]={
["name"]="方格牌组",
["text"]={
[1]="开局时",
[2]="牌组中有{C:attention}26{C:spades}张黑桃{}和",
[3]="{C:attention}26{C:hearts}张红桃{}",
},
},
["b_green"]={
["name"]="绿色牌组",
["text"]={
[1]="每回合结束时：",
[2]="每剩一次{C:blue}出牌次数，获得{C:money}$#1#{s:0.85}",
[3]="每剩一次{C:red}弃牌次数，获得{C:money}$#2#{s:0.85}",
[4]="不赚取任何{C:attention}利息",
},
},
["b_yellow"]={
["name"]="黄色牌组",
["text"]={
[1]="每回合开始",
[2]="额外获得{C:money}$#1#",
},
},
["b_zodiac"]={
["name"]="黄道牌组",
["text"]={
[1]="开局时即拥有",
[2]="{C:tarot,T:v_tarot_merchant}#1#{}、",
[3]="{C:planet,T:v_planet_merchant}#2#{}、",
[4]="和{C:attention,T:v_overstock_norm}#3#",
},
},
},
["Tag"]={
["tag_handy"]={
["name"]="便携式标签",
["text"]={
[1]="本赛局每打出一次{C:blue}手牌{}",
[2]="获得{C:money}$#1#{}",
[3]="{C:inactive}（将给 {C:money}$#2#{C:inactive}）",
},
},
["tag_standard"]={
["name"]="标准标签",
["text"]={
[1]="获得一个免费的",
[2]="{C:attention}超大标准包",
},
},
["tag_d_six"]={
["name"]="D6标签",
["text"]={
[1]="下一家商店重掷",
[2]="起价为{C:money}$0",
},
},
["tag_negative"]={
["name"]="负片标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:dark_edition}负片小丑牌",
},
},
["tag_investment"]={
["name"]="投资标签",
["text"]={
[1]="击败",
[2]="Boss盲注后，",
[3]="获得{C:money}$#1#",
},
},
["tag_holo"]={
["name"]="镭射标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:dark_edition}镭射小丑牌",
},
},
["tag_rare"]={
["name"]="稀有标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:red}稀有小丑牌，",
},
},
["tag_skip"]={
["name"]="速度标签",
["text"]={
[1]="本赛局中每跳过",
[2]="一次盲注，获得{C:money}$#1#{}",
[3]="{C:inactive}（将获得 {C:money}$#2#{C:inactive}）",
},
},
["tag_garbage"]={
["name"]="垃圾标签",
["text"]={
[1]="本赛局每一未使用的{C:red}弃牌数{}",
[2]="得到{C:money}$#1#{}",
[3]="{C:inactive}（将得到 {C:money}$#2#{C:inactive}）",
},
},
["tag_foil"]={
["name"]="闪箔标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:dark_edition}闪箔小丑牌",
},
},
["tag_buffoon"]={
["name"]="小丑标签",
["text"]={
[1]="获得一个免费的",
[2]="{C:attention}小丑包",
},
},
["tag_charm"]={
["name"]="吊饰标签",
["text"]={
[1]="获得一个免费的",
[2]="{C:tarot}超级秘术包",
},
},
["tag_ethereal"]={
["name"]="空灵标签",
["text"]={
[1]="获得一个免费的",
[2]="{C:spectral}幻灵包",
},
},
["tag_orbital"]={
["name"]="轨道标签",
["text"]={
[1]="升级{C:attention}#1#",
[2]="{C:attention}#2#个等级",
},
},
["tag_coupon"]={
["name"]="折扣券标签",
["text"]={
[1]="下一家店内的",
[2]="初始卡牌和补充包",
[3]="均为免费",
},
},
["tag_boss"]={
["name"]="Boss标签",
["text"]={
[1]="重掷",
[2]="{C:attention}Boss盲注",
},
},
["tag_top_up"]={
["name"]="充值标签",
["text"]={
[1]="产生最多{C:attention}#1#张",
[2]="{C:blue}普通{}小丑牌",
[3]="{C:inactive}（必须有空位）",
},
},
["tag_polychrome"]={
["name"]="多彩标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:dark_edition}多彩小丑牌",
},
},
["tag_meteor"]={
["name"]="流星标签",
["text"]={
[1]="获得一个免费的",
[2]="{C:planet}超级天体包",
},
},
["tag_double"]={
["name"]="双倍标签",
["text"]={
[1]="复制下一个",
[2]="选定的{C:attention}标签{}",
[3]="{s:0.8,C:attention}双倍标签{s:0.8}除外",
},
},
["tag_juggle"]={
["name"]="戏法标签",
["text"]={
[1]="下一回合",
[2]="{C:attention}+#1#{}手牌大小",
},
},
["tag_economy"]={
["name"]="经济标签",
["text"]={
[1]="资金翻倍",
[2]="{C:inactive}（最高 {C:money}$#1#{C:inactive}）",
},
},
["tag_uncommon"]={
["name"]="罕见标签",
["text"]={
[1]="下个商店内有一张",
[2]="{C:green}罕见小丑牌",
},
},
["tag_voucher"]={
["name"]="优惠券标签",
["text"]={
[1]="添加一张{C:voucher}优惠券",
[2]="到下一家商店",
},
},
},
["Blind"]={
["bl_club"]={
["name"]="梅花",
["text"]={
[1]="所有梅花牌",
[2]="都不计分",
},
},
["bl_needle"]={
["name"]="针",
["text"]={
[1]="这一回合只能出一次牌",
},
},
["bl_small"]={
["name"]="小盲注",
["text"]={
},
},
["bl_arm"]={
["name"]="手臂",
["text"]={
[1]="降低已出",
[2]="牌型等级",
},
},
["bl_plant"]={
["name"]="植物",
["text"]={
[1]="所有人头牌",
[2]="都不计分",
},
},
["bl_wheel"]={
["name"]="车轮",
["text"]={
[1]="/7的概率一张牌",
[2]="以背面朝上的方式抽取",
},
},
["bl_mouth"]={
["name"]="嘴巴",
["text"]={
[1]="本回合只能打出",
[2]="1种牌型",
},
},
["bl_eye"]={
["name"]="眼睛",
["text"]={
[1]="本回合中不可",
[2]="打出重复牌型",
},
},
["bl_pillar"]={
["name"]="支柱",
["text"]={
[1]="上一次底注中",
[2]="打过的牌都不计分",
},
},
["bl_house"]={
["name"]="房屋",
["text"]={
[1]="第一次的手牌",
[2]="以背面朝上方式抽取",
},
},
["bl_hook"]={
["name"]="钩子",
["text"]={
[1]="每次出牌",
[2]="随机弃掉2张手牌",
},
},
["bl_head"]={
["name"]="头部",
["text"]={
[1]="所有红桃牌",
[2]="都不计分",
},
},
["bl_goad"]={
["name"]="挑衅",
["text"]={
[1]="所有黑桃牌",
[2]="都不计分",
},
},
["bl_final_leaf"]={
["name"]="绿叶",
["text"]={
[1]="所有卡牌都不计分",
[2]="直到售出1张小丑牌",
},
},
["bl_ox"]={
["name"]="公牛",
["text"]={
[1]="打出#1#牌型时，",
[2]="资金归$0",
},
},
["bl_mark"]={
["name"]="标记",
["text"]={
[1]="所有人头牌都是",
[2]="以背面朝上的方式抽取",
},
},
["bl_final_vessel"]={
["name"]="紫罗兰容器",
["text"]={
[1]="超大盲注",
},
},
["bl_tooth"]={
["name"]="牙齿",
["text"]={
[1]="每出一张牌",
[2]="损失$1",
},
},
["bl_fish"]={
["name"]="鱼",
["text"]={
[1]="在第一次出牌后",
[2]="抽的牌都是面朝下抽出",
},
},
["bl_big"]={
["name"]="大盲注",
["text"]={
},
},
["bl_final_acorn"]={
["name"]="琥珀橡子",
["text"]={
[1]="翻转并洗乱",
[2]="所有小丑牌",
},
},
["bl_flint"]={
["name"]="燧石",
["text"]={
[1]="基础筹码和",
[2]="倍率减半",
},
},
["bl_psychic"]={
["name"]="灵媒",
["text"]={
[1]="必须出 5 张牌",
},
},
["bl_window"]={
["name"]="窗口",
["text"]={
[1]="所有方片牌",
[2]="都不计分",
},
},
["bl_serpent"]={
["name"]="巨蟒",
["text"]={
[1]="出牌或弃牌后，",
[2]="总是抽 3 张牌",
},
},
["bl_water"]={
["name"]="水",
["text"]={
[1]="以0弃牌",
[2]="次数开始",
},
},
["bl_manacle"]={
["name"]="镣铐",
["text"]={
[1]="手牌大小-1",
},
},
["bl_wall"]={
["name"]="围墙",
["text"]={
[1]="特大盲注",
},
},
["bl_final_heart"]={
["name"]="绯红之心",
["text"]={
[1]="每次出牌",
[2]="使任一小丑牌功能失效",
},
},
["bl_final_bell"]={
["name"]="蔚蓝钟",
["text"]={
[1]="迫使 1 张牌",
[2]="总是被选中",
},
},
},
["Voucher"]={
["v_tarot_merchant"]={
["name"]="塔罗牌商人",
["text"]={
[1]="商店内",
[2]="{C:tarot}塔罗牌{}出现",
[3]="频率增加{C:attention}X#1#{}倍",
},
},
["v_magic_trick"]={
["name"]="魔术",
["text"]={
[1]="{C:attention}商店{}里面",
[2]="有{C:attention}游戏牌{}",
[3]="可供选购",
},
},
["v_seed_money"]={
["name"]="种子基金",
["text"]={
[1]="每回合",
[2]="已获利息",
[3]="上限提高到{C:money}$#1#{}",
},
},
["v_tarot_tycoon"]={
["unlock"]={
[1]="在商店",
[2]="购买总计",
[3]="{C:attention}#1#张{C:tarot}塔罗牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="塔罗大亨",
["text"]={
[1]="商店内",
[2]="{C:tarot}星球牌{}出现",
[3]="频率增加{C:attention}X#1#{}倍",
},
},
["v_overstock_norm"]={
["name"]="库存过剩",
["text"]={
[1]="店內卡牌槽位",
[2]="{C:attention}+1{}",
},
},
["v_wasteful"]={
["name"]="废物",
["text"]={
[1]="每回合",
[2]="永久增加",
[3]="{C:blue}+#1#{}次弃牌",
},
},
["v_grabber"]={
["name"]="抓手",
["text"]={
[1]="每回合",
[2]="永久增加",
[3]="{C:blue}+#1#{}次出牌",
},
},
["v_paint_brush"]={
["name"]="油漆刷",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
},
},
["v_money_tree"]={
["unlock"]={
[1]="每回合利息收入",
[2]="提升到最高，",
[3]="持续{C:attention}#1#{}回合",
[4]="{C:inactive}(#2#)",
},
["name"]="摇钱树",
["text"]={
[1]="每回合",
[2]="已获利息",
[3]="上限提高到{C:money}$#1#{}",
},
},
["v_clearance_sale"]={
["name"]="清仓特卖",
["text"]={
[1]="所有卡牌和卡牌包",
[2]="在店内费用减{C:attention}#1#%{}",
},
},
["v_hone"]={
["name"]="打磨",
["text"]={
[1]="{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}和",
[2]="{C:dark_edition}多彩{}卡",
[3]="出现频率{C:attention}X#1#{}倍",
},
},
["v_liquidation"]={
["unlock"]={
[1]="在一场赛局中",
[2]="至少兑换",
[3]="{C:attention}#1#{C:voucher}张优惠券{}",
},
["name"]="清算",
["text"]={
[1]="所有卡牌和卡牌包",
[2]="在店内均可享受{C:attention}#1#%{}折扣",
},
},
["v_hieroglyph"]={
["name"]="象形文字",
["text"]={
[1]="{C:attention}-#1#{}底注",
[2]="每回合",
[3]="{C:blue}-#1#{}出牌次数",
},
},
["v_omen_globe"]={
["unlock"]={
[1]="从任何{C:tarot}秘术包中",
[2]="总共使用{C:attention}#1#张",
[3]="{C:tarot}塔罗牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="预兆球",
["text"]={
[1]="{C:spectral}幻灵牌{}可能",
[2]="会在任何",
[3]="{C:attention}秘术包中出现",
},
},
["v_telescope"]={
["name"]="望远镜",
["text"]={
[1]="{C:attention}天体包中的",
[2]="{C:planet}星球牌{}{}始终有",
[3]="你最常用的",
[4]="的{C:attention}牌型",
},
},
["v_planet_tycoon"]={
["unlock"]={
[1]="在商店",
[2]="购买总计",
[3]="{C:attention}#1#{}张{C:planet}星球牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="星球大亨",
["text"]={
[1]="商店内",
[2]="{C:tarot}星球牌{}出现",
[3]="频率增加{C:attention}X#1#{}倍",
},
},
["v_illusion"]={
["unlock"]={
[1]="在商店",
[2]="购买总计",
[3]="{C:attention}#1#{}张游戏牌",
[4]="{C:inactive}(#2#)",
},
["name"]="幻觉",
["text"]={
[1]="{C:attention}游戏牌{}在店内",
[2]="可以是{C:enhanced}增强卡牌{}、",
[3]="{C:dark_edition}不同版本{}，和/或{C:attention}蜡封{}",
},
},
["v_reroll_glut"]={
["unlock"]={
[1]="重掷商店",
[2]="总共{C:attention}#1#{}次",
[3]="{C:inactive}(#2#)",
},
["name"]="重掷加強版",
["text"]={
[1]="重掷费用",
[2]="减少{C:money}$#1#{}",
},
},
["v_glow_up"]={
["unlock"]={
[1]="手上的牌至少要有{C:attention}#1#张",
[2]="{C:attention}小丑牌{}且为",
[3]="{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}，或",
[4]="{C:dark_edition}多彩{}卡版型",
},
["name"]="焕彩",
["text"]={
[1]="{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}和",
[2]="{C:dark_edition}多彩{}卡",
[3]="出现频率{C:attention}X#1#{}倍",
},
},
["v_retcon"]={
["unlock"]={
[1]="发现",
[2]="{C:attention}#1#{}盲注",
},
["name"]="重构",
["text"]={
[1]="重掷Boss盲注",
[2]="{C:attention}不限{}次数",
[3]="每次重掷获得{C:money}$#1#{}",
},
},
["v_nacho_tong"]={
["unlock"]={
[1]="打出总共",
[2]="{C:attention}#1#{}张卡牌",
[3]="{C:inactive}(#2#)",
},
["name"]="纳乔之舌",
["text"]={
[1]="每回合",
[2]="永久",
[3]="增加{C:blue}+#1#{}次出牌",
},
},
["v_observatory"]={
["unlock"]={
[1]="从任何{C:planet}天体包中",
[2]="总共使用{C:attention}#1#张",
[3]="{C:planet}星球牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="天文台",
["text"]={
[1]="在您{C:attention}消耗牌栏位{}中",
[2]="的{C:planet}星球牌{}",
[3]="为该特定{C:attention}手牌类型",
[4]="给予{X:red,C:white}X#1#{}倍率",
},
},
["v_reroll_surplus"]={
["name"]="多次重掷",
["text"]={
[1]="重掷费用",
[2]="减少{C:money}$#1#{}",
},
},
["v_recyclomancy"]={
["unlock"]={
[1]="弃牌总数达到",
[2]="{C:attention}#1#{}张卡牌",
[3]="{C:inactive}(#2#)",
},
["name"]="回收魔法",
["text"]={
[1]="每回合",
[2]="永久",
[3]="增加{C:blue}+#1#{}次弃牌",
},
},
["v_palette"]={
["unlock"]={
[1]="手牌大小减少",
[2]="至 {C:attention}#1#{}张",
},
["name"]="调色板",
["text"]={
[1]="手牌中持有的",
},
},
["v_overstock_plus"]={
["unlock"]={
[1]="在商店内总共花费",
[2]="{C:money}$#1#{}",
[3]="{C:inactive}（$#2#）",
},
["name"]="库存过剩加强版",
["text"]={
[1]="店內卡牌槽位",
[2]="{C:attention}+1{}",
},
},
["v_blank"]={
["name"]="空白",
["text"]={
[1]="{C:inactive}什么都没有？",
},
},
["v_directors_cut"]={
["name"]="导演剪辑版",
["text"]={
[1]="重掷Boss盲注",
[2]="每个底注重掷{C:attention}1{}次",
[3]="每次{C:money}$#1#{}",
},
},
["v_petroglyph"]={
["unlock"]={
[1]="达到底注",
[2]="等级{E:1,C:attention}#1#",
},
["name"]="岩画",
["text"]={
[1]="{C:attention}-#1#{}底注",
[2]="每回合",
[3]="{C:red}-#1#{}次弃牌",
},
},
["v_planet_merchant"]={
["name"]="星球牌商人",
["text"]={
[1]="商店内",
[2]="{C:planet}星球牌{}出现",
[3]="频率增加{C:attention}X#1#{}倍 ",
},
},
["v_antimatter"]={
["unlock"]={
[1]="兑换{C:voucher}空白{}优惠券",
[2]="总计{C:attention}#1#{}次",
[3]="{C:inactive}(#2#)",
},
["name"]="反物质",
["text"]={
[1]="{C:dark_edition}+1{}小丑牌槽位",
},
},
["v_crystal_ball"]={
["name"]="水晶球",
["text"]={
[1]="{C:attention}+1{}消耗牌槽位",
},
},
},
["Enhanced"]={
["m_stone"]={
["name"]="石头牌",
["text"]={
[1]="{C:chips}+#1#{}筹码",
[2]="无点数无花色",
},
},
["m_mult"]={
["name"]="倍率牌",
["text"]={
[1]="{C:mult}+#1#{}倍率",
},
},
["m_wild"]={
["name"]="万能牌",
["text"]={
[1]="可以视作",
[2]="任何花色",
},
},
["m_glass"]={
["name"]="玻璃牌",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍率，",
[2]="有{C:green}#2#/#3#{}的几率",
[3]="摧毁牌卡",
},
},
["m_steel"]={
["name"]="钢铁牌",
["text"]={
[1]="当手中",
[2]="持有该牌时",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["m_bonus"]={
["name"]="奖励牌",
["text"]={
},
},
["m_gold"]={
["name"]="黄金牌",
["text"]={
[1]="如果这张卡牌",
[2]="在回合结束时还在手中，",
[3]="获得{C:money}$#1#{}",
},
},
["m_lucky"]={
["name"]="幸运牌",
["text"]={
[1]="{C:green}#1#/#3#{}的几率",
[2]="{C:mult}+#2#{}倍率",
[3]="{C:green}#1#/#5#{}的几率",
[4]="获得{C:money}$#4#",
},
},
},
["Tarot"]={
["c_sun"]={
["name"]="太阳",
["text"]={
[1]="最多可转换",
[2]="{C:attention}#1#{}张选定卡牌",
[3]="至{V:1}#2#{}",
},
},
["c_empress"]={
["name"]="皇后",
["text"]={
[1]="增强{C:attention}#1#张",
[2]="选定卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_star"]={
["name"]="星星",
["text"]={
[1]="最多可转换",
[2]="{C:attention}#1#{}张选定卡牌",
[3]="至{V:1}#2#{}",
},
},
["c_judgement"]={
["name"]="审判",
["text"]={
[1]="产生一张随机的",
[2]="{C:attention}{}小丑牌",
[3]="{C:inactive}（必须有空位）",
},
},
["c_death"]={
["name"]="死神",
["text"]={
[1]="选定{C:attention}#1#{}张卡牌，",
[2]="将{C:attention}左侧{}牌",
[3]="转换为{C:attention}右侧{}牌",
[4]="{C:inactive}（拖动重新排列）",
},
},
["c_wheel_of_fortune"]={
["name"]="命运之轮",
["text"]={
[1]="有{C:green}#1#/#2#{}的几率",
[2]="添加{C:dark_edition}闪箔{}、{C:dark_edition}镭射{}",
[3]="或{C:dark_edition}多彩{}版本",
[4]="添加给一张随机{C:attention}小丑牌",
},
},
["c_heirophant"]={
["name"]="教皇",
["text"]={
[1]="增强{C:attention}#1#张",
[2]="选定卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_fool"]={
["name"]="愚者",
["text"]={
[1]="产生本赛局中",
[2]="上一次使用的",
[3]="{C:tarot}塔罗牌{}或{C:planet}星球牌{}",
[4]="不包括{s:0.8,C:tarot}愚者牌{s:0.8}",
},
},
["c_high_priestess"]={
["name"]="女祭司",
["text"]={
[1]="产生最多{C:attention}#1#张",
[2]="张随机{C:planet}星球牌{}",
[3]="{C:inactive}（必须有空位）",
},
},
["c_chariot"]={
["name"]="战车",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_lovers"]={
["name"]="恋人",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_hanged_man"]={
["name"]="倒吊人",
["text"]={
[1]="最多可摧毁",
[2]="{C:attention}#1#{}张选定卡牌",
},
},
["c_strength"]={
["name"]="力量",
["text"]={
[1]="将最多",
[2]="{C:attention}#1#{}张选定",
[3]="卡牌点数提高{C:attention}1",
},
},
["c_world"]={
["name"]="世界",
["text"]={
[1]="最多可转换",
[2]="{C:attention}#1#{}张选定卡牌",
[3]="至{V:1}#2#{}",
},
},
["c_hermit"]={
["name"]="隐士",
["text"]={
[1]="金钱加倍",
[2]="{C:inactive}（最高 {C:money}$#1#{C:inactive}）",
},
},
["c_devil"]={
["name"]="魔鬼",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_magician"]={
["name"]="魔术师",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_moon"]={
["name"]="月亮",
["text"]={
[1]="最多可转换",
[2]="{C:attention}#1#{}张选定卡牌",
[3]="至{V:1}#2#{}",
},
},
["c_emperor"]={
["name"]="皇帝",
["text"]={
[1]="产生最多{C:attention}#1#张",
[2]="随机{C:tarot}塔罗牌{}",
[3]="{C:inactive}（必须有空位）",
},
},
["c_temperance"]={
["name"]="节制",
["text"]={
[1]="给出当前",
[2]="所有小丑牌{C:inactive}的",
[3]="总卖价（最高 {C:money}$#1#{C:inactive}）",
[4]="{C:inactive}（当前{C:money}$#2#{C:inactive}）",
},
},
["c_tower"]={
["name"]="高塔",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
["c_justice"]={
["name"]="正义",
["text"]={
[1]="增强{C:attention}#1#{}张选定",
[2]="卡牌成为",
[3]="{C:attention}#2#",
},
},
},
["Stake"]={
["stake_green"]={
["name"]="绿注",
["text"]={
[1]="所需分数随每个底注{C:attention}变化",
[2]="速度更快",
[3]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_blue"]={
["name"]="蓝注",
["text"]={
[1]="弃牌数{C:red}-1{}",
[2]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_white"]={
["name"]="白注",
["text"]={
[1]="基础难度",
},
},
["stake_red"]={
["name"]="红注",
["text"]={
[1]="{C:attention}小盲注{}",
[2]="没有奖励金",
[3]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_black"]={
["name"]="黑注",
["text"]={
[1]="商店可以拥有{C:attention}永恒{}小丑牌",
[2]="{C:inactive,s:0.8}(无法卖出或摧毁)",
[3]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_orange"]={
["name"]="橙注",
["text"]={
[1]="{C:attention}补充包{}成本",
[2]="每个底注增加{C:money}$1{}",
[3]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_purple"]={
["name"]="紫注",
["text"]={
[1]="所需分数随每个底注{C:attention}变化",
[2]="速度更快",
[3]="{s:0.8}适用于之前的所有赌注",
},
},
["stake_gold"]={
["name"]="金注",
["text"]={
[1]="{C:attention}-1{}手牌大小",
[2]="{s:0.8}应用于此前所有赌注",
},
},
},
["Planet"]={
["c_pluto"]={
["name"]="冥王星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_neptune"]={
["name"]="海王星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_mercury"]={
["name"]="水星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_jupiter"]={
["name"]="木星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_venus"]={
["name"]="金星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_mars"]={
["name"]="火星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_eris"]={
["name"]="阋神星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="{C:chips}+#4#{}筹码",
},
},
["c_earth"]={
["name"]="地球",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_ceres"]={
["name"]="谷神星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_saturn"]={
["name"]="土星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_planet_x"]={
["name"]="X行星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
["c_uranus"]={
["name"]="天王星",
["text"]={
[1]="{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}等级提升",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍率并且",
[4]="获得{C:chips}+#4#{}筹码",
},
},
},
["Other"]={
["p_buffoon_jumbo"]={
["name"]="巨型小丑包",
["text"]={
[1]="从最多{C:attention}#2#张{C:joker}小丑牌{}中",
[2]="选择{C:attention}#1#{}张",
},
},
["p_standard_jumbo"]={
["name"]="巨型标准包",
["text"]={
[1]="从最多{C:attention}#2#张{C:attention}游戏牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="到你的牌组",
},
},
["debuffed_default"]={
["name"]="被削弱",
["text"]={
[1]="所有能力",
[2]="禁用",
},
},
["undiscovered_spectral"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中购买或",
[3]="使用此牌",
[4]="以了解其效果",
},
},
["p_celestial_jumbo"]={
["name"]="巨型天体包",
["text"]={
[1]="从最多{C:attention}#2#张{C:planet}星球牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["demo_shop_locked"]={
["name"]="已锁定",
["text"]={
[1]="{C:attention}金宝的",
[2]="个人卡牌收藏。",
[3]="可在完整版",
[4]="{E:1,C:red}Balatro中找到",
},
},
["black_sticker"]={
["name"]="黑标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}黑注",
[3]="难度下获胜",
},
},
["p_spectral_jumbo"]={
["name"]="巨型幻灵包",
["text"]={
[1]="从最多{C:attention}#2#张{C:spectral}幻灵牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["challenge_locked"]={
["name"]="未解锁",
["text"]={
[1]="用至少#1#个不同牌组",
[2]="赢得一场比赛以解锁",
[3]="挑战模式",
[4]="{C:attention,s:2}#2#/#1#",
},
},
["undiscovered_joker"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中购买或",
[3]="使用此牌",
[4]="以了解其效果",
},
},
["purple_seal"]={
["name"]="紫色蜡封",
["text"]={
[1]="被{C:attention}弃掉时",
[2]="产生一张{C:tarot}塔罗牌{}",
[3]="{C:inactive}（必须有空位）",
},
},
["card_chips"]={
["text"]={
[1]="{C:chips}+#1#{}筹码",
},
},
["p_standard_normal"]={
["name"]="标准包",
["text"]={
[1]="从最多{C:attention}#2#张{C:attention}游戏牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="到你的牌组",
},
},
["red_seal"]={
["name"]="红色蜡封",
["text"]={
[1]="重新触发{C:attention}1{}次",
[2]="此卡牌",
},
},
["white_sticker"]={
["name"]="白标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}白注",
[3]="难度下获胜",
},
},
["playing_card"]={
["text"]={
[1]="{V:1}#2#{C:light_black}#1#",
},
},
["card_extra_chips"]={
["text"]={
[1]="获得{C:chips}+#1#{}个额外筹码",
},
},
["deck_locked_stake"]={
["name"]="已锁定",
["text"]={
[1]="在{V:1}#1#{}或以上",
[2]="难度以任一牌组",
[3]="赢得一局",
},
},
["orange_sticker"]={
["name"]="橙标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}橙注",
[3]="难度下获胜",
},
},
["red_sticker"]={
["name"]="红标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}红注",
[3]="难度下获胜",
},
},
["p_standard_mega"]={
["name"]="超大标准包",
["text"]={
[1]="从最多{C:attention}#2#张{C:attention}游戏牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="到你的牌组",
},
},
["locked"]={
["name"]="锁定",
["text"]={
},
},
["debuffed_playing_card"]={
["name"]="被削弱",
["text"]={
[1]="得分无筹码，",
[2]="不能触发任何",
[3]="功能或效果",
},
},
["green_sticker"]={
["name"]="绿标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}绿注",
[3]="难度下获胜",
},
},
["deck_locked_win"]={
["name"]="已锁定",
["text"]={
[1]="在任一难度下",
[2]="以{C:attention}#1#{}",
[3]="赢得一局",
},
},
["undiscovered_tag"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中使用此标签",
[3]="以了解其效果",
},
},
["p_buffoon_normal"]={
["name"]="小丑包",
["text"]={
[1]="从最多{C:attention}#2#张{C:joker}小丑牌{}中",
[2]="选择{C:attention}#1#{}张",
},
},
["undiscovered_tarot"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中购买或",
[3]="使用此牌",
[4]="以了解其效果",
},
},
["remove_negative"]={
["text"]={
},
},
["pinned_left"]={
["name"]="固定",
["text"]={
[1]="这张小丑牌",
[2]="固定在",
[3]="最左侧",
},
},
["gold_seal"]={
["name"]="金色蜡封",
["text"]={
[1]="打出这张牌",
[2]="并得分时",
[3]="获得{C:money}$3{}",
},
},
["demo_locked"]={
["name"]="已锁定",
["text"]={
[1]="本试玩版",
[2]="暂不可用",
},
},
["undiscovered_edition"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中找到此版本",
[3]="以了解其效果",
},
},
["wip_locked"]={
["name"]="已锁定",
["text"]={
[1]="正在",
[2]="制作中",
},
},
["undiscovered_booster"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中打开此包",
[3]="以了解其效果",
},
},
["p_spectral_normal"]={
["name"]="幻灵包",
["text"]={
[1]="从最多{C:attention}#2#张{C:spectral}幻灵牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["deck_locked_discover"]={
["name"]="锁定",
["text"]={
[1]="在收藏中",
[2]="发现至少",
[3]="{C:attention}#1#{}个项目",
},
},
["gold_sticker"]={
["name"]="金色标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}金注",
[3]="难度下获胜",
},
},
["p_celestial_normal"]={
["name"]="天体包",
["text"]={
[1]="从最多{C:attention}#2#张{C:planet}星球牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["blue_seal"]={
["name"]="蓝色蜡封",
["text"]={
[1]="当这张牌在回合结束时",
[2]="还{C:attention}保留{}在手牌中",
[3]="产生一张 {C:planet}星球卡{}",
},
},
["undiscovered_voucher"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中兑换并使用",
[3]="此优惠券",
[4]="以了解其效果",
},
},
["p_arcana_normal"]={
["name"]="秘术包",
["text"]={
[1]="从最多{C:attention}#2#张{C:tarot}塔罗牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["joker_locked_legendary"]={
["name"]="已锁定",
["text"]={
[1]="通过{C:spectral}灵魂{}牌",
[2]="找到这张小丑牌",
},
},
["blue_sticker"]={
["name"]="蓝标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}蓝注",
[3]="难度下获胜",
},
},
["p_arcana_mega"]={
["name"]="超级秘术包",
["text"]={
[1]="从最多{C:attention}#2#张{C:tarot}塔罗牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["p_buffoon_mega"]={
["name"]="超级小丑包",
["text"]={
[1]="从最多{C:attention}#2#张{C:joker}小丑牌{}中",
[2]="选择{C:attention}#1#{}张",
},
},
["eternal"]={
["name"]="永恒卡",
["text"]={
[1]="不能出售",
[2]="或摧毁",
},
},
["purple_sticker"]={
["name"]="紫标贴",
["text"]={
[1]="使用这个小丑牌",
[2]="在{C:attention}紫注",
[3]="难度下获胜",
},
},
["undiscovered_planet"]={
["name"]="未发现",
["text"]={
[1]="在非预设局",
[2]="中购买或",
[3]="使用此牌",
[4]="以了解其效果",
},
},
["p_arcana_jumbo"]={
["name"]="巨型秘术包",
["text"]={
[1]="从最多{C:attention}#2#张{C:tarot}塔罗牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["p_celestial_mega"]={
["name"]="超级天体包",
["text"]={
[1]="从最多{C:attention}#2#张{C:planet}星球牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
["p_spectral_mega"]={
["name"]="超级幻灵包",
["text"]={
[1]="从最多{C:attention}#2#张{C:spectral}幻灵牌{}中",
[2]="选择{C:attention}#1#{}张",
[3]="即选即用",
},
},
},
["Edition"]={
["e_negative"]={
["name"]="负片",
["text"]={
[1]="{C:dark_edition}+#1#{}个小丑牌槽位",
},
},
["e_polychrome"]={
["name"]="多彩",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍率",
},
},
["e_holo"]={
["name"]="镭射",
["text"]={
[1]="{C:mult}+#1#{}倍率",
},
},
["e_negative_consumable"]={
["name"]="负片",
["text"]={
[1]="{C:dark_edition}+#1#{}个消耗牌槽位",
},
},
["e_base"]={
["name"]="基础",
["text"]={
[1]="无额外效果",
},
},
["e_foil"]={
["name"]="闪箔",
["text"]={
[1]="{C:chips}+#1#{}筹码",
},
},
},
["Joker"]={
["j_mime"]={
["name"]="哑剧演员",
["text"]={
[1]="重新触发所有",
[2]="所有手中{C:attention}持有的",
[3]="{C:attention}手牌{}的能力",
},
},
["j_sly"]={
["name"]="奸诈小丑",
["text"]={
[1]="如果出牌中",
[2]="包含一个{C:attention}#2#，",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_ceremonial"]={
["name"]="恐怖匕首",
["text"]={
[1]="当选择 {C:attention}盲注{}时，",
[2]="摧毁右侧的小丑牌，",
[3]="并永久将其售价{C:attention}加倍",
[4]="添加至当前{C:attention}倍率",
[5]="{C:inactive}（当前为 {C:mult}+#1#{C:inactive}倍）",
},
},
["j_supernova"]={
["name"]="超新星",
["text"]={
[1]="将{C:attention}牌型{}的",
[2]="{C:attention}出牌{}次数",
[3]="添加至倍率",
},
},
["j_droll"]={
["name"]="滑稽小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_perkeo"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="佩尔科欧",
["text"]={
[1]="在结束商店后",
[2]="随机复制{C:attention}1{}张",
[3]="拥有的{C:attention}消耗牌{}",
[4]="并给那张牌{C:dark_edition}负片{}效果",
},
},
["j_seance"]={
["name"]="通灵",
["text"]={
[1]="如果{C:attention}牌型{}为",
[2]="{C:attention}#1#{}，随机产生",
[3]="一张{C:spectral}幻灵牌{}",
[4]="{C:inactive}（必须有空位）",
},
},
["j_four_fingers"]={
["name"]="四指",
["text"]={
[1]="所有{C:attention}同花{}和",
[2]="{C:attention}顺子{}都可以",
[3]="由{C:attention}4{}张牌组成。",
},
},
["j_golden"]={
["name"]="黄金小丑",
["text"]={
[1]="在回合结束时",
[2]="获得{C:money}$#1#{}",
},
},
["j_delayed_grat"]={
["name"]="延迟满足",
["text"]={
[1]="如果在回合结束时",
[2]="没有使用弃牌，则每把{C:attention}弃牌{}",
[3]="获得{C:money}$#1#{}",
},
},
["j_castle"]={
["name"]="城堡",
["text"]={
[1]="每次弃掉 {V:1}#2#{}牌，",
[2]="这张小丑牌均可获得{C:chips}+#1#{}筹码",
[3]="每个回合花色都会变",
[4]="{C:inactive}（当前为{C:chips}+#3#{C:inactive}筹码）",
},
},
["j_hit_the_road"]={
["unlock"]={
[1]="同时将{E:1,C:attention}5张",
[2]="{E:1,C:attention}J",
[3]="全部弃掉",
},
["name"]="上路",
["text"]={
[1]="每弃掉一张",
[2]="{C:attention}J{}牌，本回合",
[3]="获得{X:mult,C:white}X#1# {}倍率",
[4]="{C:inactive}（当前为 {X:mult,C:white} X#2#{C:inactive}倍）",
},
},
["j_card_sharp"]={
["name"]="老千小丑",
["text"]={
[1]="若该{C:attention}牌型{}已经",
[2]="在本回合打出过，",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_pareidolia"]={
["name"]="幻视",
["text"]={
[1]="所有卡牌",
[2]="均视为",
[3]="{C:attention}人头牌{}",
},
},
["j_green_joker"]={
["name"]="绿色小丑",
["text"]={
[1]="每次出牌，{C:mult}+#1#{}倍率",
[2]="每次弃牌，{C:mult}-#2#{}倍率",
[3]="{C:inactive}（当前为 {C:mult}+#3#{C:inactive}倍）",
},
},
["j_shortcut"]={
["name"]="捷径",
["text"]={
[1]="让{C:attention}顺子{}可以",
[2]="相隔{C:attention}1个点数",
[3]="{C:inactive}（例如：{C:attention}2 3 5 7 8{C:inactive}）",
},
},
["j_luchador"]={
["name"]="斗士",
["text"]={
[1]="卖掉此卡牌就可以",
[2]="消除当前的",
[3]="{C:attention}Boss盲注{}限制功能",
},
},
["j_devious"]={
["name"]="阴险小丑",
["text"]={
[1]="如果出牌中",
[2]="包含一个{C:attention}#2#，",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_steel_joker"]={
["name"]="钢铁小丑",
["text"]={
[1]="牌组内的",
[2]="每张{C:attention}钢铁牌",
[3]="可使倍率{X:mult,C:white}X#1#",
[4]="{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_rocket"]={
["name"]="火箭",
["text"]={
[1]="每回合结束时获得{C:money}$#1#{}。",
[2]="击败{C:attention}Boss盲注{}",
[3]="获得 {C:money}$#2#{}",
},
},
["j_credit_card"]={
["name"]="信用卡",
["text"]={
[1]="负债限额",
[2]="最多可至{C:red}-$#1#{}",
},
},
["j_hologram"]={
["name"]="全息影像",
["text"]={
[1]="每添加一张{C:attention}卡牌{}",
[2]="到你的牌组中，",
[3]="获得{X:mult,C:white}X#1#{}倍率",
[4]="{C:inactive}（当前为 {X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_ride_the_bus"]={
["name"]="搭乘巴士",
["text"]={
[1]="若连续打出",
[2]="没有{C：attention}人头牌{}的",
[3]="計分手牌，",
[4]="每次{C:mult}+#1#{}倍率",
[5]="{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）",
},
},
["j_hiker"]={
["name"]="徒步者",
["text"]={
[1]="每张打出的",
[2]="{C：attention}計分牌{}可永久",
[3]="增加{C:chips}+#1#{}筹码",
},
},
["j_ramen"]={
["name"]="拉面",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍率",
[2]="每{C:attention}丢弃一张牌{}，",
[3]="失去{X:mult,C:white}X#2#{}倍率",
},
},
["j_square"]={
["name"]="方形小丑",
["text"]={
[1]="若打出的手牌",
[2]="恰好有{C:attention}4{}张牌",
[3]="那么获得",
[4]="{C:chips}+#2#{}筹码",
},
},
["j_baseball"]={
["name"]="棒球卡",
["text"]={
[1]="每张拥有的{C:green}罕见{}小丑牌",
[2]="获得{X:mult,C:white}X#1#{}倍率",
},
},
["j_burglar"]={
["name"]="窃贼",
["text"]={
[1]="选择{C:attention}盲注{}后，",
[2]="出牌次数{C:red}+#1#{}，并",
[3]="{C:attention}失去所有弃牌次数",
},
},
["j_reserved_parking"]={
["name"]="私人车位",
["text"]={
[1]="手牌中持有的",
[2]="每持有一张 {C:attention}人头牌{}",
[3]="有{C:green}#2#/#3#{}的几率",
[4]="给予{C:money}$#1#{}",
},
},
["j_cavendish"]={
["name"]="卡文迪什",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍率",
[2]="回合结束时",
[3]="有{C:green}#2#/#3#{}的几率",
[4]="摧毁此牌",
},
},
["j_erosion"]={
["name"]="腐蚀",
["text"]={
[1]="在你的完整牌组中",
[2]="每张低于 {C:attention}#3#{}张的牌",
[3]="均可获得 {C:red}+#1#{}倍率",
[4]="{C:inactive}（当前为{C:red}+#2#{C:inactive}倍率）",
},
},
["j_trio"]={
["unlock"]={
[1]="赢一局",
[2]="且不打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="三重奏",
["text"]={
[1]="若出牌包含",
[2]="{C:attention}#2#",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_flash"]={
["name"]="闪光卡",
["text"]={
[1]="在商店中每{C:attention}重掷{}一次",
[2]="就可以获得{C:mult}+#1#{}倍率",
[3]="{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）",
},
},
["j_blueprint"]={
["unlock"]={
[1]="赢一局",
},
["name"]="蓝图",
["text"]={
[1]="复制",
[2]="右侧{C:attention}小丑牌{}的能力",
},
},
["j_joker"]={
["name"]="小丑",
["text"]={
[1]="{C:red,s:1.1}+#1#{}倍率",
},
},
["j_red_card"]={
["name"]="红牌",
["text"]={
[1]="当跳过任一{C:attention}补充包{}时",
[2]="{C:red}+#1#{}倍率",
[3]="{C:inactive}（当前为 {C:red}+#2#{C:inactive}倍）",
},
},
["j_onyx_agate"]={
["unlock"]={
[1]="在你的牌组中",
[2]="至少要有{E:1,C:attention}#1#张",
[3]="带有{E:1,C:attention}#2#花色的卡牌",
},
["name"]="缟玛瑙",
["text"]={
[1]="若每打出一张带有",
[2]="{C:clubs}梅花{}花色的牌",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_loyalty_card"]={
["name"]="积分卡",
["text"]={
[1]="每出牌{C:attention}#2#{}次",
[2]="倍率{X:red,C:white}X#1#{}",
[3]="{C:inactive}#3#次",
},
},
["j_trousers"]={
["name"]="备用裤子",
["text"]={
[1]="如果出牌的牌型包含",
[2]="{C:attention}#2#，",
[3]="此牌获得 {C:mult}+#1#{}倍率",
[4]="{C:inactive}（当前为{C:red}+#3#{C:inactive}倍率）",
},
},
["j_baron"]={
["name"]="男爵",
["text"]={
[1]="手牌中，",
[2]="每持有一张{C:attention}K{}，",
[3]="获得{X:mult,C:white}X#1#{}倍率",
},
},
["j_space"]={
["name"]="太空小丑",
["text"]={
[1]="有{C:green}#1#/#2#{}的",
[2]="几率升级",
[3]="打出的{C:attention}牌型等级{}",
},
},
["j_triboulet"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="特里布莱",
["text"]={
[1]="打出的{C:attention}K{}和{C:attention}Q",
[2]="各自获得",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_gift"]={
["name"]="礼品卡",
["text"]={
[1]="在每回合结束时",
[2]="每张拥有的{C:attention}小丑牌{}",
[3]="及{C:attention}消耗牌{}",
[4]="{C:attention}售价{}加{C:money}$#1#{}",
},
},
["j_wily"]={
["name"]="狡猾小丑",
["text"]={
[1]="如果出牌中",
[2]="包含一个{C:attention}#2#，",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_even_steven"]={
["name"]="偶数史蒂文",
["text"]={
[1]="每打出一张计分的",
[2]="{C:attention}偶数{}点的牌，",
[3]="{C:mult}+#1#{}倍率",
[4]="{C:inactive}（10、8、6、4、2）",
},
},
["j_half"]={
["name"]="半张小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}张或更少的牌，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_ancient"]={
["name"]="古老小丑",
["text"]={
[1]="计分时，打出的每张{V:1}#2#{}",
[2]="均可获得",
[3]="{X:mult,C:white}X#1#{}倍率",
[4]="{s:0.8}回合结束时花色会变",
},
},
["j_walkie_talkie"]={
["name"]="对讲机",
["text"]={
[1]="计分时，打出的每张{C:attention}10{}或{C:attention}4",
[2]="均可获得{C:chips}+#1#{}筹码以及",
[3]="{C:mult}+#2#{}倍率",
},
},
["j_merry_andy"]={
["unlock"]={
[1]="在{E:1,C:attention}#1#回合",
[2]="或更少回合内赢得一局",
},
["name"]="快乐安迪",
["text"]={
[1]="{C:red}+#1#{}次弃牌",
[2]="{C:red}#2#{}手牌大小",
},
},
["j_gros_michel"]={
["name"]="格罗斯·米歇尔",
["text"]={
[1]="{C:mult}+#1#{}倍率",
[2]="回合结束时",
[3]="有{C:green}#2#/#3#{}的几率",
[4]="摧毁此牌",
},
},
["j_astronomer"]={
["unlock"]={
[1]="找到所有",
[2]="{E:1,C:planet}星球牌{}",
},
["name"]="天文学家",
["text"]={
[1]="所有{C:planet}星球牌{}",
[2]="和{C:planet}天体包{}",
[3]="在商店内的都{C:attention}免费",
},
},
["j_crafty"]={
["name"]="精明小丑",
["text"]={
[1]="如果出牌中",
[2]="包含一个{C:attention}#2#，",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_mail"]={
["name"]="邮件回扣",
["text"]={
[1]="每弃掉一张{C:attention}#2#{}，",
[2]="即可获得{C:money}$#1#{}，",
[3]="每个回合点数都会变",
},
},
["j_chaos"]={
["name"]="混沌小丑",
["text"]={
[1]="每次商店",
[2]="{C:green}#1#{}次免费重掷",
},
},
["j_troubadour"]={
["unlock"]={
[1]="连续赢得{C:attention,E:1}#1#{}回合，",
[2]="且每回合只使用",
[3]="一次出牌次数",
},
["name"]="游吟诗人",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
[2]="每回合出牌次数{C:red}-#2#{}",
},
},
["j_wrathful_joker"]={
["name"]="愤怒小丑",
["text"]={
[1]="每打出一张",
[2]="{C:spades}#2#{}花色的牌",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_lucky_cat"]={
["name"]="招财猫",
["text"]={
[1]="每次{C:green}成功{}触发",
[2]="一张{C:attention}幸运牌{}",
[3]="即可获得{X:mult,C:white}X#1#{}倍率",
[4]="{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_mr_bones"]={
["unlock"]={
[1]="失去{C:attention,E:1}#1#{}局",
[2]="{C:inactive}(#2#)",
},
["name"]="骷髅先生",
["text"]={
[1]="若计分的筹码",
[2]="至少是",
[3]="所需筹码的{C:attention}25%",
[4]="则不会死亡",
[5]="{S:1.1,C:red,E:2}自毁{}",
},
},
["j_obelisk"]={
["name"]="方尖石塔",
["text"]={
[1]="每次连续不使用",
[2]="你最常用的{C:attention}牌型",
[3]="即可获得",
[4]="{X:mult,C:white}X#1#{}倍率",
[5]="{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_gluttenous_joker"]={
["name"]="暴食小丑",
["text"]={
[1]="每打出一张",
[2]="{C:clubs}#2#{}花色的牌",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_glass"]={
["unlock"]={
[1]="在你的牌组中",
[2]="拥有{E:1,C:attention}#1#个",
[3]="{E:1,C:attention}#2#{}",
},
["name"]="玻璃小丑",
["text"]={
[1]="每摧毁一张",
[2]="{C:attention}玻璃牌",
[3]="获得{C:mult}+#1#{}倍率",
[4]="{C:inactive}（当前为 {X:mult,C:white} X#2#{C:inactive}倍）",
},
},
["j_clever"]={
["name"]="聪敏小丑",
["text"]={
[1]="如果出牌中",
[2]="包含一个{C:attention}#2#，",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_scholar"]={
["name"]="学者",
["text"]={
[1]="计分时",
[2]="每打出一张{C:attention}A{}",
[3]="{C:mult}+#1#{}倍率",
[4]="和{C:chips}+#2#{}筹码",
},
},
["j_blue_joker"]={
["name"]="蓝色小丑",
["text"]={
[1]="每张{C:attention}牌组{}内剩余",
[2]="的卡牌，{C:chips}+#1#{}筹码",
[3]="{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）",
},
},
["j_arrowhead"]={
["unlock"]={
[1]="在你的牌组中",
[2]="至少要有{E:1,C:attention}#1#张",
[3]="带有{E:1,C:attention}#2#花色的卡牌",
},
["name"]="箭头",
["text"]={
[1]="若每打出一张带有",
[2]="{C:spades}黑桃{}花色的卡牌",
[3]="计分时{C:mult}+#1#{}筹码",
},
},
["j_throwback"]={
["unlock"]={
[1]="从主菜单中选择继续",
[2]="游玩已保存的局",
},
["name"]="回溯",
["text"]={
[1]="本赛局内每跳过一次",
[2]="{C:attention}盲注{}，获得{X:mult,C:white}X#1#{}倍率",
[3]="{C:inactive}（当前为 {X:mult,C:white}X#2#{C:inactive}倍）",
},
},
["j_invisible"]={
["unlock"]={
[1]="赢一局，",
[2]="且从未拥有超过",
[3]="{E:1,C:attention}4张小丑牌{}",
},
["name"]="隐形小丑",
["text"]={
[1]="{C:attention}#1#{}个回合后，",
[2]="卖掉此卡牌就可以",
[3]="随机{C:attention}复制{}一张小丑牌",
[4]="{C:inactive}(当前为{C:attention}#2#{C:inactive}/#1#)",
},
},
["j_cloud_9"]={
["name"]="9霄云外",
["text"]={
[1]="每张牌组内的数字{C:attention}9{}",
[2]="在每回合结束时",
[3]="获得{C:money}$#1#{}",
[4]="{C:inactive}(当前{C:money}$#2#{}{C:inactive})",
},
},
["j_greedy_joker"]={
["name"]="贪婪小丑",
["text"]={
[1]="每打出一张",
[2]="{C:diamonds}#2#{}花色的牌，",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_runner"]={
["name"]="跑步选手",
["text"]={
[1]="每次打出一手",
[2]="{C:attention}顺子{}",
[3]="{C:chips}+#2#{}筹码",
[4]="{C:inactive}（当前 {C:chips}+#1#{C:inactive}筹码）",
},
},
["j_egg"]={
["name"]="鸡蛋",
["text"]={
[1]="在回合结束时",
[2]="本卡的{C：attention}出售价值",
[3]="增加{C：money}$#1#",
},
},
["j_duo"]={
["unlock"]={
[1]="赢一局",
[2]="且不打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="二重奏",
["text"]={
[1]="若出牌包含",
[2]="{C:attention}#2#",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_flower_pot"]={
["unlock"]={
[1]="达到底注",
[2]="等级{E:1,C:attention}#1#",
},
["name"]="花盆",
["text"]={
[1]="{X:mult,C:white} X#1# {}倍率，若",
[2]="出牌中，计分的牌",
[3]="含有{C:diamonds}方片{}、{C:clubs}梅花{}",
[4]="{C:hearts}红桃{}和{C:spades}黑桃{}",
},
},
["j_mystic_summit"]={
["name"]="神秘之峰",
["text"]={
[1]="当剩余{C:attention}#2#{}次",
[2]="弃牌次数，",
[3]="{C:mult}+#1#{}倍率",
},
},
["j_midas_mask"]={
["name"]="迈达斯面具",
["text"]={
[1]="所有的{C:attention}人头牌{}",
[2]="在打出的时候",
[3]="都会变成{C:attention}黄金牌{}",
},
},
["j_smiley"]={
["name"]="微笑表情",
["text"]={
[1]="打出的{C:attention}人头牌{}",
[2]="计分时",
[3]="均可获得{C:mult}+#1#{}倍率",
},
},
["j_drunkard"]={
["name"]="醉汉",
["text"]={
[1]="{C:red}+#1#{}次弃牌数",
},
},
["j_diet_cola"]={
["name"]="零糖可乐",
["text"]={
[1]="卖掉此卡牌就可以",
[2]="创建一张免费的",
[3]="{C:attention}#1#",
},
},
["j_shoot_the_moon"]={
["unlock"]={
[1]="在单个回合中",
[2]="打出牌组里的",
[3]="{E:1,C:attention}红桃",
},
["name"]="射月",
["text"]={
[1]="若每持有一张{C:attention}Q",
[2]="在手牌中",
[3]="{C:mult}+#1#{}倍率",
},
},
["j_splash"]={
["name"]="飞溅",
["text"]={
[1]="每张{C:attention}打出的牌",
[2]="都计入得分",
},
},
["j_sock_and_buskin"]={
["unlock"]={
[1]="打出总共",
[2]="{C:attention,E:1}#1#{}张人头牌",
[3]="{C:inactive}(#2#)",
},
["name"]="喜与悲",
["text"]={
[1]="重新触发所有",
[2]="打出的{C:attention}人头牌{}",
},
},
["j_rough_gem"]={
["unlock"]={
[1]="在你的牌组中",
[2]="至少要有{E:1,C:attention}#1#张",
[3]="带有{E:1,C:attention}#2#花色的卡牌",
},
["name"]="璞玉",
["text"]={
[1]="计分时{C:mult}+#1#{}",
[2]="若每打出一张带有",
[3]="{C:diamonds}方片{}花色的卡牌",
},
},
["j_banner"]={
["name"]="旗帜",
["text"]={
[1]="每一个剩余的",
[2]="{C:attention}弃牌{}次数",
[3]="{C:chips}+#1#{}筹码",
},
},
["j_8_ball"]={
["name"]="八号球",
["text"]={
[1]="打出{C:attenetion}#1#{}张",
[2]="或更多张数字{C:attention}8{}，",
[3]="则获得一张{C:planet}星球牌{}",
[4]="{C:inactive}（必须有空位）",
},
},
["j_hallucination"]={
["name"]="幻觉",
["text"]={
[1]="打开任一{C:attention}补充包{}时，",
[2]="有{C:green}#1#/#2#{}的机会能够",
[3]="创建一张{C:attention}塔罗牌{}",
[4]="{C:inactive}（必须有空位）",
},
},
["j_trading"]={
["name"]="交易卡",
["text"]={
[1]="如果回合的{C:attention}第一次弃牌{}",
[2]="只有 {C:attention}1{}张牌，则将其",
[3]="摧毁并获得 {C:money}$#1#",
},
},
["j_mad"]={
["name"]="疯狂小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_abstract"]={
["name"]="抽象小丑",
["text"]={
[1]="每张{C:attention}小丑牌{}",
[2]="{C:mult}+#1#{}倍率",
[3]="{C:inactive}（当前为{C:red}+#2#{C:inactive}倍率）",
},
},
["j_odd_todd"]={
["name"]="奇数托德",
["text"]={
[1]="每打出一张计分的",
[2]="{C:attention}奇数{}点的牌，",
[3]="获得 {C:chips}+#1#{}筹码",
[4]="{C:inactive}（A、9、7、5、3）",
},
},
["j_riff_raff"]={
["name"]="乌合之众",
["text"]={
[1]="当选择{C:attention}盲注{}时，",
[2]="产生{C:attention}#1#张{C:blue}常规{C:attention}小丑牌",
[3]="{C:inactive}（必须有空间）",
},
},
["j_superposition"]={
["name"]="叠加",
["text"]={
[1]="如果出牌中计分的牌包含",
[2]="一张{C:attention}A{}和一个{C:attention}顺子{}",
[3]="产生一张{C:tarot}塔罗牌{}",
[4]="{C:inactive}（必须有空位）",
},
},
["j_to_the_moon"]={
["name"]="冲向月球",
["text"]={
[1]="回合结束时，",
[2]="每拥有{C:money}$5{}，",
[3]="都可额外获得{C:money}$#1#{}的{C:attention}利息{}",
},
},
["j_stuntman"]={
["unlock"]={
[1]="在一次出牌中",
[2]="获得至少",
[3]="{E:1,C:attention}#1#{}筹码",
},
["name"]="特技演员",
["text"]={
[1]="{C:chips}+#1#{}筹码",
[2]="{C:attention}-#2#{}手牌大小",
},
},
["j_satellite"]={
["unlock"]={
[1]="有{E:1,C:money}$#1#",
[2]="或更多",
},
["name"]="卫星",
["text"]={
[1]="本赛局每使用一张",
[2]="{C:planet}星球牌{}，每回合结束时",
[3]="可得到{C:money}$#1#{}",
[4]="{C:inactive}（当前{C:money}$#2#{C:inactive}）",
},
},
["j_todo_list"]={
["name"]="待办清单",
["text"]={
[1]="如果{C:attention}出牌牌型{}為{C:attention}#2#{}，",
[2]="獲得{C:money}$#1#{}",
[3]="每次支付时",
[4]="牌型都会改变",
},
},
["j_constellation"]={
["name"]="星座",
["text"]={
[1]="每使用一张{C:planet}星球牌{}",
[2]="倍率{X:mult,C:white}X#1#{}",
[3]="{C:inactive}（当前为倍率{X:mult,C:white}X#2#{C:inactive}）",
},
},
["j_selzer"]={
["name"]="苏打水",
["text"]={
[1]="在接下来的{C:attention}#1#{}次出牌中",
[2]="重新触发所有",
[3]="打出的卡牌",
},
},
["j_stone"]={
["name"]="石头小丑",
["text"]={
[1]="为牌组内的",
[2]="每张{C:attention}石头牌",
[3]="{C:chips}+#1#{}筹码",
[4]="{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）",
},
},
["j_raised_fist"]={
["name"]="致胜之拳",
["text"]={
[1]="将手中持有的 {C:attention}最小{}牌的",
[2]="点数 {C:attention}翻倍{}，",
[3]="并应用到倍率上",
},
},
["j_marble"]={
["name"]="大理石小丑",
["text"]={
[1]="选择{C:attention}盲注{}后",
[2]="牌组中会添加",
[3]="一张{C:attention}石头{}牌",
},
},
["j_bull"]={
["name"]="斗牛",
["text"]={
[1]="每拥有{C:money}$1{}",
[2]="均可获得 {C:chips}+#1#{}筹码",
[3]="{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）",
},
},
["j_dna"]={
["name"]="DNA",
["text"]={
[1]="如果回合的{C:attention}第一次出牌{}",
[2]="只有 {C:attention}1{}张牌，则将其",
[3]="永久复制到牌组",
[4]="并放到{C:attention}手牌中",
},
},
["j_zany"]={
["name"]="古怪小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_acrobat"]={
["unlock"]={
[1]="打出{C:attention,E:1}#1#{}张牌",
[2]="{C:inactive}(#2#)",
},
["name"]="杂技演员",
["text"]={
[1]="回合的最后一次",
[2]="{C:attention}出牌{}中，倍率{X:red,C:white}X#1#",
},
},
["j_photograph"]={
["name"]="照片",
["text"]={
[1]="计分时第一张打出的",
[2]="{C:attention}人头牌{}",
[3]="获得 {X:mult,C:white}X#1#{}倍率",
},
},
["j_order"]={
["unlock"]={
[1]="赢一局",
[2]="且不打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="秩序",
["text"]={
[1]="若出牌包含",
[2]="{C:attention}#2#",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_burnt"]={
["unlock"]={
[1]="售出所有",
[2]="{E:1,C:attention}+#1#{}张卡牌",
[3]="{C:inactive}(#2#)",
},
["name"]="烧焦小丑",
["text"]={
[1]="升级每回合",
[2]="首次{C:attention}被弃掉的",
[3]="扑克手牌的等级",
},
},
["j_hack"]={
["name"]="烂脱口秀演员",
["text"]={
[1]="重新触发",
[2]="所有打出的",
[3]="{C:attention}2{}、{C:attention}3{}、{C:attention}4{}和 {C:attention}5{}",
},
},
["j_swashbuckler"]={
["unlock"]={
[1]="总共卖出",
[2]="{C:attention,E:1}#1#{}张小丑牌",
[3]="{C:inactive}(#2#)张",
},
["name"]="侠盗",
["text"]={
[1]="将此卡左侧所有",
[2]="{C:attention}小丑牌{}的总售价",
[3]="添加至倍率",
[4]="{C:inactive}（当前为{C:mult}+#1#{C:inactive}倍率）",
},
},
["j_scary_face"]={
["name"]="恐怖面孔",
["text"]={
[1]="打出{C:attention}人头牌{}时，",
[2]="计分时",
[3]="获得{C:chips}{C:chips}+#1#{}",
},
},
["j_popcorn"]={
["name"]="爆米花",
["text"]={
[1]="{C:mult}+#1#{}倍率",
[2]="每进行一个回合",
[3]="{C:mult}-#2#{}倍率",
},
},
["j_caino"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="卡伊诺",
["text"]={
[1]="每有一张被摧毁的",
[2]="{C:attention}人头牌{}时",
[3]="获得{X:mult,C:white}X#1#{}倍率",
[4]="{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）",
},
},
["j_hanging_chad"]={
["unlock"]={
[1]="用{E:1,C:attention}#1#",
[2]="打赢Boss盲注",
},
["name"]="悬垂查德",
["text"]={
[1]="重新触发得分中",
[2]="使用的{C:attention}第一张{}牌",
},
},
["j_crazy"]={
["name"]="狂野小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_vampire"]={
["name"]="吸血鬼",
["text"]={
[1]="每打出一张{C:attention}增强卡牌{}",
[2]="即可获得{X:mult,C:white}X#1#{}倍率，",
[3]="並移除卡牌{C:attention}增强效果",
[4]="{C:inactive}（当前为 {X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_tribe"]={
["unlock"]={
[1]="赢一局",
[2]="且不打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="部落",
["text"]={
[1]="若出牌包含",
[2]="{C:attention}#2#",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_smeared"]={
["unlock"]={
[1]="在你的牌组中",
[2]="至少拥有{C:attention}#1#",
[3]="{E:1,C:attention}#2#{}",
},
["name"]="模糊小丑",
["text"]={
[1]="{C:diamonds}红桃{}和{C:diamonds}方片",
[2]="视作同一花色，",
[3]="{C:spades}黑桃{}和{C:spades}梅花",
[4]="也视作同一花色",
},
},
["j_jolly"]={
["name"]="开心小丑",
["text"]={
[1]="如果出牌包含",
[2]="{C:attention}#2#{}，",
[3]="{C:red}+#1#{}倍率",
},
},
["j_brainstorm"]={
["unlock"]={
[1]="弃掉一张",
[2]="{E:1,C:attention}皇家同花顺",
},
["name"]="头脑风暴",
["text"]={
[1]="复制最左边的",
[2]="{C:attention}小丑牌的技能",
},
},
["j_bloodstone"]={
["unlock"]={
[1]="在你的牌组中",
[2]="至少要有{E:1,C:attention}#1#张",
[3]="带有{E:1,C:attention}#2#花色的卡牌",
},
["name"]="血石",
["text"]={
[1]="若每打出一张带有",
[2]="{C:hearts}红桃{}花色的卡牌",
[3]="有{C：green}#1#/#2#{}的机率",
[4]="获得{X:mult,C:white}X#3#{}倍率",
},
},
["j_ticket"]={
["unlock"]={
[1]="当打出一手五张",
[2]="只包含",
[3]="{C:attention,E:1}黃金牌{}的牌",
},
["name"]="黄金门票",
["text"]={
[1]="打出{C:attention}黃金牌{}，",
[2]="计分时，{C:money}$#1#{}",
},
},
["j_seeing_double"]={
["unlock"]={
[1]="当打一手",
[2]="包含",
[3]="{E:1,C:attention}#1#的牌",
},
["name"]="双重视角",
["text"]={
[1]="出牌中，计分的牌若",
[2]="含有{C:clubs}梅花{}和",
[3]="任何其他{C:attention}花色{}，",
[4]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_ring_master"]={
["unlock"]={
[1]="达到底注",
[2]="等级{E:1,C:attention}#1#",
},
["name"]="马戏团长",
["text"]={
[1]="{C:attention}小丑牌{}、{C:tarot}塔罗牌{}、{C:planet}星球牌{}",
[2]="和{C:planet}幻灵牌{}会出现",
[3]="多次",
},
},
["j_stencil"]={
["name"]="模具小丑",
["text"]={
[1]="每个空的{C:attention}小丑牌{}槽位",
[2]="获得{X:red,C:white} X1{}倍率。",
[3]="{s:0.8}包括模具小丑",
[4]="（当前为{X:red,C:white} X#1# {C:inactive}）",
},
},
["j_oops"]={
["unlock"]={
[1]="在一次出牌中",
[2]="获得至少",
[3]="{E:1,C:attention}#1#{}筹码",
},
["name"]="六六大顺",
["text"]={
[1]="全部加倍{C:attention}列出的",
[2]="{C:green,E:1,S:1.1}几率",
[3]="{C:inactive}（例如：{C:green}3中1{C:inactive} -> {C:green}3中2{C:inactive}）",
},
},
["j_madness"]={
["name"]="疯狂",
["text"]={
[1]="当选择 {C:attention}盲注{}时，",
[2]="{X:mult,C:white}X#1#{}倍率并且",
[3]="随机{C:attention}消灭{}一个小丑",
[4]="{C:inactive}（当前为{X:mult,C:white}X#2#{}倍）",
},
},
["j_family"]={
["unlock"]={
[1]="赢一局",
[2]="且不打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="一家人",
["text"]={
[1]="若出牌包含",
[2]="{C:attention}#2#",
[3]="{X:mult,C:white}X#1#{}倍率",
},
},
["j_bootstraps"]={
["unlock"]={
[1]="在你的牌组中",
[2]="{C:dark_edition}多彩{}小丑",
},
["name"]="提靴带",
["text"]={
[1]="每拥有{C:money}$#2#{}，",
[2]="{C:mult}+#1#{}倍率",
},
},
["j_juggler"]={
["name"]="杂耍师",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
},
},
["j_dusk"]={
["name"]="黄昏卡",
["text"]={
[1]="每回合",
[2]="{C:attention}最后一次出牌{}",
[3]="该手牌会被触发两次",
},
},
["j_vagabond"]={
["name"]="流浪者",
["text"]={
[1]="若在出牌时当下",
[2]="拥有{C:money}$#1#{}或更少的金钱",
[3]="获得一张{C:purple}塔罗牌{}",
},
},
["j_wee"]={
["unlock"]={
[1]="在{E:1,C:attention}#1#回合",
[2]="或更少回合内赢得一局",
},
["name"]="小小丑",
["text"]={
[1]="每打出一张{C:attention}2{}并得分时",
[2]="此小丑牌获得",
[3]="获得{C:chips}+#2#{}筹码",
[4]="{C:inactive}（当前为{C:chips}+#1#{C:inactive}筹码）",
},
},
["j_matador"]={
["unlock"]={
[1]="打赢Boss盲注",
[2]="在{E:1,C:attention}一手之内{}且没有",
[3]="使用任何弃牌",
},
["name"]="斗牛士",
["text"]={
[1]="若出牌触发了",
[2]="{C:attention}Boss盲注{}的限制条件，",
[3]="获得{C:money}$#1#{}",
},
},
["j_campfire"]={
["name"]="篝火",
["text"]={
[1]="每次{C:attention}卖掉{}一张牌",
[2]="这张小丑牌就增加{X:mult,C:white}X#1#{}倍率，",
[3]="当{C:attention}Boss盲注{}被击败时即重置倍率",
[4]="{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）",
},
},
["j_idol"]={
["unlock"]={
[1]="在一次出牌中",
[2]="获得至少",
[3]="{E:1,C:attention}#1#{}筹码",
},
["name"]="偶像",
["text"]={
[1]="计分时在{V:1}#3#{}中",
[2]="每打出的{C:attention}#2#",
[3]="{X:mult,C:white} X#1#{}倍率",
[4]="{s:0.8}每回合卡牌都会变动",
},
},
["j_lusty_joker"]={
["name"]="色欲小丑",
["text"]={
[1]="每打出一张",
[2]="{C:hearts}#2#{}花色的牌",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_sixth_sense"]={
["name"]="第六感",
["text"]={
[1]="若此回合第一次出牌",
[2]="为一张单独的{C:attention}6{}",
[3]="就将其销毁并创建一张{C:spectral}幻灵牌{}",
[4]="{C:inactive}（必须有空位）",
},
},
["j_certificate"]={
["unlock"]={
[1]="拥有一张",
[2]="带{C:attention,E:1}金色蜡封{}的",
[3]="黄金牌",
},
["name"]="证书",
["text"]={
[1]="回合开始时",
[2]="随机添加一张",
[3]="带随机{C:attention}蜡封{}的{C:attention}牌",
[4]="到手牌中",
},
},
["j_ice_cream"]={
["name"]="冰淇淋",
["text"]={
[1]="{C:chips}+#1#{}筹码",
[2]="每次出牌",
[3]="{C:chips}-#2#{}筹码",
},
},
["j_misprint"]={
["name"]="印错小丑",
["text"]={
[1]="",
},
},
["j_turtle_bean"]={
["name"]="海龟豆",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
[2]="每回合",
[3]="减少{C:red}#2#{}张",
},
},
["j_blackboard"]={
["name"]="黑板",
["text"]={
[1]="倍率{X:red,C:white}X#1# {}，若手牌中",
[2]="未出手的牌",
[3]="都是{C:spades}#2#{}或{C:clubs}#3#{}",
},
},
["j_fortune_teller"]={
["name"]="占卜师",
["text"]={
[1]="本赛局每使用一张{C:purple}塔罗牌{}",
[2]="{C:red}+#1#{}倍率",
[3]="{C:inactive}（当前为{C:red}+#2#{C:inactive}）",
},
},
["j_drivers_license"]={
["unlock"]={
[1]="增强牌组里",
[2]="{E:1,C:attention}#1#{}张卡牌",
},
["name"]="驾驶执照",
["text"]={
[1]="{X:mult,C:white} X#1# {}倍率，如果牌组",
[2]="至少有{C:attention}16张",
[3]="增强卡牌",
[4]="{C:inactive}（当前{C:attention}#2#{C:inactive}）",
},
},
["j_chicot"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="奇科特",
["text"]={
[1]="每个{C:attention}Boss盲注",
[2]="限制条件消失",
},
},
["j_yorick"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="约里克",
["text"]={
[1]="使用{C:attention}#2#{}次弃牌后",
[2]="获得{X:mult,C:white}X#1#{}倍数",
[3]="{C:inactive}（弃牌剩余：{C:attention}#3#{C:inactive}）",
},
},
["j_business"]={
["name"]="名片",
["text"]={
[1]="计分时，打出的{C:attention}人头牌{}",
[2]="有{C:green}#1#/#2#{}的几率",
[3]="获得{C:money}$2{}",
},
},
["j_cartomancer"]={
["unlock"]={
[1]="发现每张",
[2]="{E:1,C:tarot}塔罗牌{}",
},
["name"]="卡牌术士",
["text"]={
[1]="当选择{C:attention}盲注{}时",
[2]="产生一张{C:tarot}塔罗牌{}",
[3]="{C:inactive}（必须有空位）",
},
},
["j_fibonacci"]={
["name"]="斐波那契",
["text"]={
[1]="每打出一张",
[2]="{C:attention}A{}、{C:attention}2{}、{C:attention}3{}、{C:attention}5{}或{C:attention}8{}时",
[3]="计分时{C:mult}+#1#{}倍率",
},
},
["j_faceless"]={
["name"]="无面小丑",
["text"]={
[1]="如果同时弃掉",
[2]="{C:attention}#2#{}张或更多张",
[3]="{C:attention}人头牌{}，",
[4]="获得{C:money}$#1#{}",
},
},
},
["Spectral"]={
["c_soul"]={
["name"]="灵魂",
["text"]={
[1]="创建一张",
[2]="{C:legendary,E:1}传奇{}小丑牌",
[3]="{C:inactive}（必须有空位）",
},
},
["c_cryptid"]={
["name"]="神秘生物",
["text"]={
[1]="复制{C:attention}#1#{}张",
[2]="建立{C:attention}#1#{}张",
[3]="选定牌的复制牌",
},
},
["c_trance"]={
["name"]="入迷",
["text"]={
[1]="给你手牌中的",
[2]="{C:attention}1{}张所选卡牌",
[3]="加上{C:blue}蓝色蜡封{}",
},
},
["c_medium"]={
["name"]="灵媒",
["text"]={
[1]="给你手牌中的",
[2]="{C:attention}1{}张所选卡牌",
[3]="加上{C:purple}紫色蜡封{}",
},
},
["c_deja_vu"]={
["name"]="既视感",
["text"]={
[1]="给你手牌中的",
[2]="{C:attention}1{}张所选卡牌",
[3]="加上{C:red}红色蜡封+D1670{}",
},
},
["c_ectoplasm"]={
["name"]="灵质",
["text"]={
[1]="添加{C:dark_edition}负片{}效果到",
[2]="一张随机的{C:attention}小丑牌，",
[3]="{C:red}-1{}的手牌大小",
},
},
["c_familiar"]={
["name"]="熟知",
["text"]={
[1]="随机摧毁{C:attention}1{}张手牌，",
[2]="并添加{C:attention}#1#{}张",
[3]="随机{C:attention}增强版人头牌{}",
[4]="到手牌中",
},
},
["c_immolate"]={
["name"]="火祭",
["text"]={
[1]="随机摧毁{C:attention}#1#{}张",
[2]="手牌，",
[3]="获得{C:money}$#2#",
},
},
["c_grim"]={
["name"]="严峻",
["text"]={
[1]="随机摧毁{C:attention}1{}张手牌，",
[2]="并添加{C:attention}#1#{}张",
[3]="随机{C:attention}增强版A{}",
[4]="到手牌中",
},
},
["c_aura"]={
["name"]="光环",
["text"]={
[1]="将{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}，",
[2]="或{C:dark_edition}多彩卡{}效果添加至",
[3]="{C:attention}1{}张选定的手牌中",
},
},
["c_ouija"]={
["name"]="占卜",
["text"]={
[1]="将手中所有",
[2]="手持牌转换至一种",
[3]="随机{C:attention}点数",
[4]="{C:red}-1{}手牌大小",
},
},
["c_talisman"]={
["name"]="护身符",
["text"]={
[1]="将{C:attention}金色蜡封{}添加到",
[2]="{C:attention}1{}张选定的",
[3]="手牌中",
},
},
["c_wraith"]={
["name"]="幽灵",
["text"]={
[1]="产生一张随机的",
[2]="{C:red}稀有{C:attention}小丑牌{}，",
[3]="设定金额至{C:money}$0",
},
},
["c_ankh"]={
["name"]="生命十字章",
["text"]={
[1]="随机复制一张",
[2]="{C:attention}小丑牌{}，摧毁",
[3]="其他小丑牌",
},
},
["c_sigil"]={
["name"]="符印",
["text"]={
[1]="将手中所有",
[2]="卡牌转换至一种",
[3]="随机{C:attention}花色",
},
},
["c_hex"]={
["name"]="妖法",
["text"]={
[1]="随机为一张{C:attention}小丑牌{}添加",
[2]="{C:attention}多彩{}，摧毁",
[3]="其他小丑牌",
},
},
["c_incantation"]={
["name"]="咒语",
["text"]={
[1]="随机摧毁{C:attention}1{}张手牌，",
[2]="并添加{C:attention}#1#{}张",
[3]="随机{C:attention}增强版数字牌{}",
[4]="到手牌中",
},
},
["c_black_hole"]={
["name"]="黑洞",
["text"]={
[1]="为每副",
[2]="{C:legendary,E:1}牌型",
[3]="提升{C:attention}1{}级",
},
},
},
},
["UI"]={
},
["misc"]={
["suits_singular"]={
["Spades"]="黑桃",
["Hearts"]="红桃",
["Diamonds"]="方片",
["Clubs"]="梅花",
},
["v_text"]={
["ch_c_inflation"]={
[1]="每次购买后价格永久上涨 {C:money}$1{}",
},
["ch_m_hand_size"]={
[1]="{C:attention}#1#{}手牌大小",
},
["ch_c_discard_cost"]={
[1]="每次弃牌需花费 {C:money}$#1#{}",
},
["ch_c_none"]={
[1]="{C:inactive}无",
},
["ch_m_reroll_cost"]={
[1]="{C:money}$#1#{}基本重掷费用",
},
["ch_c_no_reward"]={
[1]="所有{C:attention}盲注{}均无奖励金",
},
["ch_c_no_reward_specific"]={
[1]="{C:attention}#1# 盲注{}均无奖励金",
},
["ch_m_none"]={
[1]="{C:inactive}无",
},
["ch_c_set_seed"]={
[1]="使用设定的种子尝试1次：{C:inactive}{Hidden}",
},
["ch_c_no_interest"]={
[1]="回合结束时不赚取{C:attention}利息{}",
},
["ch_c_chips_dollar_cap"]={
[1]="{C:blue}筹码{}不能超过当前{C:money}$",
},
["ch_m_dollars"]={
[1]="从{C:money}$#1#开始",
},
["ch_c_flipped_cards"]={
[1]="{C:green}#1#中的1张{}卡牌以背面朝上的方式抽取",
},
["ch_c_minus_hand_size_per_X_dollar"]={
[1]="你每拥有{C:money}$#1#{}，可持有的卡牌 {C:red}-1{}",
},
["ch_m_discards"]={
[1]="每回合{C:red}#1#{}次弃牌",
},
["ch_c_no_shop_jokers"]={
[1]="小丑牌不再出现在{C:attention}商店{}中",
},
["ch_c_daily"]={
[1]="{E:1,s:1.2,C:red}每日挑战！",
},
["ch_m_hands"]={
[1]="每回合{C:blue}#1#{}次出牌",
},
["ch_m_consumable_slots"]={
[1]="{C:attention}#1#{}消耗牌槽位",
},
["ch_c_set_joker_slots_ante"]={
[1]="当{C:attention}#1#{}Boss盲注被击败时，将小丑牌槽位设置为{C:attention}0",
},
["ch_c_set_eternal_ante"]={
[1]="当{C:attention}#1#{}Boss盲注被击败时，所有小丑牌变为{C:attention}永恒卡",
},
["ch_c_no_extra_hand_money"]={
[1]="额外的{C:blue}牌不再赚取资金",
},
["ch_c_debuff_played_cards"]={
[1]="所有{C:attention}已打出{}的牌在计分后都会{C:attention}被削弱",
},
["ch_m_joker_slots"]={
[1]="{C:attention}#1#{}小丑牌槽位",
},
["ch_c_all_eternal"]={
[1]="所有商店里的小丑牌都是{C:eternal}永恒卡{}",
},
},
["quips"]={
["wq_4"]={
[1]="这些筹码",
[2]="都是虚拟的",
[3]="真是太可惜了……",
},
["lq_10"]={
[1]="真是太惨了！",
},
["lq_6"]={
[1]="哦不，你刚刚是",
[2]="真的在吹牛？",
},
["lq_7"]={
[1]="看来我们才是",
[2]="那个出洋相的！",
},
["wq_3"]={
[1]="看起来你",
[2]="是有真本事的！",
},
["wq_1"]={
[1]="你太棒了！",
},
["lq_5"]={
[1]="看来我们",
[2]="找到了谁才是",
[3]="真正的小丑！",
},
["wq_2"]={
[1]="你表现得",
[2]="相当不错！",
},
["lq_9"]={
[1]="我真是个",
[2]="傻瓜，你的借口",
[3]="又是什么？",
},
["dq_1"]={
[1]="哎哟！我希望你",
[2]="肚子里还有",
[3]="别的招式来",
[4]="应对这场最终挑战！",
},
["lq_4"]={
[1]="你也知道",
[2]="老话怎么说的，",
[3]="你可能小赚，但庄家永远不亏！",
},
["lq_8"]={
[1]="如果我有手的话",
[2]="我肯定会",
[3]="捂上双眼！",
},
["lq_1"]={
[1]="可能消消乐",
[2]="才更适合",
[3]="我们的节奏……",
},
["wq_7"]={
[1]="幸好",
[2]="我没有",
[3]="和你打赌",
},
["lq_2"]={
[1]="我们的牌打的",
[2]="相当潦草！",
},
["lq_3"]={
[1]="我们是时候",
[2]="撤出",
[3]="重来了！",
},
["wq_5"]={
[1]="看来我把你",
[2]="教的不错啊！",
},
["wq_6"]={
[1]="你有几局",
[2]="非常精彩啊！",
},
},
["achievement_descriptions"]={
["speedrunner"]="在12回合内赢得一局",
["card_player"]="打出至少2500张牌",
["extreme_couponer"]="发现所有优惠券",
["heads_up"]="赢一局",
["retrograde"]="让任一牌型升至第10级",
["shattered"]="单次出牌打碎2张玻璃牌",
["completionist_plus_plus"]="每张小丑牌都获得一个金色标贴",
["nest_egg"]="单局中拥有 $400 或以上",
["roi"]="在底注4阶段时购买5张优惠券",
["royale"]="打出一次皇家同花顺",
["tiny_hands"]="将你的牌组减少到20张或更少",
["_100000k"]="单次出牌获得1亿筹码",
["cartomancy"]="发现所有塔罗牌",
["rule_breaker"]="完成每一场挑战局",
["flushed"]="用5张万能牌打出一次同花",
["mid_stakes"]="在至少黑注难度下赢一局",
["completionist"]="发现100%的收藏道具",
["low_stakes"]="在至少红注难度下赢一局",
["_1000k"]="单次出牌获得100万筹码",
["ante_upper"]="达到底注8阶段",
["astronomy"]="发现所有星球牌",
["big_hands"]="牌组中拥有80张或以上的卡牌",
["card_discarder"]="弃掉至少2500张牌",
["completionist_plus"]="赢得胜利且每个牌组都在金注难度",
["legendary"]="发现一张传奇小丑牌",
["rule_bender"]="完成任一挑战局",
["_10k"]="单次出牌获得1万筹码",
["high_stakes"]="在至少金注难度下赢一局",
["clairvoyance"]="发现所有幻灵牌",
["ante_up"]="达到底注4阶段",
["you_get_what_you_get"]="赢下一局且没有在商店中重掷",
},
["poker_hands"]={
["Flush House"]="同花葫芦",
["Full House"]="葫芦",
["Flush"]="同花",
["Pair"]="对子",
["Four of a Kind"]="四条",
["Royal Flush"]="皇家同花顺",
["Straight Flush"]="同花顺",
["Straight"]="顺子",
["Five of a Kind"]="五条",
["Flush Five"]="同花五条",
["Two Pair"]="两对",
["Three of a Kind"]="三条",
["High Card"]="高牌",
},
["blind_states"]={
["Defeated"]="已被击败",
["Upcoming"]="下一回合",
["Current"]="当前",
["Selected"]="已选择",
["Select"]="选择",
["Skipped"]="跳过",
},
["dictionary"]={
["b_credits"]="制作人员",
["b_set_rumble"]="控制器震动",
["b_play_cap"]="开始游戏",
["ph_no_boss_active"]="无活跃boss",
["k_skipped_cap"]="跳过",
["b_high_contrast_cards"]="高对比度卡牌",
["b_set_play_discard_pos"]="出牌/弃牌按钮位置",
["k_playing_as"]="使用",
["k_unlocked_ex"]="已解锁！",
["k_reroll"]="重掷",
["b_music"]="音乐",
["ml_play_discard_pos_opt"]={
[1]="弃牌/出牌",
[2]="出牌/弃牌",
},
["b_set_video"]="视频",
["b_restrictions"]="限制条件",
["b_jokers"]="小丑",
["k_copied_ex"]="已复制！",
["b_set_graphics"]="图形",
["ph_blind_score_at_least"]="至少得分",
["b_copy"]="复制",
["k_collection"]="收藏",
["k_choose"]="选择",
["b_rules"]="规则",
["k_lower_score"]="分数",
["b_stat_jokers"]="小丑",
["k_x_base"]="X 基础",
["b_run_info_1"]="比赛",
["k_rare"]="稀有",
["ph_click_confirm"]="再次点击确认",
["b_options"]="选项",
["b_stat_vouchers"]="优惠券",
["k_money"]="资金",
["b_stats"]="统计数据",
["k_stake"]="赌注",
["b_set_screenshake"]="屏幕震动",
["ph_demo_thanks_2"]="BALATRO 演示版",
["b_stat_tarots"]="塔罗牌",
["ml_unlock_all_trophies"]={
[1]="警告！解锁全部收藏道具",
[2]="会禁用此账号的奖杯！",
},
["k_dwarf_planet"]="矮行星",
["b_stake"]="赌注",
["k_wins"]="获胜数",
["ph_unscored_hand"]="出牌将不会计分",
["k_ante_cap"]="底注",
["b_set_monitor"]="显示监视器",
["k_arcana_pack"]="秘术包",
["ph_defeat_this_blind_1"]="打败盲注",
["ph_no_vouchers"]="本赛局并未兑换任何优惠券",
["k_upgrade_ex"]="升级！",
["k_plus_spectral"]="+1幻灵牌",
["ml_unlock_all_explanation"]={
[1]="警告！解锁全部收藏道具",
[2]="会禁用此账号的成就！",
},
["b_redeem"]="兑换",
["b_next_round_2"]="回合",
["k_swapped_ex"]="已切换！",
["b_back"]="返回",
["k_base_cap"]="基础",
["ph_up_ante_2"]="加注所有盲注",
["k_game_modifiers"]="游戏修改器",
["b_create_profile"]="创建配置",
["b_copy_seed"]="复制种子",
["b_new_challenge"]="开始新挑战",
["k_plus_planet"]="+1星球牌",
["b_tarot_cards"]="塔罗牌",
["b_challenges"]="挑战",
["b_delete_profile"]="删除配置",
["k_ante"]="底注",
["ph_score_furthest_round"]="回合",
["k_vouchers_cap"]="优惠券",
["b_main_menu"]="主菜单",
["b_vouchers"]="优惠券",
["k_val_up"]="价值提升！",
["b_set_apply"]="应用",
["ml_smoothing_opt"]={
[1]="关闭",
[2]="开启",
},
["k_achievement"]="成就",
["b_use"]="使用",
["k_deck_stake_wins"]="牌组赌注完成度",
["$"]="$",
["b_set_master_vol"]="主音量",
["k_challenges"]="挑战",
["k_base_cards"]="基础卡牌",
["b_set_shadows"]="阴影",
["k_undisovered"]="未发现",
["ml_edition_seal_enhancement_explanation"]={
[1]="每张游戏牌可能会有",
[2]="增强、版本和蜡封版本",
},
["b_stat_consumables"]="消耗牌",
["b_buy"]="购买",
["k_page"]="页",
["k_defeated_by"]="击败",
["k_high_score_ex"]="高分！",
["ph_vouchers_redeemed"]="本赛局兑换的优惠券",
["ml_vsync_opt"]={
[1]="垂直同步开启",
[2]="垂直同步关闭",
},
["ph_score_cards_purchased"]="已购买卡牌",
["k_enter_seed"]="输入种子",
["k_incompatible"]="不兼容",
["b_options_cap"]="选项",
["b_set_CRT"]="CRT",
["k_no_reward"]="无奖励",
["b_cash_out"]="提现",
["k_spectral"]="幻灵",
["ml_eternal"]={
[1]="永恒卡",
[2]="不能出售",
[3]="或摧毁",
},
["b_unlock_all"]="解锁全部",
["k_legendary"]="传奇",
["b_skip_reward"]="跳过奖励",
["k_rank"]="点数",
["b_set_windowmode"]="窗口模式",
["ph_boss_disabled"]="Boss盲注限制条件失效",
["b_decks"]="牌组",
["ph_deck_preview_effective"]="因小丑、盲注和卡牌强化而产生的有效总数",
["k_trophies_disabled"]="奖杯被禁用",
["b_open"]="打开",
["b_set_CRT_bloom"]="模拟CRT荧光效果",
["k_aces"]="A",
["k_banned_cards"]="禁用卡",
["k_trophy"]="奖杯",
["b_select"]="选择",
["ph_score_at_least"]="至少得分",
["k_compatible"]="兼容",
["k_tarot"]="塔罗牌",
["k_active"]="已激活",
["k_buffoon_pack"]="小丑包",
["b_booster_packs"]="补充包",
["ph_choose_blind_1"]="选择你的",
["k_card_stats"]="卡牌属性",
["k_nope_ex"]="没有！",
["k_unknown"]="?????",
["k_seeded_run"]="预设局",
["k_hud_discards"]="弃牌",
["k_enter_text"]="输入文本",
["ml_gold_seal_desc"]={
[1]="黄金蜡封",
[2]="若打出",
[3]="返回手牌",
},
["k_no_space_ex"]="没有空间！",
["ph_score_hand"]="最佳出牌",
["k_joker_stickers"]="小丑贴纸",
["k_other"]="其他",
["b_discard"]="弃牌",
["ph_game_over"]="游戏结束",
["ph_defeat_this_blind_2"]="发现它",
["k_spectral_pack"]="幻灵包",
["ph_you_win_demo"]="你赢下了试玩版！",
["b_enhanced_cards"]="增强卡牌",
["k_redeemed_ex"]="兑换！",
["k_round"]="回合",
["b_run_info_2"]="信息",
["k_mult"]="倍率",
["k_challenge_mode"]="挑战模式",
["k_face_cards"]="人头牌",
["b_next"]="下一个",
["b_new_run"]="新一局",
["k_plus_tarot"]="+1塔罗牌",
["k_reward"]="奖励",
["k_level_prefix"]="等级",
["ph_1_level"]="+1级",
["b_load_profile"]="加载配置",
["ml_shadow_opt"]={
[1]="开启",
[2]="关闭",
},
["k_debuffed"]="被削弱",
["k_joker"]="小丑",
["ph_score_new_collection"]="新发现",
["k_planet_q"]="星球？",
["ph_score_poker_hand"]="最常用出牌",
["b_next_round_1"]="下一个",
["ph_score_furthest_ante"]="底注",
["ph_up_ante_3"]="刷新盲注",
["b_imagery"]="图像",
["k_lvl"]="级别",
["b_set_gamespeed"]="游戏速度",
["k_safe_ex"]="安全！",
["b_and_use"]="＆使用",
["ph_all_poker_hand"]="所有牌型",
["b_endless"]="无尽模式",
["ph_choose_blind_2"]="下一个盲注",
["b_stat_planets"]="星球牌",
["k_standard_pack"]="标准包",
["k_empty_caps"]="空",
["b_editions"]="版本",
["k_custom_rules"]="自定义规则",
["ph_demo_thanks_1"]="感谢游玩",
["k_voucher"]="优惠券",
["k_deck"]="牌组",
["ml_crash_report_info"]={
[1]="崩溃报告将发送给开发人员",
[2]="用以减少今后出现问题。",
[3]="不会发送身份信息或个人信息。",
},
["k_hud_hands"]="出牌",
["b_settings"]="设置",
["ph_up_ante_1"]="提高底注",
["k_no_room_ex"]="没有空间！",
["b_reroll_boss"]="重掷Boss盲注",
["b_stat_spectrals"]="幻灵牌",
["k_jokers_cap"]="小丑",
["k_plus_stone"]="+1石头牌",
["ph_4_7_of_clubs"]="四张梅花7",
["k_active_ex"]="激活！",
["k_suit"]="花色",
["k_locked"]="锁定",
["ph_blind_reward"]="奖励：",
["ph_stat_consumable"]="这张卡的使用次数",
["b_play_hand"]="出牌",
["b_playbalatro"]="访问 playbalatro.com",
["k_no_other_jokers"]="没有其他小丑牌！",
["k_achievements_disabled"]="未开启成就",
["k_none"]="无",
["k_reset"]="重置",
["k_stake_level"]="赌注等级",
["b_collection"]="收藏",
["b_current_profile"]="当前配置",
["b_quit_cap"]="退出",
["ml_card_stats"]={
[1]="卡牌",
[2]="统计数据",
},
["b_full_deck"]="完整牌组",
["b_set_game_vol"]="游戏音量",
["b_reset_profile"]="重设配置",
["k_daily_run"]="每日挑战",
["ml_bloom_opt"]={
[1]="关闭",
[2]="开启",
},
["b_set_crash_reports"]="崩溃报告",
["k_also_applied"]="同适用",
["ph_deck_preview_stones"]="石头",
["k_level_up_ex"]="提升等级！",
["k_all_hands"]="全部出牌",
["b_set_game"]="游戏",
["b_wishlist"]="在Steam上加入愿望单",
["k_again_ex"]="再来一次！",
["ph_you_win"]="你赢了！",
["k_plus_joker"]="+1小丑",
["b_remaining"]="剩余",
["k_edition"]="版本",
["ml_demo_thanks_message"]={
[1]="请考虑将Balatro列入",
[2]="steam许愿清单并注册",
[3]="playbalatro.com上的时事通讯",
},
["ph_score_cards_discarded"]="已弃掉卡牌",
["b_sell"]="售出",
["k_eaten_ex"]="被吃掉！",
["k_drank_ex"]="喝下去!",
["k_enter_name"]="输入名字",
["ph_defeat_the_boss"]="打赢Boss盲注",
["k_extinct_ex"]="已灭绝！",
["k_seed"]="种子",
["k_uncommon"]="罕见",
["k_melted_ex"]="已融化！",
["ph_stat_joker"]="使用此卡完成的总回合数",
["k_poker_hand"]="牌型",
["ml_disabled_seed"]={
[1]="所有解锁和",
[2]="发现均被禁用",
},
["b_spectral_cards"]="幻灵牌",
["b_blinds"]="盲注",
["b_continue"]="继续",
["k_banned_tags"]="禁用标签",
["b_poker_hands"]="牌型",
["k_duplicated_ex"]="重复！",
["k_profile"]="配置",
["k_demo_version_ex"]="试玩版！",
["k_best_hand"]="最佳出牌",
["k_numbered_cards"]="数字牌",
["b_sort_hand"]="理牌",
["k_not_discovered"]="未发现",
["k_common"]="普通",
["k_planet"]="星球牌",
["ph_score_cards_played"]="已使用卡牌",
["b_skip_blind"]="跳过盲注",
["b_start_new_run"]="开始新的一局",
["k_effective"]="有效",
["b_sounds"]="声音",
["b_tags"]="标签",
["k_or"]="或",
["ph_score_times_rerolled"]="重掷次数",
["b_set_pixel_smoothing"]="像素画平滑",
["ph_stat_voucher"]="兑换此优惠券的次数",
["ph_alert_debuff_confirm"]="再次按下”出牌“确认",
["k_celestial_pack"]="天体包",
["k_gold"]="金色",
["b_planet_cards"]="星球牌",
["k_view"]="查看",
["ph_mr_bones"]="被骷髅先生救了",
["ph_improve_run"]="提升你的成绩！",
["ml_windowmode_opt"]={
[1]="窗口模式",
[2]="全屏模式",
[3]="无边框模式",
},
["ph_most_played"]="{最常出的牌型}",
["b_set_audio"]="音频",
["b_collection_cap"]="收藏",
["b_set_music_vol"]="音乐音量",
["k_progress"]="进度",
["b_deck"]="牌组",
["b_skip"]="跳过",
["k_balanced"]="平衡",
["ph_sneak_peek"]="抢先看",
["ml_paste_seed"]={
[1]="粘贴",
[2]="种子",
},
["b_seals"]="蜡封",
["k_saved_ex"]="已储存！",
["b_seed"]="种子",
["k_cap_consumables"]="消耗牌",
["k_booster"]="补充包",
["k_eroded_ex"]="被腐蚀！",
},
["achievement_names"]={
["speedrunner"]="速通大神",
["card_player"]="玩牌能手",
["extreme_couponer"]="优惠券重度使用者",
["heads_up"]="注意",
["retrograde"]="逆序",
["shattered"]="破碎",
["completionist_plus_plus"]="完美主义者++",
["nest_egg"]="储备金",
["roi"]="投资回报率",
["royale"]="皇家",
["tiny_hands"]="小手",
["_100000k"]="1亿",
["cartomancy"]="纸牌卜卦",
["rule_breaker"]="规则破坏者",
["flushed"]="同花",
["mid_stakes"]="中赌注",
["completionist"]="完美主义者",
["low_stakes"]="低赌注",
["_1000k"]="100万",
["ante_upper"]="底注再上升！",
["astronomy"]="天文",
["big_hands"]="大手",
["card_discarder"]="弃牌能手",
["completionist_plus"]="完美主义者+",
["legendary"]="传奇",
["rule_bender"]="规则篡改者",
["_10k"]="1万",
["high_stakes"]="高赌注",
["clairvoyance"]="未卜先知",
["ante_up"]="底注上升！",
["you_get_what_you_get"]="种瓜得瓜",
},
["challenge_names"]={
["c_five_card_1"]="五连抽",
["c_mad_world_1"]="疯狂世界",
["c_monolith_1"]="巨石",
["c_fragile_1"]="易碎品",
["c_luxury_1"]="奢侈税",
["c_omelette_1"]="煎蛋卷",
["c_double_nothing_1"]="孤注一掷",
["c_blast_off_1"]="引燃",
["c_golden_needle_1"]="金针",
["c_rich_1"]="富者愈富",
["c_inflation_1"]="通货膨胀",
["c_knife_1"]="刀锋之上",
["c_jokerless_1"]="无小丑",
["c_non_perishable_1"]="不腐之物",
["c_medusa_1"]="美杜莎",
["c_xray_1"]="X光视界",
["c_bram_poker_1"]="布拉姆扑克",
["c_city_1"]="15分钟都市",
["c_cruelty_1"]="残酷",
["c_typecast_1"]="模式转换",
},
["v_dictionary"]={
["a_handsize"]="+#1#的手牌大小",
["loyalty_active"]="激活！",
["deck_preview_wheel_plural"]="由于抽出的#1#牌面朝下，数字可能较低",
["ante_x_voucher"]="底注#1#张优惠券",
["unlocked"]="#1#/#2#已解锁",
["ml_negative_desc"]={
[1]="负片",
[2]="+#1#小丑牌槽位",
},
["a_handsize_minus"]="-#1#手牌大小",
["a_xmult"]="X#1#倍率",
["a_mult_minus"]="-#1#倍率",
["a_xmult_minus"]="-X#1#倍率",
["a_mult"]="+#1#倍率",
["ml_negative_consumable_desc"]={
[1]="负片",
[2]="+#1#消耗牌槽位",
},
["loyalty_inactive"]="#1#剩余",
["interest"]="每$#2#获得#1#利息（最高 #3#）",
["deck_preview_wheel_singular"]="由于抽出的#1#牌面朝下，数字可能较低",
["ml_holo_desc"]={
[1]="镭射",
[2]="+#1#倍率",
},
["a_chips"]="+#1#",
["a_hands"]="+#1#出牌次数",
["a_chips_minus"]="-#1#",
["ml_polychrome_desc"]={
[1]="多彩",
[2]="+#1#倍率",
},
["a_sold_tally"]="#1#/#2#售出",
["completed"]="#1#/#2#已完成",
["remaining_discard_money"]="剩余弃牌次数（每次$#1#）",
["remaining_hand_money"]="剩余出牌次数（每次$#1#）",
["challenges_completed"]="已完成#1#/#2#挑战",
["ml_foil_desc"]={
[1]="闪箔",
[2]="+#1#筹码",
},
["a_remaining"]="剩余#1#",
},
["tutorial"]={
["bb_4"]={
[1]="如果你战胜了它，那么",
[2]="{C:attention}底注{}提升并且所有",
[3]="{C:attention}盲注{}变得更难",
},
["fh_4"]={
[1]="卡牌还可获得",
[2]="一些{C:blue}筹码{}，",
[3]="悬停此处查看！",
},
["fh_6"]={
[1]="还可以选择{C:red}“弃牌”{}，最多",
[2]="可弃掉{C:attention}5{}张选定卡牌",
[3]="以求组成",
[4]="更强牌型。试试吧！",
},
["fh_1"]={
[1]="你可以通过以下方式获得筹码",
[2]="打出{C:attention}牌型",
},
["s_5"]={
[1]="挑剔着点，",
[2]="你一次只能带",
[3]="{C:attention}5张小丑牌{}",
},
["fh_2"]={
[1]="{C:attention}牌型{}可获得",
[2]="基本{C:blue}筹码",
[3]="再乘以某个数值的{C:red}倍率加成",
},
["fh_3"]={
[1]="查看你的{C:attention}牌型",
[2]="可通过{C:attention}比赛信息{}区操作，",
[3]="同时可以查看其他",
[4]="关于当前游戏的信息",
},
["sh_3"]={
[1]="最多选择{C:attention}2{}张",
[2]="手持牌，并按下",
[3]="{C:attention}“使用”{}键，打出{C:tarot}塔罗牌{}",
[4]="施加增强效果！",
},
["fh_7"]={
[1]="小心！每回合你的",
[2]="{C:blue}出牌{}和{C:red}弃牌{}",
[3]="次数有限",
},
["fh_5"]={
[1]="现在选择最多",
[2]="{C:attention}5{}张牌",
[3]="并按下{C:blue}“出牌键”",
},
["sh_2"]={
[1]="确保你",
[2]="{C:attention}使用{}消耗牌！",
},
["bb_2"]={
[1]="或选择{C:attention}跳过",
[2]="可获得一个{C:attention}标签{}！每个",
[3]="{C:attention}标签{}具有独特的效果",
},
["s_7"]={
[1]="这张{C:tarot}塔罗牌{}是",
[2]="{C:attention}消耗牌{}。此牌可",
[3]="增强您在玩的",
[4]="卡牌。好好留着这张牌",
},
["s_3"]={
[1]="这是{C:attention}#1#张",
[2]="{C:attention}小丑牌{}之一的卡牌，可以添加到",
[3]="游戏中。每张{C:attention}小丑牌",
[4]="效果不同",
},
["s_11"]={
[1]="快来查看这两个",
[2]="{C:booster}补充包{}，",
[3]="所有商店均有售，",
[4]="补充包内增益多多！",
},
["bb_1"]={
[1]="选择{C:attention}大盲注",
[2]="可以让你赚钱",
},
["sh_1"]={
[1]="当你得到更多的卡牌时，",
[2]="请记住，你可以重新理牌。",
[3]="{C:attention}小丑牌{}触发顺序为",
[4]="从左至右",
},
["sb_4"]={
[1]="选择{C:blue}小盲注",
[2]="来开始回合！",
},
["s_4"]={
[1]="这个可以让你每次出牌",
[2]="{C:red}+4倍率{}",
},
["s_10"]={
[1]="只要你打败",
[2]="{C:attention}Boss盲注{}，",
[3]="{C:attention}优惠券{}会重新上架。",
},
["s_12"]={
[1]="让我们继续",
[2]="{C:attention}下一回合{}。",
},
["sb_2"]={
[1]="你的目标是赚取",
[2]="{C:blue}筹码{}以击败",
[3]="对手的{C:attention}盲注",
},
["s_6"]={
[1]="现在，从{C:attention}店内",
[2]="购买另一张卡牌。",
},
["s_2"]={
[1]="试试买这个",
[2]="超酷的小丑牌",
},
["sb_1"]={
[1]="你好呀！我叫",
[2]="{C:attention}金宝{}，我是来帮你的",
[3]="让我带你了解游玩的方法！",
},
["sb_3"]={
[1]="这是{C:blue}小盲注{}，",
[2]="你只需要获得",
[3]="{C:attention}300筹码{}就可击败它。",
},
["fh_8"]={
[1]="在使用完所有{C:blue}出牌{}",
[2]="次数前，赚取{C:attention}300筹码{}，",
[3]="来赢得此回合。",
[4]="祝你好运！",
},
["s_9"]={
[1]="如果你有足够的积蓄，",
[2]="可以购买{C:attention}优惠券{}。",
[3]="{C:attention}优惠券{}可以帮您",
[4]="提升本局体验",
},
["s_8"]={
[1]="您一次最多",
[2]="可以携带",
[3]="{C:attention}2张消耗牌{}",
},
["bb_5"]={
[1]="击败{C:attention}底注{}#1#以获胜。",
[2]="现在做出你的选择！",
},
["bb_3"]={
[1]="但要注意",
[2]="{C:attention}Boss盲注{}。 每个Boss盲注",
[3]="都有着限制条件",
[4]="您必须要有策略来应对。",
},
["s_1"]={
[1]="干得漂亮！现在",
[2]="你有一些{C:money}现金{}，",
[3]="你可以从{C:attention}店内",
[4]="买一些新的卡牌",
},
},
["labels"]={
["foil"]="闪箔",
["blue_seal"]="蓝色蜡封",
["rare"]="稀有",
["voucher"]="优惠券",
["purple_seal"]="紫色蜡封",
["gold_seal"]="金色蜡封",
["red_seal"]="红色蜡封",
["tarot"]="塔罗牌",
["negative"]="负片",
["pluto_planet"]="矮行星",
["common"]="普通",
["pinned_left"]="已固定",
["legendary"]="传奇",
["eternal"]="永恒卡",
["holographic"]="镭射",
["uncommon"]="罕见",
["planet"]="星球牌",
["locked"]="未解锁",
["polychrome"]="多彩",
},
["ranks"]={
["4"]="4",
["8"]="8",
["10"]="10",
["5"]="5",
["9"]="9",
["6"]="6",
["King"]="K",
["Ace"]="A",
["3"]="3",
["7"]="7",
["Jack"]="J",
["Queen"]="Q",
["2"]="2",
},
["high_scores"]={
["furthest_round"]="最高回合",
["hand"]="最佳出牌",
["furthest_ante"]="最高投注额",
["collection"]="收藏",
["current_streak"]="",
["boss_streak"]="最多连续击败Boss",
["poker_hand"]="最常用的出牌",
["most_money"]="最多资金",
["win_streak"]="最佳连胜纪录",
},
["suits_plural"]={
["Spades"]="黑桃",
["Hearts"]="红桃",
["Diamonds"]="方片",
["Clubs"]="梅花",
},
["poker_hand_descriptions"]={
["Flush House"]={
[1]="三条及对子，且",
[2]="花色相同",
},
["Full House"]={
[1]="三条及对子，且",
},
["Flush"]={
[1]="5张牌花色相同",
},
["Pair"]={
[1]="两张点数相同的牌可以与最多",
[2]="3张其他未计分的牌一同打出",
},
["Four of a Kind"]={
[1]="4张相同点数的牌",
[2]="可以与其他一张未计分的牌一同打出",
},
["Royal Flush"]={
[1]="连续5张牌（连续数字），且",
[2]="花色相同",
},
["Straight Flush"]={
[1]="连续5张牌（连续数字），且",
[2]="花色相同",
},
["Straight"]={
[1]="连续5张牌（连续数字）",
},
["Five of a Kind"]={
[1]="5张相同点数的牌",
},
["Flush Five"]={
[1]="5张相同点数和相同花色的牌",
},
["Two Pair"]={
[1]="两对不同点数的牌",
[2]="可以与其他一张未计分的牌一同打出",
},
["Three of a Kind"]={
[1]="3张点数相同的牌可以与最多",
[2]="2张其他未计分的牌一同打出",
},
["High Card"]={
[1]="如果打出的牌不是以上任何一种",
[2]="那么只有点数最高的牌得分",
},
},
},
}