return {
["tutorial"]={
},
["descriptions"]={
["Back"]={
["b_challenge"]={
["name"]="挑戰牌組",
["text"]={
[1]="",
},
},
["b_plasma"]={
["name"]="等離子牌組",
["text"]={
[1]="在計算局數分數時",
[2]="平均{C:blue}籌碼{}",
[3]="和{C:red}倍數{}",
[4]="盲注要求分數{C:red}X#1#{}",
},
},
["b_nebula"]={
["name"]="星雲牌組",
["text"]={
[1]="開局時得到",
[2]="{C:planet,T:v_telescope}#1#{}禮券",
[3]="",
[4]="及{C:red}#2#{}消耗牌欄位",
},
},
["b_anaglyph"]={
["name"]="浮雕牌組",
["text"]={
[1]="每次擊敗",
[2]="{C:attention}Boss盲注{}後，獲得一個",
[3]="{C:attention,T:tag_double}#1#",
},
},
["b_black"]={
["name"]="黑色牌組",
["text"]={
[1]="每一回合",
[2]="",
[3]="{C:attention}+#1#{}小丑牌欄位",
[4]="{C:blue}-#2#{}出牌次數",
},
},
["b_ghost"]={
["name"]="幽靈牌組",
["text"]={
[1]="商店內可能會有",
[2]="{C:spectral}幻靈牌{}",
[3]="開始時擁有{C:spectral,T:c_hex}妖術{}卡",
},
},
["b_abandoned"]={
["name"]="拋棄牌組",
["text"]={
[1]="開局時",
[2]="玩家牌組中",
[3]="沒有{C:attention}花牌",
},
},
["b_erratic"]={
["name"]="不穩定牌組",
["text"]={
[1]="牌組中所有",
[2]="{C:attention}點數{}和{C:attention}花色",
[3]="均為隨機設定",
},
},
["b_magic"]={
["name"]="魔術牌組",
["text"]={
[1]="開局時得到",
[2]="{C:tarot,T:v_crystal_ball}#1#{}禮券",
[3]="和{C:attention}2張{}",
[4]="{C:tarot,T:c_fool}#2#",
},
},
["b_red"]={
["name"]="紅色牌組",
["text"]={
[1]="每一回合",
[2]="{C:red}+#1#{}次棄牌",
},
},
["b_painted"]={
["name"]="彩繪牌組",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
[2]="{C:red}#2#{}小丑牌欄位",
},
},
["b_blue"]={
["name"]="藍色牌組",
["text"]={
[1]="每一回合",
[2]="{C:blue}+#1#{}次出牌",
},
},
["b_checkered"]={
["name"]="方格牌組",
["text"]={
[1]="開局時牌組為",
[2]="{C:attention}26張{C:spades}黑桃{}和",
[3]="{C:attention}26張{C:hearts}紅心{}",
},
},
["b_green"]={
["name"]="綠色牌組",
["text"]={
[1]="每一回合結束時：",
[2]="每剩一次{C:blue}出牌次數，獲得{C:money}$#1#{s:0.85}",
[3]="每剩一次{C:red}棄牌次數，獲得{C:money}$#2#{s:0.85}",
[4]="不獲得任何{C:attention}利息",
},
},
["b_yellow"]={
["name"]="黃色牌組",
["text"]={
[1]="開始時",
[2]="額外獲得{C:money}$#1#",
},
},
["b_zodiac"]={
["name"]="星座牌組",
["text"]={
[1]="開局時即擁有",
[2]="{C:tarot,T:v_tarot_merchant}#1#{}、",
[3]="{C:planet,T:v_planet_merchant}#2#{}",
[4]="和{C:attention,T:v_overstock_norm}#3#",
},
},
},
["Tag"]={
["tag_handy"]={
["name"]="方便標籤",
["text"]={
[1]="本賽局每打出一次{C:blue}手牌{}",
[2]="獲得{C:money}$#1#{}",
[3]="{C:inactive}(將得到{C:money}$#2#{C:inactive})",
},
},
["tag_standard"]={
["name"]="標準標籤",
["text"]={
[1]="獲得一個免費的",
[2]="{C:attention}超級標準禮包",
},
},
["tag_d_six"]={
["name"]="D6標籤",
["text"]={
[1]="下一次商店重摋",
[2]="起價為{C:money}$0",
},
},
["tag_negative"]={
["name"]="負片標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:dark_edition}負片小丑牌",
},
},
["tag_investment"]={
["name"]="投資標籤",
["text"]={
[1]="擊敗",
[2]="Boss盲注以後，",
[3]="獲得{C:money}$#1#",
},
},
["tag_holo"]={
["name"]="全像攝影標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:dark_edition}全像攝影小丑牌",
},
},
["tag_rare"]={
["name"]="稀有標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:red}稀有小丑牌",
},
},
["tag_skip"]={
["name"]="速度標籤",
["text"]={
[1]="本賽局中每跳過",
[2]="一次盲注，獲得{C:money}$#1#{}",
[3]="{C:inactive}(會給{C:money}$#2#{C:inactive})",
},
},
["tag_garbage"]={
["name"]="垃圾標籤",
["text"]={
[1]="本賽局每一未使用的{C:red}弃牌次数{}",
[2]="得到{C:money}$#1#{}",
[3]="{C:inactive}(將得到{C:money}$#2#{C:inactive})",
},
},
["tag_foil"]={
["name"]="銀箔標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:dark_edition}銀箔小丑牌",
},
},
["tag_buffoon"]={
["name"]="丑角標籤",
["text"]={
[1]="獲得一個免費的",
[2]="{C:attention}丑角禮包",
},
},
["tag_charm"]={
["name"]="魔力標籤",
["text"]={
[1]="獲得一個免費的",
[2]="{C:tarot}超級奧秘禮包",
},
},
["tag_ethereal"]={
["name"]="永存標籤",
["text"]={
[1]="獲得一個免費的",
[2]="{C:spectral}幻靈禮包",
},
},
["tag_orbital"]={
["name"]="軌道標籤",
["text"]={
[1]="升級{C:attention}#1#",
[2]="{C:attention}#2#個等級",
},
},
["tag_coupon"]={
["name"]="優惠券標籤",
["text"]={
[1]="下一家店的",
[2]="初始牌卡和擴充包",
[3]="均為免費",
},
},
["tag_boss"]={
["name"]="Boss標籤",
["text"]={
[1]="重摋",
[2]="{C:attention}Boss盲注",
},
},
["tag_top_up"]={
["name"]="儲值標籤",
["text"]={
[1]="產生最多{C:attention}#1#張",
[2]="{C:blue}一般{}小丑牌",
[3]="{C:inactive}(必須有空位)",
},
},
["tag_polychrome"]={
["name"]="彩色標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:dark_edition}彩色小丑牌",
},
},
["tag_meteor"]={
["name"]="流星標籤",
["text"]={
[1]="獲得一個免費的",
[2]="{C:planet}超級天外禮包",
},
},
["tag_double"]={
["name"]="雙倍標籤",
["text"]={
[1]="複製下一個",
[2]="選定的{C:attention}標籤{}",
[3]="{s:0.8,C:attention}雙倍標籤{s:0.8}除外",
},
},
["tag_juggle"]={
["name"]="雜耍標籤",
["text"]={
[1]="下一回合",
[2]="{C:attention}+#1#{}手牌大小",
},
},
["tag_economy"]={
["name"]="經濟標籤",
["text"]={
[1]="金錢加倍",
[2]="{C:inactive}(最高{C:money}$#1#{C:inactive})",
},
},
["tag_uncommon"]={
["name"]="罕見標籤",
["text"]={
[1]="下個商店內有一張",
[2]="{C:green}罕見小丑牌",
},
},
["tag_voucher"]={
["name"]="禮券標籤",
["text"]={
[1]="增加一張{C:voucher}禮券",
[2]="到下一間商店",
},
},
},
["Blind"]={
["bl_club"]={
["name"]="梅花",
["text"]={
[1]="所有梅花牌卡",
[2]="都不計分",
},
},
["bl_needle"]={
["name"]="細針",
["text"]={
[1]="此回合只能打出一種手牌類型",
},
},
["bl_small"]={
["name"]="小盲注",
["text"]={
},
},
["bl_arm"]={
["name"]="手臂",
["text"]={
[1]="降低玩的這局",
[2]="出牌的牌型等級",
},
},
["bl_plant"]={
["name"]="星球",
["text"]={
[1]="所有花牌",
[2]="都不計分",
},
},
["bl_wheel"]={
["name"]="巨輪",
["text"]={
[1]="/7機率一張牌",
[2]="以面朝下方式抽出",
},
},
["bl_mouth"]={
["name"]="嘴巴",
["text"]={
[1]="本回合只能打出",
[2]="一種手牌類型",
},
},
["bl_eye"]={
["name"]="眼睛",
["text"]={
[1]="本回合不能打出",
[2]="重複的手牌類型",
},
},
["bl_pillar"]={
["name"]="支柱",
["text"]={
[1]="上一次底注中",
[2]="打過的牌都不計分",
},
},
["bl_house"]={
["name"]="房子",
["text"]={
[1]="第一次的手牌",
[2]="以背面朝上方式抽取",
},
},
["bl_hook"]={
["name"]="鉤子",
["text"]={
[1]="每次出牌",
[2]="隨機丟棄2張手牌",
},
},
["bl_head"]={
["name"]="頭顱",
["text"]={
[1]="所有紅心牌卡",
[2]="都不計分",
},
},
["bl_goad"]={
["name"]="鞭策",
["text"]={
[1]="所有的黑桃牌卡",
[2]="都不計分",
},
},
["bl_final_leaf"]={
["name"]="翠綠樹葉",
["text"]={
[1]="所有牌卡都不計分",
[2]="直到賣出1張小丑牌",
},
},
["bl_ox"]={
["name"]="公牛",
["text"]={
[1]="打出#1#牌型時，",
[2]="設定金額至$0",
},
},
["bl_mark"]={
["name"]="標記",
["text"]={
[1]="所有花牌",
[2]="面朝下抽出",
},
},
["bl_final_vessel"]={
["name"]="紫羅蘭花器",
["text"]={
[1]="非常大盲注",
},
},
["bl_tooth"]={
["name"]="尖齒",
["text"]={
[1]="每出一張牌",
[2]="損失$1",
},
},
["bl_fish"]={
["name"]="魚",
["text"]={
[1]="在第一次出牌後",
[2]="抽的牌都是面朝下抽出",
},
},
["bl_big"]={
["name"]="大盲注",
["text"]={
},
},
["bl_final_acorn"]={
["name"]="琥珀橡果",
["text"]={
[1]="所有小丑牌都面朝下",
[2]="和牌位亂調",
},
},
["bl_flint"]={
["name"]="燧石",
["text"]={
[1]="基本籌碼和",
[2]="倍數都減半",
},
},
["bl_psychic"]={
["name"]="靈媒",
["text"]={
[1]="必須出5張牌",
},
},
["bl_window"]={
["name"]="窗戶",
["text"]={
[1]="所有方塊牌卡",
[2]="都不計分",
},
},
["bl_serpent"]={
["name"]="蛇",
["text"]={
[1]="每次出牌或棄牌後，",
[2]="都只抽出3張牌",
},
},
["bl_water"]={
["name"]="清水",
["text"]={
[1]="此回合開始於",
[2]="0 次棄牌次數",
},
},
["bl_manacle"]={
["name"]="手銬",
["text"]={
[1]="手牌大小-1",
},
},
["bl_wall"]={
["name"]="高牆",
["text"]={
[1]="特大盲注",
},
},
["bl_final_heart"]={
["name"]="緋紅之心",
["text"]={
[1]="每次出牌",
[2]="任一小丑牌功能失效",
},
},
["bl_final_bell"]={
["name"]="蔚藍鐘",
["text"]={
[1]="有一張牌會一直",
[2]="被強制選定",
},
},
},
["Voucher"]={
["v_tarot_merchant"]={
["name"]="塔羅牌商家",
["text"]={
[1]="在商店出現{C:tarot}塔羅牌{}",
[2]="的頻率增加",
[3]="{C:attention}#1#X{}倍",
},
},
["v_magic_trick"]={
["name"]="魔術",
["text"]={
[1]="{C:attention}商店{}裡面",
[2]="有{C:attention}遊戲牌{}",
[3]="可供選購",
},
},
["v_seed_money"]={
["name"]="種子資金",
["text"]={
[1]="提高每回合",
[2]="利息收入的",
[3]="上限至{C:money}$#1#{}",
},
},
["v_tarot_tycoon"]={
["unlock"]={
[1]="在商店",
[2]="購買總共",
[3]="{C:attention}#1#張{C:tarot}塔羅牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="塔羅大亨",
["text"]={
[1]="在商店出現{C:tarot}塔羅牌{}",
[2]="的頻率增加",
[3]="{C:attention}#1#X{}倍",
},
},
["v_overstock_norm"]={
["name"]="存貨過多",
["text"]={
[1]="店內牌卡欄位",
[2]="{C:attention}+1{}",
},
},
["v_wasteful"]={
["name"]="浪費",
["text"]={
[1]="每回合",
[2]="永久增加",
[3]="{C:red}+#1#{}次棄牌",
},
},
["v_grabber"]={
["name"]="搶奪者",
["text"]={
[1]="每回合",
[2]="永久增加",
[3]="{C:blue}+#1#{}次出牌",
},
},
["v_paint_brush"]={
["name"]="油漆刷",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
},
},
["v_money_tree"]={
["unlock"]={
[1]="連續{C:attention}#1#{}回合",
[2]="將回合收益",
[3]="利息提升到最高",
[4]="{C:inactive}(#2#)",
},
["name"]="金錢樹",
["text"]={
[1]="提高每回合",
[2]="利息收入的",
[3]="上限至{C:money}$#1#{}",
},
},
["v_clearance_sale"]={
["name"]="清倉拍賣",
["text"]={
[1]="店內的所有牌卡和套組",
[2]="費用減{C:attention}#1#%{}",
},
},
["v_hone"]={
["name"]="磨刀石",
["text"]={
[1]="{C:dark_edition}銀箔{}、{C:dark_edition}全像攝影{}和",
[2]="{C:dark_edition}彩色{}牌卡",
[3]="出現頻率{C:attention}X#1#倍",
},
},
["v_liquidation"]={
["unlock"]={
[1]="在一場賽局中",
[2]="至少兌換",
[3]="{C:attention}#1#{C:voucher}張禮券{}",
},
["name"]="清算",
["text"]={
[1]="店內的所有牌卡和套組",
[2]="皆享{C:attention}#1#%{}折扣優惠",
},
},
["v_hieroglyph"]={
["name"]="象形文字",
["text"]={
[1]="{C:attention}-#1#{}底注",
[2]="每回合",
[3]="{C:blue}-#1#{}出牌次數",
},
},
["v_omen_globe"]={
["unlock"]={
[1]="從任一{C:tarot}奧秘禮包中",
[2]="使用總計{C:attention}#1#張",
[3]="{C:tarot}塔羅牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="預兆地球儀",
["text"]={
[1]="{C:spectral}幻靈牌{}",
[2]="可能出現在任何",
[3]="{C:attention}奧秘禮包中",
},
},
["v_telescope"]={
["name"]="望遠鏡",
["text"]={
[1]="{C:attention}天外禮包{}裡面",
[2]="總是會有",
[3]="你最常使用{C:attention}牌型{}",
[4]="的{C:planet}行星牌{}",
},
},
["v_planet_tycoon"]={
["unlock"]={
[1]="在商店",
[2]="購買總共",
[3]="{C:attention}#1#{}張{C:planet}行星牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="行星大亨",
["text"]={
[1]="在商店出現{C:planet}行星牌{}",
[2]="的頻率增加",
[3]="{C:attention}#1#X{}倍",
},
},
["v_illusion"]={
["unlock"]={
[1]="在商店",
[2]="購買總共",
[3]="{C:attention}#1#{}張遊戲牌",
[4]="{C:inactive}(#2#)",
},
["name"]="幻想",
["text"]={
[1]="在商店內的{C:attention}遊戲牌{}",
[2]="可能是{C:enhanced}加強牌{}、{C:dark_edition}不同版本{}",
[3]="或/及蓋有{C:attention}封蠟章{}",
},
},
["v_reroll_glut"]={
["unlock"]={
[1]="商店重摋",
[2]="總計{C:attention}#1#{}次",
[3]="{C:inactive}(#2#)",
},
["name"]="重摋加強版",
["text"]={
[1]="重摋費用",
[2]="減少{C:money}$#1#{}",
},
},
["v_glow_up"]={
["unlock"]={
[1]="手上的牌至少要有{C:attention}#1#張",
[2]="{C:attention}小丑牌{}有",
[3]="{C:dark_edition}銀箔{}、{C:dark_edition}全像攝影{}或",
[4]="{C:dark_edition}彩色{}版本",
},
["name"]="閃亮亮",
["text"]={
[1]="{C:dark_edition}銀箔{}、{C:dark_edition}全像攝影{}和",
[2]="{C:dark_edition}彩色{}牌卡",
[3]="出現頻率{C:attention}X#1#倍",
},
},
["v_retcon"]={
["unlock"]={
[1]="發現",
[2]="{C:attention}#1#{}盲注",
},
["name"]="修訂佳作",
["text"]={
[1]="重開Boss盲注",
[2]="{C:attention}無限次{}",
[3]="每次花費{C:money}$#1#{}",
},
},
["v_nacho_tong"]={
["unlock"]={
[1]="打出總共",
[2]="{C:attention}#1#{}張牌",
[3]="{C:inactive}(#2#)",
},
["name"]="唐納喬",
["text"]={
[1]="每回合",
[2]="永久獲得",
[3]="{C:blue}+#1#{}次出牌",
},
},
["v_observatory"]={
["unlock"]={
[1]="從任一{C:planet}天外禮包中",
[2]="使用總計{C:attention}#1#張",
[3]="{C:planet}行星牌{}",
[4]="{C:inactive}(#2#)",
},
["name"]="天文台",
["text"]={
[1]="在您{C:attention}消耗牌欄位{}中",
[2]="的{C:planet}行星牌{}",
[3]="為該特定{C:attention}手牌類型",
[4]="給予{X:red,C:white}X#1#{}倍數",
},
},
["v_reroll_surplus"]={
["name"]="多次重摋",
["text"]={
[1]="重摋費用",
[2]="減少{C:money}$#1#{}",
},
},
["v_recyclomancy"]={
["unlock"]={
[1]="棄牌總數達到",
[2]="{C:attention}#1#{}張牌",
[3]="{C:inactive}(#2#)",
},
["name"]="回收魔法",
["text"]={
[1]="每回合",
[2]="永久獲得",
[3]="{C:red}+#1#{}次棄牌",
},
},
["v_palette"]={
["unlock"]={
[1]="縮減手牌大小",
[2]="至{C:attention}#1#{}牌",
},
["name"]="調色板",
["text"]={
[1]="手上持有{C:attention}+#1#{}",
},
},
["v_overstock_plus"]={
["unlock"]={
[1]="在店內花費總計",
[2]="{C:money}$#1#{}",
[3]="{C:inactive}($#2#)",
},
["name"]="存貨過多增強版",
["text"]={
[1]="店內牌卡欄位",
[2]="{C:attention}+1{}",
},
},
["v_blank"]={
["name"]="空白",
["text"]={
[1]="{C:inactive}有作用嗎？",
},
},
["v_directors_cut"]={
["name"]="導演佳作",
["text"]={
[1]="重摋Boss盲注",
[2]="每個底注重摋{C:attention}1{}次，",
[3]="每次{C:money}$#1#{}",
},
},
["v_petroglyph"]={
["unlock"]={
[1]="達到底注",
[2]="級別{E:1,C:attention}#1#",
},
["name"]="岩石雕刻",
["text"]={
[1]="{C:attention}-#1#{}底注",
[2]="每回合",
[3]="{C:red}-#1#{}棄牌次數",
},
},
["v_planet_merchant"]={
["name"]="行星牌商家",
["text"]={
[1]="在商店出現{C:planet}行星牌{}",
[2]="的頻率增加",
[3]="{C:attention}#1#X{}倍",
},
},
["v_antimatter"]={
["unlock"]={
[1]="兌換{C:voucher}空白{}禮券",
[2]="總計{C:attention}#1#{}次",
[3]="{C:inactive}(#2#)",
},
["name"]="反物質",
["text"]={
[1]="{C:dark_edition}+1{}小丑牌欄位",
},
},
["v_crystal_ball"]={
["name"]="水晶球",
["text"]={
[1]="{C:attention}+1{}消耗牌欄位",
},
},
},
["Enhanced"]={
["m_stone"]={
["name"]="石頭牌",
["text"]={
[1]="{C:chips}+#1#{}籌碼",
[2]="無點數或花色",
},
},
["m_mult"]={
["name"]="倍數牌",
["text"]={
[1]="{C:mult}+#1#{}倍數",
},
},
["m_wild"]={
["name"]="萬能牌",
["text"]={
[1]="可以用在",
[2]="任何花色",
},
},
["m_glass"]={
["name"]="玻璃牌",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍數，",
[2]="擁有{C:green}#2#/#3#{}的機率",
[3]="摧毀牌卡",
},
},
["m_steel"]={
["name"]="鋼鐵牌",
["text"]={
[1]="當這張牌卡",
[2]="在手上時",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["m_bonus"]={
["name"]="獎勵牌",
["text"]={
},
},
["m_gold"]={
["name"]="黃金牌",
["text"]={
[1]="在這回合結束時",
[2]="如果這張牌卡還在手上，",
[3]="金錢{C:money}$#1#{}",
},
},
["m_lucky"]={
["name"]="幸運牌",
["text"]={
[1]="{C:green}#1#/#3#{}的機率",
[2]="{C:mult}+#2#{}倍數",
[3]="{C:green}#1#/#5#{}的機率",
[4]="獲得{C:money}$#4#",
},
},
},
["Tarot"]={
["c_sun"]={
["name"]="太陽",
["text"]={
[1]="最多可轉換",
[2]="{C:attention}#1#{}張選定的牌",
[3]="至{V:1}#2#{}",
},
},
["c_empress"]={
["name"]="皇后",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌卡至",
[3]="{C:attention}#2#",
},
},
["c_star"]={
["name"]="星星",
["text"]={
[1]="最多可轉換",
[2]="{C:attention}#1#{}張選定的牌",
[3]="至{V:1}#2#{}",
},
},
["c_judgement"]={
["name"]="審判",
["text"]={
[1]="產生一張隨機的",
[2]="{C:attention}小丑牌{}",
[3]="{C:inactive}(必須有空位)",
},
},
["c_death"]={
["name"]="死神",
["text"]={
[1]="選擇{C:attention}#1#{}張牌卡，",
[2]="將{C:attention}左邊{}的牌卡",
[3]="轉換至{C:attention}右邊{}的牌卡",
[4]="{C:inactive}(拉動即可重新排列)",
},
},
["c_wheel_of_fortune"]={
["name"]="幸運之輪",
["text"]={
[1]="{C:green}#1#/#2#{}的機率會增加",
[2]="{C:dark_edition}銀箔{}、{C:dark_edition}全像攝影{}和",
[3]="{C:dark_edition}彩色{}版本",
[4]="至隨機一張{C:attention}小丑牌",
},
},
["c_heirophant"]={
["name"]="教皇",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌卡成為",
[3]="{C:attention}#2#",
},
},
["c_fool"]={
["name"]="愚者",
["text"]={
[1]="產生本賽局中",
[2]="上一張使用的",
[3]="{C:tarot}塔羅牌{}或{C:planet}行星牌{}",
[4]="{s:0.8,C:tarot}愚者牌{s:0.8}除外",
},
},
["c_high_priestess"]={
["name"]="女祭司",
["text"]={
[1]="產生最多{C:attention}#1#張",
[2]="隨機{C:planet}行星牌{}",
[3]="{C:inactive}(必須有空位)",
},
},
["c_chariot"]={
["name"]="戰車",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
["c_lovers"]={
["name"]="戀人",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
["c_hanged_man"]={
["name"]="吊人",
["text"]={
[1]="最多可摧毀",
[2]="{C:attention}#1#{}張選定的牌",
},
},
["c_strength"]={
["name"]="力量",
["text"]={
[1]="將最多{C:attention}#1#{}張",
[2]="選定的牌卡",
[3]="點數提高{C:attention}1",
},
},
["c_world"]={
["name"]="世界",
["text"]={
[1]="最多可轉換",
[2]="{C:attention}#1#{}張選定的牌",
[3]="至{V:1}#2#{}",
},
},
["c_hermit"]={
["name"]="隱士",
["text"]={
[1]="金錢加倍",
[2]="{C:inactive}(最高{C:money}$#1#{C:inactive})",
},
},
["c_devil"]={
["name"]="惡魔",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
["c_magician"]={
["name"]="魔術師",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
["c_moon"]={
["name"]="月亮",
["text"]={
[1]="最多可轉換",
[2]="{C:attention}#1#{}張選定的牌",
[3]="至{V:1}#2#{}",
},
},
["c_emperor"]={
["name"]="皇帝",
["text"]={
[1]="產生最多{C:attention}#1#張",
[2]="任意{C:tarot}塔羅牌{}",
[3]="{C:inactive}(必須有空位)",
},
},
["c_temperance"]={
["name"]="節制",
["text"]={
[1]="給出目前手上",
[2]="所有小丑牌卡",
[3]="的總賣價{C:inactive}(最高{C:money}$#1#{C:inactive})",
[4]="{C:inactive}(目前為{C:money}$#2#{C:inactive})",
},
},
["c_tower"]={
["name"]="高塔",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
["c_justice"]={
["name"]="正義",
["text"]={
[1]="加強{C:attention}#1#{}張",
[2]="所選的牌成為",
[3]="{C:attention}#2#",
},
},
},
["Stake"]={
["stake_green"]={
["name"]="綠色賭注",
["text"]={
[1]="每個{C:attention}底注所需分數",
[2]="以更快的尺度提高",
[3]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_blue"]={
["name"]="藍色賭注",
["text"]={
[1]="{C:red}-1{}棄牌次數",
[2]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_white"]={
["name"]="白色賭注",
["text"]={
[1]="基本難度",
},
},
["stake_red"]={
["name"]="紅色賭注",
["text"]={
[1]="{C:attention}小盲注{}",
[2]="無獎勵金",
[3]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_black"]={
["name"]="黑色賭注",
["text"]={
[1]="商店有{C:attention}永存{}小丑牌",
[2]="{C:inactive,s:0.8}(無法賣出或摧毀)",
[3]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_orange"]={
["name"]="橘色賭注",
["text"]={
[1]="{C:attention}擴充包{}費用",
[2]="會在每底注多貴{C:money}$1{}",
[3]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_purple"]={
["name"]="紫色賭注",
["text"]={
[1]="每個{C:attention}底注所需分數",
[2]="以更快的尺度提高",
[3]="{s:0.8}適用於所有先前的賭注",
},
},
["stake_gold"]={
["name"]="金色賭注",
["text"]={
[1]="手牌大小{C:red}-1{}",
[2]="{s:0.8}適用於所有先前的賭注",
},
},
},
["Planet"]={
["c_pluto"]={
["name"]="冥王星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_neptune"]={
["name"]="海王星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_mercury"]={
["name"]="水星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_jupiter"]={
["name"]="木星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_venus"]={
["name"]="金星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_mars"]={
["name"]="火星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_eris"]={
["name"]="鬩神星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_earth"]={
["name"]="地球",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_ceres"]={
["name"]="穀神星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_saturn"]={
["name"]="土星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_planet_x"]={
["name"]="X行星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
["c_uranus"]={
["name"]="天王星",
["text"]={
[1]="{S:0.8}({S:0.8,V:1}目前等級#1#{S:0.8}){}升級",
[2]="{C:attention}#2#",
[3]="{C:mult}+#3#{}倍數和",
[4]="{C:chips}+#4#{}籌碼",
},
},
},
["Other"]={
["p_buffoon_jumbo"]={
["name"]="特大丑角禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:joker}小丑牌{}中",
[2]="選擇{C:attention}#1#{}張",
},
},
["p_standard_jumbo"]={
["name"]="特大標準禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:attention}遊戲牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="到你的牌組",
},
},
["debuffed_default"]={
["name"]="遭減益",
["text"]={
[1]="所有能力",
[2]="失效",
},
},
["undiscovered_spectral"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="購買或使用",
[3]="禮券",
[4]="瞭解功用",
},
},
["p_celestial_jumbo"]={
["name"]="超大天外禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:planet}行星牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["demo_shop_locked"]={
["name"]="已鎖定",
["text"]={
[1]="{C:attention}金寶的",
[2]="個人收藏牌卡。",
[3]="將於正式版的",
[4]="{E:1,C:red}Balatro可供使用",
},
},
["black_sticker"]={
["name"]="黑色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}黑色",
[3]="{C:attention}賭注{}難度",
},
},
["p_spectral_jumbo"]={
["name"]="特大幻靈禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:spectral}幻靈牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["challenge_locked"]={
["name"]="已鎖定",
["text"]={
[1]="用至少#1#個不同牌組",
[2]="贏得一場比賽以解鎖",
[3]="挑戰模式",
[4]="{C:attention,s:2}#2#/#1#",
},
},
["undiscovered_joker"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="購買或使用",
[3]="禮券",
[4]="瞭解功用",
},
},
["purple_seal"]={
["name"]="紫色封蠟章",
["text"]={
[1]="{C:attention}棄此牌時",
[2]="產生一張{C:tarot}塔羅牌{}",
[3]="{C:inactive}(必須有空位)",
},
},
["card_chips"]={
["text"]={
[1]="{C:chips}+#1#{}籌碼",
},
},
["p_standard_normal"]={
["name"]="標準禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:attention}遊戲牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="到你的牌組",
},
},
["red_seal"]={
["name"]="紅色封蠟章",
["text"]={
[1]="重新觸發",
[2]="{C:attention}1{}次這張牌",
},
},
["white_sticker"]={
["name"]="白色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}白色",
[3]="{C:attention}賭注{}難度",
},
},
["playing_card"]={
["text"]={
[1]="{V:1}#2#{C:light_black}#1#",
},
},
["card_extra_chips"]={
["text"]={
[1]="{C:chips}+#1#{}個額外籌碼",
},
},
["deck_locked_stake"]={
["name"]="已鎖定",
["text"]={
[1]="用任一牌組贏得比賽，",
[2]="至少需為",
[3]="{V:1}#1#{}難度",
},
},
["orange_sticker"]={
["name"]="橘色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}橘色",
[3]="{C:attention}賭注{}難度",
},
},
["red_sticker"]={
["name"]="紅色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}紅色",
[3]="{C:attention}賭注{}難度",
},
},
["p_standard_mega"]={
["name"]="超級標準禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:attention}遊戲牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="到你的牌組",
},
},
["locked"]={
["name"]="已鎖定",
["text"]={
},
},
["debuffed_playing_card"]={
["name"]="遭減益",
["text"]={
[1]="得分無籌碼，",
[2]="不能觸發任何",
[3]="功能或效果",
},
},
["green_sticker"]={
["name"]="綠色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}綠色",
[3]="{C:attention}賭注{}難度",
},
},
["deck_locked_win"]={
["name"]="已鎖定",
["text"]={
[1]="在任一難度下",
[2]="使用{C:attention}#1#{}",
[3]="贏得一場比賽",
},
},
["undiscovered_tag"]={
["name"]="未發現",
["text"]={
[1]="使用這個標籤在",
[2]="在無種子比賽",
[3]="瞭解功用",
},
},
["p_buffoon_normal"]={
["name"]="丑角禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:joker}小丑牌{}中",
[2]="選擇{C:attention}#1#{}張",
},
},
["undiscovered_tarot"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="購買或使用",
[3]="禮券",
[4]="瞭解功用",
},
},
["remove_negative"]={
["text"]={
},
},
["pinned_left"]={
["name"]="已釘選",
["text"]={
[1]="這張小丑牌",
[2]="已釘選在",
[3]="最左邊位置",
},
},
["gold_seal"]={
["name"]="金色封蠟章",
["text"]={
[1]="打出這張牌",
[2]="且此牌計分，",
[3]="獲得{C:money}$3{}",
},
},
["demo_locked"]={
["name"]="已鎖定",
["text"]={
[1]="本試玩版",
[2]="暫不適用",
},
},
["undiscovered_edition"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="找到此版本",
[3]="瞭解功用",
},
},
["wip_locked"]={
["name"]="已鎖定",
["text"]={
[1]="正在",
[2]="製作中",
},
},
["undiscovered_booster"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="打開此禮包",
[3]="瞭解功用",
},
},
["p_spectral_normal"]={
["name"]="幻靈禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:spectral}幻靈牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["deck_locked_discover"]={
["name"]="已鎖定",
["text"]={
[1]="在收藏中",
[2]="發現至少",
[3]="{C:attention}#1#{}個項目",
},
},
["gold_sticker"]={
["name"]="金色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}金色",
[3]="{C:attention}賭注{}難度",
},
},
["p_celestial_normal"]={
["name"]="天外禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:planet}行星牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["blue_seal"]={
["name"]="藍色封蠟章",
["text"]={
[1]="當這張牌在回合結束時",
[2]="還{C:attention}保留{}在手牌中",
[3]="產生一張{C:planet}行星牌{}",
},
},
["undiscovered_voucher"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="兌換此",
[3]="禮券",
[4]="瞭解功用",
},
},
["p_arcana_normal"]={
["name"]="奧秘禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:tarot}塔羅牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["joker_locked_legendary"]={
["name"]="已鎖定",
["text"]={
[1]="透過{C:spectral}靈魂{}牌",
[2]="找到這張小丑牌",
},
},
["blue_sticker"]={
["name"]="藍色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}藍色",
[3]="{C:attention}賭注{}難度",
},
},
["p_arcana_mega"]={
["name"]="超級奧秘禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:tarot}塔羅牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["p_buffoon_mega"]={
["name"]="超級丑角禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:joker}小丑牌{}中",
[2]="選擇{C:attention}#1#{}張",
},
},
["eternal"]={
["name"]="永恆",
["text"]={
[1]="不能賣出",
[2]="或催毀",
},
},
["purple_sticker"]={
["name"]="紫色貼紙",
["text"]={
[1]="使用這張小丑牌",
[2]="贏得{C:attention}紫色",
[3]="{C:attention}賭注{}難度",
},
},
["undiscovered_planet"]={
["name"]="未發現",
["text"]={
[1]="在無種子比賽",
[2]="購買或使用",
[3]="禮券",
[4]="瞭解功用",
},
},
["p_arcana_jumbo"]={
["name"]="特大奧秘禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:tarot}塔羅牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["p_celestial_mega"]={
["name"]="超級天外禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:planet}行星牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
["p_spectral_mega"]={
["name"]="超級幻靈禮包",
["text"]={
[1]="從最多{C:attention}#2#張{C:spectral}幻靈牌{}中",
[2]="選擇{C:attention}#1#{}張",
[3]="並馬上使用",
},
},
},
["Edition"]={
["e_negative"]={
["name"]="負片",
["text"]={
[1]="{C:dark_edition}+#1#{}小丑牌欄位",
},
},
["e_polychrome"]={
["name"]="彩色",
["text"]={
[1]="{X:mult,C:white}X#1#{}倍數",
},
},
["e_holo"]={
["name"]="全像攝影",
["text"]={
[1]="{C:mult}+#1#{}倍數",
},
},
["e_negative_consumable"]={
["name"]="負片",
["text"]={
[1]="{C:dark_edition}+#1#{}消耗牌欄位",
},
},
["e_base"]={
["name"]="基本",
["text"]={
[1]="無額外效果",
},
},
["e_foil"]={
["name"]="銀箔",
["text"]={
[1]="{C:chips}+#1#{}籌碼",
},
},
},
["Joker"]={
["j_mime"]={
["name"]="默劇小丑",
["text"]={
[1]="重新觸發",
[2]="所有手中{C:attention}持有的",
[3]="{C:attention}手牌{}的能力",
},
},
["j_sly"]={
["name"]="狡詐小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#，",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_ceremonial"]={
["name"]="恐佈匕首",
["text"]={
[1]="每次{C:attention}盲注{}選擇後，",
[2]="摧毀右邊的小丑牌",
[3]="並永久增加其賣出價",
[4]="的{C:attention}兩倍{}至目前{C:red}倍數",
[5]="{C:inactive}(目前為{C:mult}+#1#{C:inactive}倍)",
},
},
["j_supernova"]={
["name"]="超新星",
["text"]={
[1]="將{C:attention}牌型{}的",
[2]="出牌次數",
[3]="增加到得分倍數",
},
},
["j_droll"]={
["name"]="古怪小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#{}，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_perkeo"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="佩爾基",
["text"]={
[1]="在結束商店後",
[2]="隨機複製{C:attention}1{}張",
[3]="擁有的{C:attention}消耗牌{}",
[4]="並給那張牌{C:dark_edition}負片{}效果",
},
},
["j_seance"]={
["name"]="亡靈之約",
["text"]={
[1]="如果{C:attention}手牌{}為{C:attention}#1#{}",
[2]="即產生一張",
[3]="隨機的{C:spectral}幻靈牌{}",
[4]="{C:inactive}(必須有空位)",
},
},
["j_four_fingers"]={
["name"]="四張牌",
["text"]={
[1]="所有{C:attention}同花{}和",
[2]="{C:attention}順子{}可以",
[3]="只用{C:attention}4{}張牌湊成",
},
},
["j_golden"]={
["name"]="黃金小丑",
["text"]={
[1]="於每一回合結束時",
[2]="獲得{C:money}$#1#{}",
},
},
["j_delayed_grat"]={
["name"]="最後獎賞",
["text"]={
[1]="如果在本回合未使用棄牌，",
[2]="每一個{C:attention}棄牌數{}",
[3]="獲得{C:money}$#1#{}",
},
},
["j_castle"]={
["name"]="城堡",
["text"]={
[1]="每次丟棄{V:1}#2#{}花色牌，",
[2]="此小丑牌獲得{C:chips}+#1#{}籌碼",
[3]="每回合花色都會變更",
[4]="{C:inactive}(目前為{C:chips}+#3#{C:inactive}籌碼)",
},
},
["j_hit_the_road"]={
["unlock"]={
[1]="同時將{E:1,C:attention}5張",
[2]="{E:1,C:attention}J{}",
[3]="全部棄掉",
},
["name"]="一路暢通",
["text"]={
[1]="每捨棄一張",
[2]="{C:attention}J{}，本回合",
[3]="獲得{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_card_sharp"]={
["name"]="老千小丑",
["text"]={
[1]="當這一{C:attention}牌型{}",
[2]="已經在這回合出過時，",
[3]="倍數{X:mult,C:white}X#1#{}",
},
},
["j_pareidolia"]={
["name"]="迷幻錯覺",
["text"]={
[1]="所有牌",
[2]="一律會被視為",
[3]="{C:attention}花牌{}",
},
},
["j_green_joker"]={
["name"]="綠色小丑",
["text"]={
[1]="每次出牌，{C:mult}+#1#{}倍數",
[2]="每次棄牌，{C:mult}-#2#{}倍數",
[3]="{C:inactive}(目前為{C:mult}+#3#{C:inactive}倍)",
},
},
["j_shortcut"]={
["name"]="捷徑",
["text"]={
[1]="允許{C:attention}順子{}能以",
[2]="相差1點的牌{C:attention}組成",
[3]="{C:inactive}(例如：{C:attention}2 3 5 7 8{C:inactive})",
},
},
["j_luchador"]={
["name"]="鬥士",
["text"]={
[1]="賣出這張牌卡以",
[2]="消除目前的",
[3]="{C:attention}Boss盲注{}限制功能",
},
},
["j_devious"]={
["name"]="心機小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#，",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_steel_joker"]={
["name"]="鋼鐵小丑",
["text"]={
[1]="每次{C:attention}鋼鐵牌",
[2]="你的牌組裡的",
[3]="{C:chips}+#1#{}籌碼",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_rocket"]={
["name"]="火箭",
["text"]={
[1]="每回合結束時獲得{C:money}$#1#{}。",
[2]="每次打敗{C:attention}Boss盲注{}時",
[3]="獲得{C:money}$#2#",
},
},
["j_credit_card"]={
["name"]="信用卡",
["text"]={
[1]="最多可負債",
[2]="至{C:red}$#1#{}",
},
},
["j_hologram"]={
["name"]="全像",
["text"]={
[1]="每次新增{C:attention}牌卡{}",
[2]="至牌組時，",
[3]="{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_ride_the_bus"]={
["name"]="公車卡",
["text"]={
[1]="若連續打出",
[2]="沒有{C:attention}花牌{}的",
[3]="計分手牌，",
[4]="每次倍數{C:mult}+#1#",
[5]="{C:inactive}(目前為{C:mult}+#2#{C:inactive}倍)",
},
},
["j_hiker"]={
["name"]="登山小丑",
["text"]={
[1]="每張打出的",
[2]="{C:attention}計分牌{}可永久",
[3]="獲得{C:chips}+#1#{}籌碼",
},
},
["j_ramen"]={
["name"]="拉麵",
["text"]={
[1]="擁有{X:mult,C:white}X#1#{}倍數",
[2]="每{C:attention}丟棄一張牌{}，",
[3]="失去{X:mult,C:white}X#2#{}倍數",
},
},
["j_square"]={
["name"]="方塊小丑",
["text"]={
[1]="每打出{C:attention}4{}張牌",
[2]="則可獲得",
[3]="{C:chips}+#1#{}籌碼",
[4]="{C:inactive}(目前{C:chips}#1#{}籌碼)",
},
},
["j_baseball"]={
["name"]="棒球牌",
["text"]={
[1]="每張擁有的{C:green}罕見{}小丑牌",
[2]="給予{X:mult,C:white}X#1#{}倍數",
},
},
["j_burglar"]={
["name"]="竊賊小丑",
["text"]={
[1]="選擇{C:attention}盲注{}後，",
[2]="{C:blue}+#1#{}出牌次數並",
[3]="{C:attention}失去所有棄牌次數",
},
},
["j_reserved_parking"]={
["name"]="私人車位",
["text"]={
[1]="手牌中",
[2]="每張持有的{C:attention}花牌{}",
[3]="有{C:green}#2#/#3#{}的機率",
[4]="給予{C:money}$#1#{}",
},
},
["j_cavendish"]={
["name"]="華蕉",
["text"]={
[1]="倍數{X:mult,C:white}X#1#{}，",
[2]="每回合結束時",
[3]="有{C:green}#2#/#3#{}的機率",
[4]="此牌會被摧毀",
},
},
["j_erosion"]={
["name"]="侵蝕",
["text"]={
[1]="在你的牌組中",
[2]="每張低於{C:attention}#3#{}張的牌卡",
[3]="均可獲得{C:red}+#1#{}倍數",
[4]="{C:inactive}(目前為{C:red}+#2#{C:inactive}倍)",
},
},
["j_trio"]={
["unlock"]={
[1]="贏得比賽",
[2]="且沒有打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="三重奏",
["text"]={
[1]="如果打出的牌",
[2]="包含{C:attention}#2#{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_flash"]={
["name"]="閃卡",
["text"]={
[1]="在商店內每{C:attention}重摋{}一次",
[2]="獲得{C:mult}+#1#{}倍數",
[3]="{C:inactive}(目前為{C:mult}+#2#{C:inactive}倍)",
},
},
["j_blueprint"]={
["unlock"]={
[1]="贏得比賽",
},
["name"]="藍圖小丑",
["text"]={
[1]="複製",
[2]="右邊{C:attention}小丑牌{}的能力",
},
},
["j_joker"]={
["name"]="小丑",
["text"]={
[1]="倍數{C:red,s:1.1}+#1#{}",
},
},
["j_red_card"]={
["name"]="紅牌",
["text"]={
[1]="當跳過任一{C:attention}擴充包{}時",
[2]="獲得{C:red}+#1#{}倍數",
[3]="{C:inactive}(目前為{C:red}+#2#{C:inactive}倍)",
},
},
["j_onyx_agate"]={
["unlock"]={
[1]="在你的牌組中",
[2]="至少要有{E:1,C:attention}#1#張",
[3]="{E:1,C:attention}#2#花色的牌",
},
["name"]="黑瑪瑙",
["text"]={
[1]="只要每次打出",
[2]="{C:clubs}梅花{}花色牌，",
[3]="得分時，{C:mult}+#1#{}倍數",
},
},
["j_loyalty_card"]={
["name"]="積分卡",
["text"]={
[1]="每出牌{C:attention}#2#{}次",
[2]="獲得一次倍數{X:red,C:white}X#1#{}",
[3]="{C:inactive}#3#次",
},
},
["j_trousers"]={
["name"]="備用長褲",
["text"]={
[1]="如果出牌的牌型包含",
[2]="{C:attention}#2#，",
[3]="獲得{C:mult}+#1#{}倍數",
[4]="{C:inactive}(目前為{C:red}+#3#{C:inactive}倍)",
},
},
["j_baron"]={
["name"]="男爵",
["text"]={
[1]="手牌中，每",
[2]="持有一張{C:attention}K{}，",
[3]="給予{X:mult,C:white}X#1#{}倍數",
},
},
["j_space"]={
["name"]="太空小丑",
["text"]={
[1]="每次出牌",
[2]="有{C:green}#1#/#2#{}的機率",
[3]="升級{C:attention}牌型等級{}",
},
},
["j_triboulet"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="弄臣小丑",
["text"]={
[1]="打出的{C:attention}K{}和{C:attention}Q",
[2]="各自獲得",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_gift"]={
["name"]="禮物卡",
["text"]={
[1]="在每回合結束時",
[2]="每張擁有的{C:attention}小丑牌{}",
[3]="及{C:attention}消耗卡{}",
[4]="{C:attention}售價{}加{C:money}$#1#{}",
},
},
["j_wily"]={
["name"]="狡猾小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#，",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_even_steven"]={
["name"]="互不相欠",
["text"]={
[1]="每打出一張計分的",
[2]="{C:attention}偶數{}點的牌，",
[3]="得分時，{C:mult}+#1#{}倍數",
[4]="{C:inactive}(10、8、6、4、2)",
},
},
["j_half"]={
["name"]="半個小丑",
["text"]={
[1]="如果打出",
[2]="不超過{C:attention}#2#{}張牌，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_ancient"]={
["name"]="古代小丑",
["text"]={
[1]="每次打出",
[2]="{V:1}#2#{}花色的牌，",
[3]="得分時獲得{X:mult,C:white}X#1#{}倍數",
[4]="{s:0.8}花色於每回合結束時變更",
},
},
["j_walkie_talkie"]={
["name"]="對講機",
["text"]={
[1]="每打出數字{C:attention}10{}或{C:attention}4，",
[2]="得分時給予{C:chips}+#1#{}籌碼及",
[3]="{C:mult}+#2#{}倍數",
},
},
["j_merry_andy"]={
["unlock"]={
[1]="在{E:1,C:attention}#1#回合或",
[2]="或更少的回合數下勝出",
},
["name"]="快樂小丑",
["text"]={
[1]="{C:red}+#1#{}棄牌次數",
[2]="{C:red}#2#{}手牌大小",
},
},
["j_gros_michel"]={
["name"]="大麥克香蕉",
["text"]={
[1]="倍數{C:mult}+#1#{}，",
[2]="每回合結束時",
[3]="有{C:green}#2#/#3#{}的機率",
[4]="此牌會被銷毀",
},
},
["j_astronomer"]={
["unlock"]={
[1]="發現每張",
[2]="{E:1,C:planet}行星牌{}",
},
["name"]="天文學家",
["text"]={
[1]="商店裡的{C:planet}行星牌{}",
[2]="以及{C:planet}天外禮包{}",
[3]="全部{C:attention}免費",
},
},
["j_crafty"]={
["name"]="鬼靈精小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#，",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_mail"]={
["name"]="郵件",
["text"]={
[1]="每棄牌一張{C:attention}#2#{}",
[2]="獲得{C:money}$#1#{}，",
[3]="每回合數字都會變更",
},
},
["j_chaos"]={
["name"]="慌亂小丑",
["text"]={
[1]="每回合在商店可",
[2]="{C:green}免費{}重新洗牌{C:attention}#1#{}次",
},
},
["j_troubadour"]={
["unlock"]={
[1]="透過只打出",
[2]="一次手牌",
[3]="連勝{C:attention,E:1}#1#{}回合",
},
["name"]="吟遊詩人",
["text"]={
[1]="手牌大小{C:attention}+#1#{}，",
[2]="每回合出牌次數{C:red}-#2#{}次",
},
},
["j_wrathful_joker"]={
["name"]="憤怒小丑",
["text"]={
[1]="每打出一張",
[2]="{C:spades}#2#{}花色的牌，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_lucky_cat"]={
["name"]="幸運貓",
["text"]={
[1]="每次{C:green}成功{}觸發",
[2]="{C:attention}幸運牌{}時",
[3]="獲得{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_mr_bones"]={
["unlock"]={
[1]="輸掉{C:attention,E:1}#1#{}場比賽",
[2]="{C:inactive}(#2#)",
},
["name"]="骷髏頭",
["text"]={
[1]="若得分時，獲得",
[2]="所需籌碼的",
[3]="{C:attention}25%{}或以上，",
[4]="可避免死亡",
[5]="{S:1.1,C:red,E:2}自我毀滅{}",
},
},
["j_obelisk"]={
["name"]="方尖碑",
["text"]={
[1]="每次連續打出的牌",
[2]="若非最常打出的",
[3]="{C:attention}牌型{}，就給予",
[4]="{X:mult,C:white}X#1#{}倍數",
[5]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_gluttenous_joker"]={
["name"]="貪吃小丑",
["text"]={
[1]="每打出一張",
[2]="{C:clubs}#2#{}花色的牌，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_glass"]={
["unlock"]={
[1]="牌組中至少要有",
[2]="{E:1,C:attention}#1#張{E:1,C:attention}#2#",
[3]="花色的牌",
},
["name"]="玻璃小丑",
["text"]={
[1]="每摧毀一張",
[2]="{C:attention}玻璃牌{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_clever"]={
["name"]="機靈小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#，",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_scholar"]={
["name"]="學者小丑",
["text"]={
[1]="每打出一張{C:attention}A{}，",
[2]="得分時，",
[3]="{C:chips}+#2#{}籌碼、",
[4]="{C:mult}+#1#{}倍數",
},
},
["j_blue_joker"]={
["name"]="藍色小丑",
["text"]={
[1]="每張在{C:attention}牌組{}剩下的牌",
[2]="可{C:chips}+#1#{}籌碼",
[3]="{C:inactive}(目前為{C:chips}+#2#{C:inactive}籌碼)",
},
},
["j_arrowhead"]={
["unlock"]={
[1]="牌組中至少要有",
[2]="{E:1,C:attention}#1#張{E:1,C:attention}#2#",
[3]="花色的牌",
},
["name"]="石箭頭",
["text"]={
[1]="只要每次打出",
[2]="{C:spades}黑桃{}花色牌，",
[3]="得分時{C:chips}+#1#{}籌碼",
},
},
["j_throwback"]={
["unlock"]={
[1]="從主選單",
[2]="繼續玩已儲存的比賽",
},
["name"]="復古小丑",
["text"]={
[1]="此比賽中每跳過一次",
[2]="{C:attention}盲注{}，{X:mult,C:white}X#1#{}倍數",
[3]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_invisible"]={
["unlock"]={
[1]="拿到不超過{E:1,C:attention}4張小丑牌{}",
[2]="的情況",
[3]="贏得比賽",
},
["name"]="隱形小丑",
["text"]={
[1]="在{C:attention}#1#{}回合後，",
[2]="賣出這張牌卡以",
[3]="{C:attention}複製{}隨機一張小丑牌",
[4]="{C:inactive}(目前為{C:attention}#2#{C:inactive}/#1#)",
},
},
["j_cloud_9"]={
["name"]="9霄雲外",
["text"]={
[1]="每張牌組內的數字{C:attention}9{}",
[2]="在每回合結束時",
[3]="獲得{C:money}$#1#{}",
[4]="{C:inactive}(目前{C:money}$#2#{}{C:inactive})",
},
},
["j_greedy_joker"]={
["name"]="貪心小丑",
["text"]={
[1]="每打出一張",
[2]="{C:diamonds}#2#{}花色的牌，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_runner"]={
["name"]="跑者小丑",
["text"]={
[1]="每次打出{C:attention}順子{}",
[2]="就會獲得",
[3]="{C:chips}+#2#{}籌碼",
[4]="{C:inactive}(目前{C:chips}+#1#{C:inactive}籌碼)",
},
},
["j_egg"]={
["name"]="蛋頭小丑",
["text"]={
[1]="在回合結束時",
[2]="本卡的{C:attention}出售價值",
[3]="增加{C:money}$#1#",
},
},
["j_duo"]={
["unlock"]={
[1]="贏得比賽",
[2]="且沒有打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="二重奏",
["text"]={
[1]="如果打出的牌",
[2]="包含{C:attention}#2#{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_flower_pot"]={
["unlock"]={
[1]="達到底注",
[2]="級別{E:1,C:attention}#1#",
},
["name"]="盆栽",
["text"]={
[1]="如果出牌中有計分的牌",
[2]="包含{C:diamonds}方塊{}、{C:clubs}梅花{}、",
[3]="{C:hearts}紅心{}及{C:spades}黑桃{}，",
[4]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_mystic_summit"]={
["name"]="神秘之峰",
["text"]={
[1]="當剩下{C:attention}#2#{}次",
[2]="棄牌數時，",
[3]="倍數{C:mult}+#1#{}",
},
},
["j_midas_mask"]={
["name"]="邁達斯面具",
["text"]={
[1]="出牌時，",
[2]="將所有打出的{C:attention}花牌{}",
[3]="變成{C:attention}黃金牌{}",
},
},
["j_smiley"]={
["name"]="笑臉",
["text"]={
[1]="打出{C:attention}花牌{}",
[2]="得分時",
[3]="給予{C:mult}+#1#{}倍數",
},
},
["j_drunkard"]={
["name"]="喝掛小丑",
["text"]={
[1]="{C:red}+#1#{}次棄牌數",
},
},
["j_diet_cola"]={
["name"]="低卡可樂",
["text"]={
[1]="賣出這張牌卡以",
[2]="建立一個免費",
[3]="{C:attention}#1#",
},
},
["j_shoot_the_moon"]={
["unlock"]={
[1]="在一個回合中",
[2]="打出牌組中",
[3]="所有{E:1,C:attention}紅心",
},
["name"]="射月亮",
["text"]={
[1]="手上每張持有的",
[2]="{C:attention}黑桃Q",
[3]="{C:mult}+#1#{}倍數",
},
},
["j_splash"]={
["name"]="水花噴濺",
["text"]={
[1]="每張{C:attention}打出的牌",
[2]="都會計分",
},
},
["j_sock_and_buskin"]={
["unlock"]={
[1]="總共打出",
[2]="{C:attention,E:1}#1#{}張花牌",
[3]="{C:inactive}(#2#)",
},
["name"]="花牌小丑",
["text"]={
[1]="重新觸發全部",
[2]="打出的{C:attention}花牌{}",
},
},
["j_rough_gem"]={
["unlock"]={
[1]="手上的牌至少要有{E:1,C:attention}#1#",
[2]="{E:1,C:attention}#2#",
[3]="花色",
},
["name"]="原礦",
["text"]={
[1]="只要每次打出",
[2]="{C:diamonds}方塊{}花色牌，",
[3]="得分時{C:money}$#1#{}",
},
},
["j_banner"]={
["name"]="旗幟",
["text"]={
[1]="每一個剩餘的",
[2]="{C:attention}棄牌{}次數可獲得",
[3]="{C:chips}+#1#{}籌碼",
},
},
["j_8_ball"]={
["name"]="八號球",
["text"]={
[1]="每打出{C:attenetion}#1#{}張",
[2]="或更多張數字{C:attention}8{}，",
[3]="獲得一張{C:planet}行星牌{}",
[4]="{C:inactive}(必須有空位)",
},
},
["j_hallucination"]={
["name"]="產生幻覺",
["text"]={
[1]="當開啟任一{C:attention}擴充包{}時，",
[2]="有{C:green}#1#/#2#{}的機會",
[3]="產生一張{C:tarot}塔羅牌{}",
[4]="{C:inactive}(必須有空位)",
},
},
["j_trading"]={
["name"]="交換卡",
["text"]={
[1]="每回合的{C:attention}第一次棄牌{}",
[2]="如果只有棄{C:attention}1{}張牌",
[3]="摧毀那張牌並獲得{C:money}$#1#",
},
},
["j_mad"]={
["name"]="生氣小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#{}，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_abstract"]={
["name"]="抽象小丑",
["text"]={
[1]="每張{C:attention}小丑牌{}",
[2]="{C:mult}+#1#{}倍數",
[3]="{C:inactive}(目前為{C:red}+#2#{C:inactive}倍)",
},
},
["j_odd_todd"]={
["name"]="古怪托德",
["text"]={
[1]="每打出一張計分的",
[2]="{C:attention}奇數{}點的牌，",
[3]="得分時，{C:chips}+#1#{}籌碼",
[4]="{C:inactive}(A、9、7、5、3)",
},
},
["j_riff_raff"]={
["name"]="即興演出",
["text"]={
[1]="每當選擇{C:attention}盲注{}時",
[2]="其會產生{C:attention}#1#張{C:blue}一般{C:attention}小丑牌",
[3]="{C:inactive}(必須有空位)",
},
},
["j_superposition"]={
["name"]="完美位置",
["text"]={
[1]="如果計分手牌包含",
[2]="一張{C:attention}A{}及{C:attention}順子{}",
[3]="即產生一張{C:tarot}塔羅牌{}",
[4]="{C:inactive}(必須有空位)",
},
},
["j_to_the_moon"]={
["name"]="登月",
["text"]={
[1]="每回合結束時，",
[2]="每擁有{C:money}$5{}，",
[3]="皆可獲得額外{C:money}$#1#{}利息",
},
},
["j_stuntman"]={
["unlock"]={
[1]="在一手牌中",
[2]="至少獲得",
[3]="{E:1,C:attention}#1#{}籌碼",
},
["name"]="特技演員",
["text"]={
[1]="{C:chips}+#1#{}籌碼",
[2]="{C:attention}-#2#{}手牌大小",
},
},
["j_satellite"]={
["unlock"]={
[1]="得到{E:1,C:money}$#1#",
[2]="或更多",
},
["name"]="衛星",
["text"]={
[1]="本赛局每使用一張",
[2]="{C:planet}行星牌{}，每回合結束時",
[3]="可得到{C:money}$#1#{}",
[4]="{C:inactive}(目前為{C:money}$#2#{C:inactive})",
},
},
["j_todo_list"]={
["name"]="待辦事項",
["text"]={
[1]="如果{C:attention}出牌牌型{}為{C:attention}#2#{}，",
[2]="獲得{C:money}$#1#{}",
[3]="每次支付時",
[4]="牌型都會改變",
},
},
["j_constellation"]={
["name"]="星空小丑",
["text"]={
[1]="每張已使用的{C:planet}行星牌{}",
[2]="可獲得{X:mult,C:white}X#1#{}倍數",
[3]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_selzer"]={
["name"]="氣泡水",
["text"]={
[1]="未來{C:attention}#1#{}次出牌",
[2]="重新觸發所有",
[3]="打出的牌",
},
},
["j_stone"]={
["name"]="石頭小丑",
["text"]={
[1]="為牌組內的",
[2]="每張{C:attention}石頭牌{}",
[3]="{C:chips}+#1#{}籌碼",
[4]="{C:inactive}(目前為{C:chips}+#2#{C:inactive}籌碼)",
},
},
["j_raised_fist"]={
["name"]="致勝之拳",
["text"]={
[1]="將手牌中的{C:attention}最小{}牌的",
[2]="點數{C:attention}翻倍{}",
[3]="加到倍數中",
},
},
["j_marble"]={
["name"]="大理石小丑",
["text"]={
[1]="每次選完{C:attention}盲注{}，",
[2]="增加1張{C:attention}石頭牌{}",
[3]="到牌組中",
},
},
["j_bull"]={
["name"]="鬥牛",
["text"]={
[1]="每擁有{C:money}$1{}",
[2]="{C:chips}+#1#{}籌碼",
[3]="{C:inactive}(目前為{C:chips}+#2#{C:inactive}籌碼)",
},
},
["j_dna"]={
["name"]="DNA",
["text"]={
[1]="如果一回合的{C:attention}第一次出牌{}",
[2]="只有出{C:attention}1{}張牌",
[3]="將永久複製{C:attention}那張牌{}到牌組",
[4]="並放到{C:attention}手牌{}",
},
},
["j_zany"]={
["name"]="滑稽小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#{}，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_acrobat"]={
["unlock"]={
[1]="打{C:attention,E:1}#1#{}手牌",
[2]="{C:inactive}(#2#)",
},
["name"]="雜技演員",
["text"]={
[1]="每回合{C:attention}最後一次{C:attention}出牌{}",
[2]="可得到{X:red,C:white}X#1#{}倍數",
},
},
["j_photograph"]={
["name"]="攝影",
["text"]={
[1]="出牌時",
[2]="第一張記分的{C:attention}花牌{}",
[3]="獲得{X:mult,C:white}X#1#{}倍數",
},
},
["j_order"]={
["unlock"]={
[1]="贏得比賽",
[2]="且沒有打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="順子",
["text"]={
[1]="如果打出的牌",
[2]="包含{C:attention}#2#{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_burnt"]={
["unlock"]={
[1]="共賣出",
[2]="{E:1,C:attention}#1#{}牌",
[3]="{C:inactive}(#2#)",
},
["name"]="累爆小丑",
["text"]={
[1]="升級",
[2]="每回合中",
[3]="第一次{C:attention}棄牌的牌型",
},
},
["j_hack"]={
["name"]="爛脫口秀演員",
["text"]={
[1]="重新觸發",
[2]="所有打出的",
[3]="{C:attention}2{}、{C:attention}3{}、{C:attention}4{}、或{C:attention}5{}",
},
},
["j_swashbuckler"]={
["unlock"]={
[1]="賣出總共",
[2]="{C:attention,E:1}#1#{}張小丑牌",
[3]="{C:inactive}(#2#)張",
},
["name"]="盜賊小丑",
["text"]={
[1]="將這張卡左邊所有",
[2]="{C:attention}小丑牌{}的總售價",
[3]="增加至倍數",
[4]="{C:inactive}(目前為{C:mult}+#1#{C:inactive}倍)",
},
},
["j_scary_face"]={
["name"]="駭人的臉",
["text"]={
[1]="打出{C:attention}花牌{}時，",
[2]="得分時",
[3]="給予{C:chips}+#1#{}",
},
},
["j_popcorn"]={
["name"]="爆米花",
["text"]={
[1]="{C:mult}+#1#{}倍數，",
[2]="每結束一回合",
[3]="{C:mult}-#2#{}倍數",
},
},
["j_caino"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="白臉小丑",
["text"]={
[1]="每張{C:attention}花牌{}被摧毀時",
[2]="永久獲得",
[3]="{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_hanging_chad"]={
["unlock"]={
[1]="贏得Boss盲注",
[2]="使用的是{E:1,C:attention}#1#",
},
["name"]="懸孔票",
["text"]={
[1]="重新觸發{C:attention}第一張{}打出的",
[2]="記入計分的牌",
},
},
["j_crazy"]={
["name"]="瘋狂小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#{}，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_vampire"]={
["name"]="吸血鬼小丑",
["text"]={
[1]="每次打出{C:attention}加強牌{}，",
[2]="移除牌卡{C:attention}加強效果",
[3]="並獲得{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_tribe"]={
["unlock"]={
[1]="贏得比賽",
[2]="且沒有打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="同花",
["text"]={
[1]="如果打出的牌",
[2]="包含{C:attention}#2#{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_smeared"]={
["unlock"]={
[1]="手上的牌至少要有{C:attention}#1#",
[2]="{E:1,C:attention}#2#{}",
[3]="出現",
},
["name"]="歪臉小丑",
["text"]={
[1]="{C:hearts}紅心{}和{C:diamonds}方塊",
[2]="視為相同花色，",
[3]="{C:spades}黑桃{}和{C:clubs}梅花",
[4]="視為相同花色",
},
},
["j_jolly"]={
["name"]="開心小丑",
["text"]={
[1]="如果打出的牌包含",
[2]="{C:attention}#2#{}，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_brainstorm"]={
["unlock"]={
[1]="丟棄",
[2]="{E:1,C:attention}皇家同花順",
},
["name"]="腦力激盪",
["text"]={
[1]="複製",
[2]="最左邊{C:attention}小丑牌的能力",
},
},
["j_bloodstone"]={
["unlock"]={
[1]="手上的牌至少要有{E:1,C:attention}#1#",
[2]="{E:1,C:attention}#2#",
[3]="花色",
},
["name"]="血石",
["text"]={
[1]="每次打出的",
[2]="{C:hearts}紅心{}花色牌",
[3]="有{C:green}#1#/#2#{}的機率",
[4]="獲得{X:mult,C:white}X#3#{}倍數",
},
},
["j_ticket"]={
["unlock"]={
[1]="打出5張手牌，",
[2]="其中只包含 ",
[3]="{C:attention,E:1}黃金牌{}",
},
["name"]="黃金門票",
["text"]={
[1]="若打出{C:money}黃金牌{}，",
[2]="得分時，{C:money}$#1#{}",
},
},
["j_seeing_double"]={
["unlock"]={
[1]="打一手",
[2]="要包含",
[3]="{E:1,C:attention}#1#的牌",
},
["name"]="幻視",
["text"]={
[1]="如果出牌中有計分的牌",
[2]="包含{C:clubs}梅花{}和",
[3]="其他任意{C:attention}花色{}，",
[4]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_ring_master"]={
["unlock"]={
[1]="達到底注",
[2]="級別{E:1,C:attention}#1#",
},
["name"]="馬戲王小丑",
["text"]={
[1]="{C:attention}小丑牌{}、{C:tarot}塔羅牌{}、{C:planet}行星牌{}和",
[2]="{C:spectral}幻靈牌{}會在商店出現",
[3]="多次",
},
},
["j_stencil"]={
["name"]="模具小丑",
["text"]={
[1]="每個空的{C:attention}小丑牌{}欄位",
[2]="獲得{X:red,C:white}X#1#{}倍數。",
[3]="包含{s:0.8}模具小丑",
[4]="{C:inactive}(目前為{X:red,C:white}X#1#{C:inactive})",
},
},
["j_oops"]={
["unlock"]={
[1]="在一手牌中",
[2]="得到最少",
[3]="{E:1,C:attention}#1#{}籌碼",
},
["name"]="六六大順",
["text"]={
[1]="所有{C:attention}機率牌{}的",
[2]="{C:green,E:1,S:1.1}機率加倍",
[3]="{C:inactive}(例：{C:green}1/3{C:inactive} -> {C:green}2/3{C:inactive})",
},
},
["j_madness"]={
["name"]="瘋狂小丑",
["text"]={
[1]="在{C:attention}盲注{}選擇後，",
[2]="獲得{X:mult,C:white}X#1#{}倍數並",
[3]="{C:attention}摧毀{}隨機一張小丑牌",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{}倍)",
},
},
["j_family"]={
["unlock"]={
[1]="贏得比賽",
[2]="且沒有打出",
[3]="{E:1,C:attention}#1#",
},
["name"]="鐵支",
["text"]={
[1]="如果打出的牌",
[2]="包含{C:attention}#2#{}，",
[3]="{X:mult,C:white}X#1#{}倍數",
},
},
["j_bootstraps"]={
["unlock"]={
[1]="手上的牌至少要有{E:1,C:attention}#1#",
[2]="{C:dark_edition}彩色{}小丑",
},
["name"]="拔靴帶",
["text"]={
[1]="每擁有{C:money}$#2#{}，",
[2]="{C:mult}+#1#{}倍數",
},
},
["j_juggler"]={
["name"]="雜耍小丑",
["text"]={
[1]="{C:attention}+#1#{}手牌大小",
},
},
["j_dusk"]={
["name"]="夕陽卡",
["text"]={
[1]="在{C:attention}最後{}",
[2]="{C:attention}一次出牌{}時，",
[3]="該手牌會被觸發兩次",
},
},
["j_vagabond"]={
["name"]="流浪者",
["text"]={
[1]="若在出牌時當下",
[2]="擁有{C:money}$#1#{}或更少的金錢",
[3]="產生一張{C:purple}塔羅牌{}",
},
},
["j_wee"]={
["unlock"]={
[1]="在{E:1,C:attention}#1#回合或",
[2]="或更少的回合數下勝出",
},
["name"]="小小丑",
["text"]={
[1]="每打出一張數字{C:attention}2{}並得分時",
[2]="這張小丑牌",
[3]="永久獲得{C:chips}+#2#{}籌碼",
[4]="{C:inactive}(目前為{C:chips}+#1#{C:inactive}籌碼)",
},
},
["j_matador"]={
["unlock"]={
[1]="在{E:1,C:attention}一手之内{}且没有",
[2]="且不使用棄牌次數",
[3]="戰勝Boss盲注",
},
["name"]="鬥牛小丑",
["text"]={
[1]="如果打出的牌觸發",
[2]="{C:attention}Boss盲注{}的限制條件，",
[3]="獲得{C:money}$#1#{}",
},
},
["j_campfire"]={
["name"]="營火",
["text"]={
[1]="每{C:attention}賣出{}一張牌卡",
[2]="此小丑獲得{X:mult,C:white}X#1#{}倍數，",
[3]="每戰勝{C:attention}Boss盲注{}時重置",
[4]="{C:inactive}(目前為{X:mult,C:white}X#2#{C:inactive}倍)",
},
},
["j_idol"]={
["unlock"]={
[1]="在一手牌中",
[2]="得到最少",
[3]="{E:1,C:attention}#1#{}籌碼",
},
["name"]="偶像小丑",
["text"]={
[1]="打出每張{V:1}#3#{}花色的",
[2]="{C:attention}#2#{}在得分時",
[3]="{X:mult,C:white}X#1#{}倍數",
[4]="{s:0.8}每個回合牌都會變",
},
},
["j_lusty_joker"]={
["name"]="好色小丑",
["text"]={
[1]="每打出一張",
[2]="{C:hearts}#2#{}花色的牌，",
[3]="倍數{C:red}+#1#{}",
},
},
["j_sixth_sense"]={
["name"]="第六感",
["text"]={
[1]="如果回合第一次出牌為",
[2]="單張數字{C:attention}6{}，將銷毀那張牌並且",
[3]="產生一張隨機的{C:spectral}幻靈牌{}",
[4]="{C:inactive}(必須有空位)",
},
},
["j_certificate"]={
["unlock"]={
[1]="擁有一張",
[2]="帶有{C:attention,E:1}金色封蠟章",
[3]="的黃金牌",
},
["name"]="證書",
["text"]={
[1]="每回合開始時",
[2]="隨機增加一張",
[3]="帶有隨機{C:attention}封蠟章{}的",
[4]="牌到手牌中",
},
},
["j_ice_cream"]={
["name"]="冰淇淋",
["text"]={
[1]="{C:chips}+#1#{}籌碼，",
[2]="每次出牌",
[3]="{C:chips}-#2#{}籌碼",
},
},
["j_misprint"]={
["name"]="印錯小丑",
["text"]={
[1]="",
},
},
["j_turtle_bean"]={
["name"]="烏龜豆",
["text"]={
[1]="手牌大小{C:attention}+#1#{}",
[2]="每一回合",
[3]="減少{C:red}#2#{}",
},
},
["j_blackboard"]={
["name"]="黑板小丑",
["text"]={
[1]="如果手牌中未打出的牌",
[2]="都是{C:spades}#2#{}或{C:clubs}#3#{}，",
[3]="倍數{X:red,C:white}X#1#{}",
},
},
["j_fortune_teller"]={
["name"]="占卜師小丑",
["text"]={
[1]="本賽局每使用一張{C:purple}塔羅牌{}時",
[2]="倍數{C:red}+#1#{}",
[3]="{C:inactive}(目前為{C:red}+#2#{C:inactive})",
},
},
["j_drivers_license"]={
["unlock"]={
[1]="在你的牌組中",
[2]="加強{E:1,C:attention}#1#{}張牌",
},
["name"]="駕照",
["text"]={
[1]="如果手上的牌至少有{C:attention}16",
[2]="張加強牌",
[3]="{X:mult,C:white}X#1#{}倍數",
[4]="{C:inactive}(目前為{C:attention}#2#{C:inactive})",
},
},
["j_chicot"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="奇科特",
["text"]={
[1]="每個{C:attention}Boss盲注",
[2]="限制條件消失",
},
},
["j_yorick"]={
["unlock"]={
[1]="{E:1,s:1.3}?????",
},
["name"]="約里克",
["text"]={
[1]="使用{C:attention}#2#{}次棄牌後",
[2]="獲得{X:mult,C:white}X#1#{}倍數",
[3]="{C:inactive}(剩下棄牌數：{C:attention}#3#{C:inactive})",
},
},
["j_business"]={
["name"]="名片",
["text"]={
[1]="打出的{C:attention}花牌{}有",
[2]="{C:green}#1#/#2#{}的機率",
[3]="在得分時獲得{C:money}$2{}",
},
},
["j_cartomancer"]={
["unlock"]={
[1]="發現每張",
[2]="{E:1,C:attention}#1#{C:tarot}塔羅牌{}",
},
["name"]="卜卦小丑",
["text"]={
[1]="在選了{C:attention}盲注{}後",
[2]="產生一張{C:tarot}塔羅牌{}",
[3]="{C:inactive}(必須有空位)",
},
},
["j_fibonacci"]={
["name"]="黃金分割數",
["text"]={
[1]="每次打出{C:attention}A{}、",
[2]="{C:attention}2{}、{C:attention}3{}、{C:attention}5{}、或{C:attention}8{}時，",
[3]="得分時{C:mult}+#1#{}倍數",
},
},
["j_faceless"]={
["name"]="無臉小丑",
["text"]={
[1]="如果同時捨棄",
[2]="{C:attention}#2#{}張或更多張",
[3]="{C:attention}花牌{}",
[4]="獲得{C:money}$#1#{}",
},
},
},
["Spectral"]={
["c_soul"]={
["name"]="靈魂",
["text"]={
[1]="產生一張",
[2]="{C:legendary,E:1}傳奇{}小丑牌",
[3]="{C:inactive}(必須有空位)",
},
},
["c_cryptid"]={
["name"]="傳說動物",
["text"]={
[1]="選擇{C:attention}1{}張手牌",
[2]="建立{C:attention}#1#{}張",
[3]="選定牌的複製牌",
},
},
["c_trance"]={
["name"]="入迷",
["text"]={
[1]="新增一個{C:blue}藍色封蠟章{}",
[2]="至{C:attention}1{}張",
[3]="選擇的手牌中",
},
},
["c_medium"]={
["name"]="靈媒",
["text"]={
[1]="新增一個{C:purple}紫色封蠟章{}",
[2]="至{C:attention}1{}張",
[3]="選擇的手牌中",
},
},
["c_deja_vu"]={
["name"]="既視感",
["text"]={
[1]="新增一個{C:red}紅色封蠟章{}",
[2]="至{C:attention}1{}張",
[3]="選擇的手牌中",
},
},
["c_ectoplasm"]={
["name"]="靈質",
["text"]={
[1]="新增{C:dark_edition}負片{}效果到",
[2]="一張隨機的{C:attention}小丑牌，",
[3]="{C:red}-1{}的手牌大小",
},
},
["c_familiar"]={
["name"]="熟悉",
["text"]={
[1]="摧毀隨機{C:attention}1{}張手牌，",
[2]="再新增{C:attention}#1#{}張",
[3]="隨機{C:attention}加強花牌{}",
[4]="到手牌中",
},
},
["c_immolate"]={
["name"]="犧牲",
["text"]={
[1]="隨機摧毀",
[2]="{C:attention}#1#{}張手牌",
[3]="獲得{C:money}$#2#",
},
},
["c_grim"]={
["name"]="無情",
["text"]={
[1]="摧毀手上隨機{C:attention}1{}張牌",
[2]="再新增{C:attention}#1#{}張",
[3]="{C:attention}加強版A{}",
[4]="到手牌中",
},
},
["c_aura"]={
["name"]="光環",
["text"]={
[1]="新增{C:dark_edition}銀箔{}、{C:dark_edition}全像攝影{}，",
[2]="或{C:dark_edition}彩色{}效果到",
[3]="{C:attention}1{}張選定的手牌中",
},
},
["c_ouija"]={
["name"]="占卜板",
["text"]={
[1]="轉換手牌中",
[2]="所有牌卡成一種",
[3]="隨機{C:attention}點數",
[4]="{C:red}-1{}手牌大小",
},
},
["c_talisman"]={
["name"]="護身符",
["text"]={
[1]="新增{C:attention}金色封蠟章{}",
[2]="到選擇的{C:attention}1{}張",
[3]="手牌中",
},
},
["c_wraith"]={
["name"]="幻影",
["text"]={
[1]="產生一張隨機的",
[2]="{C:red}稀有{C:attention}小丑牌{}，",
[3]="設定金額至{C:money}$0",
},
},
["c_ankh"]={
["name"]="安卡",
["text"]={
[1]="隨機複製一張",
[2]="擁有的{C:attention}小丑牌{}",
[3]="並摧毀其它小丑牌",
},
},
["c_sigil"]={
["name"]="魔符",
["text"]={
[1]="轉換手牌中",
[2]="所有牌卡成一種",
[3]="隨機{C:attention}花色",
},
},
["c_hex"]={
["name"]="妖術",
["text"]={
[1]="新增{C:dark_edition}彩色{}效果至",
[2]="一個隨機{C:attention}小丑牌{}，",
[3]="並摧毀其它小丑牌",
},
},
["c_incantation"]={
["name"]="咒語",
["text"]={
[1]="摧毀手上隨機{C:attention}1{}張牌",
[2]="再新增{C:attention}#1#{}張",
[3]="{C:attention}加強版數字牌{}",
[4]="到手牌中",
},
},
["c_black_hole"]={
["name"]="黑洞",
["text"]={
[1]="升級每個",
[2]="{C:legendary,E:1}牌型",
[3]="{C:attention}1{}個等級",
},
},
},
},
["UI"]={
},
["misc"]={
["suits_singular"]={
["Spades"]="黑桃",
["Hearts"]="紅心",
["Diamonds"]="方塊",
["Clubs"]="梅花",
},
["v_text"]={
["ch_c_inflation"]={
[1]="每次選購永久提高價格{C:money}$1{}",
},
["ch_m_hand_size"]={
[1]="{C:attention}#1#{}手牌大小",
},
["ch_c_discard_cost"]={
[1]="每次棄牌支付{C:money}$#1#{}",
},
["ch_c_none"]={
[1]="{C:inactive}無",
},
["ch_m_reroll_cost"]={
[1]="{C:money}$#1#{}重摋基本費用",
},
["ch_c_no_reward"]={
[1]="所有{C:attention}盲注{}均沒有獎勵金",
},
["ch_c_no_reward_specific"]={
[1]="{C:attention}#1#盲注{}均沒有獎勵金",
},
["ch_m_none"]={
[1]="{C:inactive}無",
},
["ch_c_set_seed"]={
[1]="嘗試設定種子1次：{C:inactive}{隱藏}",
},
["ch_c_no_interest"]={
[1]="每一回合結束時無法獲得{C:attention}利息{}",
},
["ch_c_chips_dollar_cap"]={
[1]="{C:blue}籌碼{}不能超過目前的{C:money}$",
},
["ch_m_dollars"]={
[1]="從{C:money}$#1#開始玩",
},
["ch_c_flipped_cards"]={
[1]="每{C:green}#1#{}張牌中有1張會是面朝下抽出",
},
["ch_c_minus_hand_size_per_X_dollar"]={
[1]="每擁有{C:money}$#1#{}，就{C:red}-1{}張能持有的手牌",
},
["ch_m_discards"]={
[1]="每回合{C:red}-#1#{}棄牌次數",
},
["ch_c_no_shop_jokers"]={
[1]="{C:attention}商店{}中不再出現小丑牌",
},
["ch_c_daily"]={
[1]="{E:1,s:1.2,C:red}每日挑戰！",
},
["ch_m_hands"]={
[1]="每回合{C:blue}#1#{}出牌次數",
},
["ch_m_consumable_slots"]={
[1]="{C:attention}#1#{}消耗牌欄位",
},
["ch_c_set_joker_slots_ante"]={
[1]="當{C:attention}#1#{}Boss盲注被擊敗後，將小丑牌欄位數變為{C:attention}0",
},
["ch_c_set_eternal_ante"]={
[1]="當{C:attention}#1#{}Boss盲注被擊敗後，所有的小丑牌都會成為{C:attention}永恆狀態",
},
["ch_c_no_extra_hand_money"]={
[1]="額外{C:blue}手牌{}無法再獲得資金",
},
["ch_c_debuff_played_cards"]={
[1]="所有{C:attention}打出過的{}牌在計分後會遭到{C:attention}減益{}",
},
["ch_m_joker_slots"]={
[1]="{C:attention}#1#{}小丑牌欄位",
},
["ch_c_all_eternal"]={
[1]="所有商店內小丑都是{C:eternal}永恆的{}",
},
},
["quips"]={
["wq_4"]={
[1]="這些籌碼",
[2]="要是都是真錢",
[3]="該有多好啊……",
},
["lq_10"]={
[1]="真是糗到不行！",
},
["lq_6"]={
[1]="天啊，難到",
[2]="你也是在吹牛？",
},
["lq_7"]={
[1]="沒想到",
[2]="我們讓人看笑話了！",
},
["wq_3"]={
[1]="看來",
[2]="你不是在吹牛！",
},
["wq_1"]={
[1]="你的表現超出色！",
},
["lq_5"]={
[1]="看來",
[2]="我們找到",
[3]="誰才是真正的「小丑」了！",
},
["wq_2"]={
[1]="你超讚",
[2]="很棒呢！",
},
["lq_9"]={
[1]="我是",
[2]="真的傻，但你",
[3]="的藉口是什麼？",
},
["dq_1"]={
[1]="唉！我希望",
[2]="你有什麼妙計",
[3]="能應付這",
[4]="最後的挑戰！",
},
["lq_4"]={
[1]="人家不是常說那句話嗎？",
[2]="就是",
[3]="贏的永遠是莊家！",
},
["lq_8"]={
[1]="這種情況，",
[2]="只要有手的人都想",
[3]="把眼睛遮起來吧！",
},
["lq_1"]={
[1]="感覺",
[2]="我們更適合玩",
[3]="Go Fish……",
},
["wq_7"]={
[1]="幸好",
[2]="我不打賭",
[3]="不是你！",
},
["lq_2"]={
[1]="我們放棄得",
[2]="有點輕易欸！",
},
["lq_3"]={
[1]="是時候該",
[2]="重新洗牌",
[3]="然後重新開局了！",
},
["wq_5"]={
[1]="看來我已",
[2]="我把你教得很好嘛！",
},
["wq_6"]={
[1]="你的決策",
[2]="非常明智！",
},
},
["achievement_descriptions"]={
["speedrunner"]="在12回合以內贏得比賽",
["card_player"]="打出至少2500張牌",
["extreme_couponer"]="找到所有禮券",
["heads_up"]="贏得比賽",
["retrograde"]="將任一手牌提升至等級10",
["shattered"]="在單一手牌中破壞2玻璃牌",
["completionist_plus_plus"]="每張小丑牌都獲得金色貼紙",
["nest_egg"]="在單一回合中擁有$400以上",
["roi"]="在底注4的遊戲中購買5禮券",
["royale"]="打出同花大順",
["tiny_hands"]="將你的牌組縮減至20張或以下",
["_100000k"]="在單一手牌中獲得100,000,000籌碼",
["cartomancy"]="找到所有塔羅牌",
["rule_breaker"]="完成所有挑戰賽",
["flushed"]="用5張萬能牌打出一次同花",
["mid_stakes"]="至少在藍色賭注難度贏得比賽",
["completionist"]="找到100%個人收藏牌卡",
["low_stakes"]="至少在紅色賭注難度贏得比賽",
["_1000k"]="在單一手牌中獲得1,000,000籌碼",
["ante_upper"]="達到底注8",
["astronomy"]="找到所有行星牌",
["big_hands"]="牌組中擁有80張以上牌卡",
["card_discarder"]="丟棄至少2500張牌",
["completionist_plus"]="在金色賭注難度中，使用每副牌組贏得勝利",
["legendary"]="找到傳奇小丑",
["rule_bender"]="完成任一挑戰賽",
["_10k"]="在單一手牌中獲得10,000籌碼",
["high_stakes"]="至少在金色賭注難度贏得比賽",
["clairvoyance"]="找到所有幻靈牌",
["ante_up"]="達到底注4",
["you_get_what_you_get"]="在不使用商店重開牌的情況下贏得比賽",
},
["poker_hands"]={
["Flush House"]="同花葫蘆",
["Full House"]="葫蘆",
["Flush"]="同花",
["Pair"]="對子",
["Four of a Kind"]="四條",
["Royal Flush"]="皇家同花順",
["Straight Flush"]="同花順",
["Straight"]="順子",
["Five of a Kind"]="五條",
["Flush Five"]="同花五條",
["Two Pair"]="兩對",
["Three of a Kind"]="三條",
["High Card"]="高牌",
},
["blind_states"]={
["Defeated"]="已被擊敗",
["Upcoming"]="下一回合",
["Current"]="目前",
["Selected"]="已選擇",
["Select"]="選擇",
["Skipped"]="跳過",
},
["dictionary"]={
["b_credits"]="製作人員",
["b_set_rumble"]="控制器振動",
["b_play_cap"]="開始遊戲",
["ph_no_boss_active"]="無使用中的好牌",
["k_skipped_cap"]="已跳過",
["b_high_contrast_cards"]="高對比牌",
["b_set_play_discard_pos"]="出牌/棄牌按鈕位置",
["k_playing_as"]="角色名稱",
["k_unlocked_ex"]="已解鎖！",
["k_reroll"]="重開牌",
["b_music"]="音樂",
["ml_play_discard_pos_opt"]={
[1]="棄牌/出牌",
[2]="出牌/棄牌",
},
["b_set_video"]="影像",
["b_restrictions"]="限制",
["b_jokers"]="小丑",
["k_copied_ex"]="已複製！",
["b_set_graphics"]="圖像",
["ph_blind_score_at_least"]="至少得分",
["b_copy"]="複製",
["k_collection"]="收藏",
["k_choose"]="選擇",
["b_rules"]="規則",
["k_lower_score"]="分數",
["b_stat_jokers"]="小丑",
["k_x_base"]="X基本",
["b_run_info_1"]="比賽",
["k_rare"]="稀有",
["ph_click_confirm"]="再按一下即可確認",
["b_options"]="選項",
["b_stat_vouchers"]="禮券",
["k_money"]="資金",
["b_stats"]="統計數據",
["k_stake"]="賭注",
["b_set_screenshake"]="螢幕抖動",
["ph_demo_thanks_2"]="BALATRO試玩版",
["b_stat_tarots"]="塔羅牌",
["ml_unlock_all_trophies"]={
[1]="警告！解鎖完整收藏",
[2]="將停用此個人檔案的獎盃！",
},
["k_dwarf_planet"]="矮行星",
["b_stake"]="賭注",
["k_wins"]="獲勝數",
["ph_unscored_hand"]="出牌將不會得分",
["k_ante_cap"]="底注",
["b_set_monitor"]="顯示螢幕",
["k_arcana_pack"]="奧秘禮包",
["ph_defeat_this_blind_1"]="戰勝盲注",
["ph_no_vouchers"]="本賽局沒有兌換禮券",
["k_upgrade_ex"]="升級！",
["k_plus_spectral"]="+1幻靈牌",
["ml_unlock_all_explanation"]={
[1]="警告！解鎖完整收藏",
[2]="將禁用此個人檔案的成就！",
},
["b_redeem"]="兌換",
["b_next_round_2"]="回合",
["k_swapped_ex"]="已切換！",
["b_back"]="返回",
["k_base_cap"]="基本",
["ph_up_ante_2"]="提高所有盲注",
["k_game_modifiers"]="遊戲修改者",
["b_create_profile"]="建立個人檔案",
["b_copy_seed"]="複製種子",
["b_new_challenge"]="開始新挑戰",
["k_plus_planet"]="+1行星牌",
["b_tarot_cards"]="塔羅牌",
["b_challenges"]="挑戰",
["b_delete_profile"]="刪除個人檔案",
["k_ante"]="底注",
["ph_score_furthest_round"]="回合",
["k_vouchers_cap"]="禮券",
["b_main_menu"]="主選單",
["b_vouchers"]="禮券",
["k_val_up"]="提高價值！",
["b_set_apply"]="套用",
["ml_smoothing_opt"]={
[1]="關閉",
[2]="開啟",
},
["k_achievement"]="成就",
["b_use"]="使用",
["k_deck_stake_wins"]="牌組賭注完成度",
["$"]="$",
["b_set_master_vol"]="主音量",
["k_challenges"]="挑戰",
["k_base_cards"]="基本牌卡",
["b_set_shadows"]="陰影",
["k_undisovered"]="未發現",
["ml_edition_seal_enhancement_explanation"]={
[1]="每張遊戲牌可能會有",
[2]="加強、版本與封蠟章版本",
},
["b_stat_consumables"]="消耗牌",
["b_buy"]="購買",
["k_page"]="頁",
["k_defeated_by"]="擊敗",
["k_high_score_ex"]="高分！",
["ph_vouchers_redeemed"]="本賽局兌換的禮券",
["ml_vsync_opt"]={
[1]="垂直同步開啟",
[2]="垂直同步關閉",
},
["ph_score_cards_purchased"]="已選購的牌",
["k_enter_seed"]="進入種子",
["k_incompatible"]="不相容",
["b_options_cap"]="選項",
["b_set_CRT"]="CRT",
["k_no_reward"]="無獎勵",
["b_cash_out"]="兌現",
["k_spectral"]="幻靈",
["ml_eternal"]={
[1]="永恆",
[2]="不能賣出",
[3]="或催毀",
},
["b_unlock_all"]="解鎖全部",
["k_legendary"]="傳奇",
["b_skip_reward"]="跳過獎勵",
["k_rank"]="點數",
["b_set_windowmode"]="視窗模式",
["ph_boss_disabled"]="Boss盲注限制條件失效",
["b_decks"]="牌組",
["ph_deck_preview_effective"]="因小丑、盲注和卡牌增強而產生的有效總數量",
["k_trophies_disabled"]="獎盃停用",
["b_open"]="打開",
["b_set_CRT_bloom"]="模擬CRT螢光效果",
["k_aces"]="A",
["k_banned_cards"]="禁卡",
["k_trophy"]="獎盃",
["b_select"]="選擇",
["ph_score_at_least"]="分數最少",
["k_compatible"]="相容",
["k_tarot"]="塔羅牌",
["k_active"]="使用中",
["k_buffoon_pack"]="丑角禮包",
["b_booster_packs"]="擴充包",
["ph_choose_blind_1"]="選擇您的",
["k_card_stats"]="牌卡統計數據",
["k_nope_ex"]="不！",
["k_unknown"]="?????",
["k_seeded_run"]="種子比賽",
["k_hud_discards"]="棄牌",
["k_enter_text"]="輸入文字",
["ml_gold_seal_desc"]={
[1]="金色封蠟章",
[2]="重返手上",
[3]="白貼紙時",
},
["k_no_space_ex"]="沒有空間！",
["ph_score_hand"]="最好的一手",
["k_joker_stickers"]="小丑貼紙",
["k_other"]="其他",
["b_discard"]="棄牌",
["ph_game_over"]="遊戲結束",
["ph_defeat_this_blind_2"]="發現它",
["k_spectral_pack"]="幻靈禮包",
["ph_you_win_demo"]="你在試玩版中獲勝了！",
["b_enhanced_cards"]="加強牌",
["k_redeemed_ex"]="已兌換！",
["k_round"]="回合",
["b_run_info_2"]="資訊",
["k_mult"]="倍數",
["k_challenge_mode"]="挑戰模式",
["k_face_cards"]="花牌",
["b_next"]="下一個",
["b_new_run"]="新一回合",
["k_plus_tarot"]="+1塔羅牌",
["k_reward"]="獎勵",
["k_level_prefix"]="等級",
["ph_1_level"]="+1級",
["b_load_profile"]="載入個人檔案",
["ml_shadow_opt"]={
[1]="開啟",
[2]="關閉",
},
["k_debuffed"]="遭減益",
["k_joker"]="小丑",
["ph_score_new_collection"]="新發現",
["k_planet_q"]="行星?",
["ph_score_poker_hand"]="玩得最多的一局",
["b_next_round_1"]="下一個",
["ph_score_furthest_ante"]="底注",
["ph_up_ante_3"]="重洗盲注",
["b_imagery"]="影像",
["k_lvl"]="等級",
["b_set_gamespeed"]="遊戲速度",
["k_safe_ex"]="安全！",
["b_and_use"]="和使用",
["ph_all_poker_hand"]="所有手牌",
["b_endless"]="無盡模式",
["ph_choose_blind_2"]="下一個盲注",
["b_stat_planets"]="行星牌",
["k_standard_pack"]="標準禮包",
["k_empty_caps"]="空",
["b_editions"]="版本",
["k_custom_rules"]="自訂規則",
["ph_demo_thanks_1"]="感謝您體驗",
["k_voucher"]="禮券",
["k_deck"]="牌組",
["ml_crash_report_info"]={
[1]="當機報告會送給開發商",
[2]="以協助減少未來的問題。系統並不會",
[3]="送出可識別身分的資訊或個人資料。",
},
["k_hud_hands"]="出牌",
["b_settings"]="設定",
["ph_up_ante_1"]="提高底注",
["k_no_room_ex"]="沒有空間！",
["b_reroll_boss"]="重開Boss盲注",
["b_stat_spectrals"]="幻靈牌",
["k_jokers_cap"]="小丑",
["k_plus_stone"]="+1石頭牌",
["ph_4_7_of_clubs"]="四張梅花7",
["k_active_ex"]="使用中！",
["k_suit"]="花色",
["k_locked"]="已鎖定",
["ph_blind_reward"]="獎勵：",
["ph_stat_consumable"]="這張牌卡使用過的次數",
["b_play_hand"]="出牌",
["b_playbalatro"]="造訪playbalatro.com",
["k_no_other_jokers"]="沒有其他小丑牌！",
["k_achievements_disabled"]="禁用成就",
["k_none"]="無",
["k_reset"]="重設",
["k_stake_level"]="賭注等級",
["b_collection"]="收藏",
["b_current_profile"]="目前資料",
["b_quit_cap"]="退出",
["ml_card_stats"]={
[1]="牌卡",
[2]="統計數據",
},
["b_full_deck"]="完整牌組",
["b_set_game_vol"]="遊戲音量",
["b_reset_profile"]="重設個人檔案",
["k_daily_run"]="每日比賽",
["ml_bloom_opt"]={
[1]="關閉",
[2]="開啟",
},
["b_set_crash_reports"]="當機報告",
["k_also_applied"]="也適用於",
["ph_deck_preview_stones"]="石頭",
["k_level_up_ex"]="升級！",
["k_all_hands"]="所有手牌",
["b_set_game"]="遊戲",
["b_wishlist"]="加入Steam願望清單",
["k_again_ex"]="再一次！",
["ph_you_win"]="你獲勝了！",
["k_plus_joker"]="+1小丑",
["b_remaining"]="剩下",
["k_edition"]="版本",
["ml_demo_thanks_message"]={
[1]="不妨到",
[2]="Steam將Balatro加入願望清單",
[3]="並在playbalatro.com訂閱電子報",
},
["ph_score_cards_discarded"]="丟棄的牌",
["b_sell"]="賣出",
["k_eaten_ex"]="吞噬！",
["k_drank_ex"]="大喝一口！",
["k_enter_name"]="輸入名稱",
["ph_defeat_the_boss"]="戰勝Boss盲注",
["k_extinct_ex"]="消滅了！",
["k_seed"]="種子",
["k_uncommon"]="罕見",
["k_melted_ex"]="已融化！",
["ph_stat_joker"]="這張牌卡總共完成的回合數",
["k_poker_hand"]="牌型",
["ml_disabled_seed"]={
[1]="全部解鎖及",
[2]="發現均被禁用",
},
["b_spectral_cards"]="幻靈牌",
["b_blinds"]="盲注",
["b_continue"]="繼續",
["k_banned_tags"]="禁標籤",
["b_poker_hands"]="手牌",
["k_duplicated_ex"]="複製！",
["k_profile"]="個人檔案",
["k_demo_version_ex"]="試玩版",
["k_best_hand"]="最好的一手",
["k_numbered_cards"]="數字牌",
["b_sort_hand"]="理牌",
["k_not_discovered"]="未發現",
["k_common"]="一般",
["k_planet"]="行星牌",
["ph_score_cards_played"]="打出的牌",
["b_skip_blind"]="跳過盲注",
["b_start_new_run"]="開始新的一局",
["k_effective"]="有效",
["b_sounds"]="聲音",
["b_tags"]="標籤",
["k_or"]="或",
["ph_score_times_rerolled"]="已重開時間",
["b_set_pixel_smoothing"]="像素圖像平滑",
["ph_stat_voucher"]="這張禮券兌換過的次數",
["ph_alert_debuff_confirm"]="再按一次「出牌」確認",
["k_celestial_pack"]="天外禮包",
["k_gold"]="金色",
["b_planet_cards"]="行星牌",
["k_view"]="檢視",
["ph_mr_bones"]="已被骷髏頭救出",
["ph_improve_run"]="順順手氣！",
["ml_windowmode_opt"]={
[1]="視窗模式",
[2]="全螢幕模式",
[3]="無邊界模式",
},
["ph_most_played"]="{最常出的牌型}",
["b_set_audio"]="音訊",
["b_collection_cap"]="收藏",
["b_set_music_vol"]="音樂音量",
["k_progress"]="進度",
["b_deck"]="牌組",
["b_skip"]="跳過",
["k_balanced"]="已平衡",
["ph_sneak_peek"]="先睹為快",
["ml_paste_seed"]={
[1]="貼上",
[2]="種子",
},
["b_seals"]="封蠟章",
["k_saved_ex"]="已儲存！",
["b_seed"]="種子",
["k_cap_consumables"]="消耗牌",
["k_booster"]="擴充",
["k_eroded_ex"]="侵蝕！",
},
["achievement_names"]={
["speedrunner"]="快速破關者",
["card_player"]="牌卡玩家",
["extreme_couponer"]="精打細算者",
["heads_up"]="注意",
["retrograde"]="逆行",
["shattered"]="粉碎",
["completionist_plus_plus"]="完美主義者++",
["nest_egg"]="儲備金",
["roi"]="投報率",
["royale"]="王室",
["tiny_hands"]="小手牌",
["_100000k"]="100,000K",
["cartomancy"]="卜卦",
["rule_breaker"]="規則破壞者",
["flushed"]="同花",
["mid_stakes"]="中賭注",
["completionist"]="完美主義者",
["low_stakes"]="低賭注",
["_1000k"]="1,000K",
["ante_upper"]="底注再上升！",
["astronomy"]="天文學",
["big_hands"]="大手牌",
["card_discarder"]="棄牌者",
["completionist_plus"]="完美主義者+",
["legendary"]="傳奇",
["rule_bender"]="規則突破者",
["_10k"]="10K",
["high_stakes"]="高賭注",
["clairvoyance"]="未卜先知",
["ante_up"]="底注上升！",
["you_get_what_you_get"]="接受現況",
},
["challenge_names"]={
["c_five_card_1"]="五張換牌",
["c_mad_world_1"]="瘋狂世界",
["c_monolith_1"]="巨石柱",
["c_fragile_1"]="脆弱不堪",
["c_luxury_1"]="奢侈稅",
["c_omelette_1"]="煎蛋捲",
["c_double_nothing_1"]="孤注一擲",
["c_blast_off_1"]="一飛沖天",
["c_golden_needle_1"]="黃金針",
["c_rich_1"]="富者愈富",
["c_inflation_1"]="通貨膨脹",
["c_knife_1"]="刀鋒之上",
["c_jokerless_1"]="小丑不再",
["c_non_perishable_1"]="保久物資",
["c_medusa_1"]="梅杜莎",
["c_xray_1"]="透視眼",
["c_bram_poker_1"]="布蘭撲克",
["c_city_1"]="一刻鐘城市",
["c_cruelty_1"]="殘忍無情",
["c_typecast_1"]="定型角色",
},
["v_dictionary"]={
["a_handsize"]="+#1#的手牌大小",
["loyalty_active"]="開啟！",
["deck_preview_wheel_plural"]="因#1#牌面朝下，數字可能較小",
["ante_x_voucher"]="底注#1#張禮券",
["unlocked"]="已解鎖#1#/#2#",
["ml_negative_desc"]={
[1]="負片",
[2]="+#1#小丑牌欄位",
},
["a_handsize_minus"]="-#1#手牌大小",
["a_xmult"]="X#1#倍數",
["a_mult_minus"]="-#1#倍數",
["a_xmult_minus"]="-X#1#倍數",
["a_mult"]="+#1#倍數",
["ml_negative_consumable_desc"]={
[1]="負片",
[2]="+#1#消耗牌欄位",
},
["loyalty_inactive"]="剩下#1#",
["interest"]="每$#2#獲得#1#利息(上限為#3#)",
["deck_preview_wheel_singular"]="因#1#牌面朝下，數字可能較小",
["ml_holo_desc"]={
[1]="全像攝影",
[2]="+#1#倍數",
},
["a_chips"]="+#1#",
["a_hands"]="+#1# 出牌次數",
["a_chips_minus"]="-#1#",
["ml_polychrome_desc"]={
[1]="彩色",
[2]="X#1#倍數",
},
["a_sold_tally"]="#1#/#2#賣出",
["completed"]="已完成#1#/#2#",
["remaining_discard_money"]="剩下棄牌次數(每次$#1#)",
["remaining_hand_money"]="剩下出牌次數(每次$#1#)",
["challenges_completed"]="已完成#1#/#2#個挑戰",
["ml_foil_desc"]={
[1]="銀箔",
[2]="+#1#籌碼",
},
["a_remaining"]="剩下#1#",
},
["tutorial"]={
["bb_4"]={
[1]="如果您贏了，",
[2]="{C:attention}底注{}就會增加，然後所有",
[3]="{C:attention}盲注{}都會變難",
},
["fh_4"]={
[1]="牌卡也可賺取",
[2]="{C:blue}籌碼{}，將滑鼠",
[3]="移到卡上即可查看！",
},
["fh_6"]={
[1]="您也可以{C:red}「棄牌」",
[2]="(最多選定{C:attention}5{}張牌)",
[3]="來創造更好的手牌。",
[4]="快試試看吧！",
},
["fh_1"]={
[1]="賺到籌碼，全靠",
[2]="打出{C:attention}手牌",
},
["s_5"]={
[1]="挑剔一點，",
[2]="您一次只能帶",
[3]="{C:attention}5張小丑牌{}",
},
["fh_2"]={
[1]="每次打出{C:attention}手牌{}都",
[2]="能賺取基本{C:blue}籌碼",
[3]="再透過{C:red}倍數加成",
},
["fh_3"]={
[1]="請前往{C:attention}比賽資訊{}區塊",
[2]="查看你的{C:attention}牌型",
[3]="以及其他跟目前比賽",
[4]="有關的資訊",
},
["sh_3"]={
[1]="選擇手上最多{C:attention}2{}張牌",
[2]="然後在{C:tarot}塔羅牌{}上",
[3]="按下{C:attention}「使用」{}",
[4]="就能加強效果！",
},
["fh_7"]={
[1]="請小心，每回合",
[2]="{C:blue}出牌{}和{C:red}棄牌{}次數",
[3]="皆有上限",
},
["fh_5"]={
[1]="現在，最多",
[2]="選擇{C:attention}5{}張牌",
[3]="並按下{C:blue}「出牌」",
},
["sh_2"]={
[1]="別忘了",
[2]="{C:attention}使用{}您的消耗牌！",
},
["bb_2"]={
[1]="您也可以選擇{C:attention}跳過",
[2]="取得{C:attention}標籤{}！每個",
[3]="{C:attention}標籤{}都有獨特的效果",
},
["s_7"]={
[1]="這張{C:tarot}塔羅牌{}是",
[2]="{C:attention}消耗牌{}，可以",
[3]="加強您打出的牌。",
[4]="好好留著這張牌！",
},
["s_3"]={
[1]="這是{C:attention}#1#張其中一張",
[2]="可以加到比賽的",
[3]="{C:attention}小丑牌{}。每張{C:attention}小丑牌",
[4]="都有不一樣的功能",
},
["s_11"]={
[1]="快去看看兩個",
[2]="商店賣的{C:booster}擴充包{}，",
[3]="每次商店都會販售，",
[4]="擴充包有滿滿好康！",
},
["bb_1"]={
[1]="選擇{C:attention}大盲注",
[2]="將賺到現金",
},
["sh_1"]={
[1]="如果您有多張牌卡，",
[2]="記得您可以重新",
[3]="理牌。{C:attention}小丑牌{}觸發",
[4]="是從左到右的排列方式",
},
["sb_4"]={
[1]="選擇{C:blue}小盲注",
[2]="開始這一回合！",
},
["s_4"]={
[1]="這張可以增加{C:red}+4倍數{}到",
[2]="您打出的每張牌！",
},
["s_10"]={
[1]="{C:attention}禮券{}會在",
[2]="您擊敗{C:attention}Boss盲注{}",
[3]="後重新上架。",
},
["s_12"]={
[1]="我們現在進入",
[2]="{C:attention}下一回合{}。",
},
["sb_2"]={
[1]="您的目標是要賺取",
[2]="{C:blue}籌碼{}來擊敗",
[3]="對手的{C:attention}盲注",
},
["s_6"]={
[1]="現在，從{C:attention}商店購買",
[2]="另一張卡牌。",
},
["s_2"]={
[1]="試試買這張",
[2]="帥氣的小丑牌",
},
["sb_1"]={
[1]="您好！我的名字是",
[2]="{C:attention}金寶{}，讓我來幫您",
[3]="瞭解遊玩的方式！",
},
["sb_3"]={
[1]="這裡是{C:blue}小盲注{}，",
[2]="您只需要獲得",
[3]="{C:attention}300籌碼{}就可以擊敗他。",
},
["fh_8"]={
[1]="在使用所有{C:blue}手牌次數前",
[2]="賺取{C:attention}300籌碼{}",
[3]="贏得這一回合。",
[4]="祝您好運！",
},
["s_9"]={
[1]="如果您有足夠積蓄，",
[2]="也可考慮購買{C:attention}禮券{}。",
[3]="{C:attention}禮券{}可以",
[4]="幫您升級比賽！",
},
["s_8"]={
[1]="您一次最多",
[2]="可以攜帶",
[3]="{C:attention}2張消耗牌{}",
},
["bb_5"]={
[1]="打敗{C:attention}底注{}#1#就能獲勝",
[2]="現在做出您的選擇吧！",
},
["bb_3"]={
[1]="不過請小心",
[2]="{C:attention}Boss盲注{}。每個Boss盲注",
[3]="都有著限制條件",
[4]="您必須要有策略來應對。",
},
["s_1"]={
[1]="很棒！現在",
[2]="您有一些{C:money}現金{}，",
[3]="立即前往{C:attention}商店",
[4]="買一些新卡牌吧！",
},
},
["labels"]={
["foil"]="銀箔",
["blue_seal"]="藍色封蠟章",
["rare"]="稀有",
["voucher"]="禮券",
["purple_seal"]="紫色封蠟章",
["gold_seal"]="金色封蠟章",
["red_seal"]="紅色封蠟章",
["tarot"]="塔羅牌",
["negative"]="負片",
["pluto_planet"]="矮行星",
["common"]="一般",
["pinned_left"]="已釘選",
["legendary"]="傳奇",
["eternal"]="永恆",
["holographic"]="全像攝影",
["uncommon"]="罕見",
["planet"]="行星牌",
["locked"]="已鎖定",
["polychrome"]="彩色",
},
["ranks"]={
["4"]="4",
["8"]="8",
["10"]="10",
["5"]="5",
["9"]="9",
["6"]="6",
["King"]="K",
["Ace"]="A",
["3"]="3",
["7"]="7",
["Jack"]="J",
["Queen"]="Q",
["2"]="2",
},
["high_scores"]={
["furthest_round"]="最高回合",
["hand"]="最好的一手",
["furthest_ante"]="最高底注",
["collection"]="收藏",
["current_streak"]="",
["boss_streak"]="最多連續好牌",
["poker_hand"]="最常出的牌",
["most_money"]="最多資金",
["win_streak"]="至佳連贏",
},
["suits_plural"]={
["Spades"]="黑桃",
["Hearts"]="紅心",
["Diamonds"]="方塊",
["Clubs"]="梅花",
},
["poker_hand_descriptions"]={
["Flush House"]={
[1]="三條和對子與",
[2]="所有牌分享相同花色",
},
["Full House"]={
[1]="三條和對子",
},
["Flush"]={
[1]="5張相同花色的牌",
},
["Pair"]={
[1]="2張相同點數的牌。可以與",
[2]="最多其他3張未計分的牌卡一起出",
},
["Four of a Kind"]={
[1]="4張牌一樣點數。可以與",
[2]="其他1張未計分的牌一起出",
},
["Royal Flush"]={
[1]="5張牌一連(連續數字)且",
[2]="所有牌分享相同花色",
},
["Straight Flush"]={
[1]="5張牌一連(連續數字)且",
[2]="所有牌分享相同花色",
},
["Straight"]={
[1]="5張牌一連(連續數字)",
},
["Five of a Kind"]={
[1]="5張相同點數的牌",
},
["Flush Five"]={
[1]="5張相同點數與花色的牌",
},
["Two Pair"]={
[1]="兩對不同點數的牌。可以與",
[2]="其他1張未計分的牌一起出",
},
["Three of a Kind"]={
[1]="3張牌相同點數的牌。可以與",
[2]="其他2張未計分的牌卡一起出",
},
["High Card"]={
[1]="如果玩的手牌不屬於上述任一種，",
[2]="只有最高點數的牌可以計入分數",
},
},
},
}